### ISSUE TITLE
Allow custom headers

### ISSUE THREAD

**Issue by vincentarnaud90** [elastic/rally#1000]
**Describe the feature**:
Hello, 
I have a custom elasticsearch plugin that requires HTTP headers and following [this post](https://discuss.elastic.co/t/custom-headers/234669) on dicuss I'd like to know if it's possible to add the ability to pass custom headers either through `--client-options` and/or on a per operation basis by allowing an `headers` key in operations on track definition, thus allowing not to systematically use the `raw-request` operation.

**Comment by danielmitterdorfer** [comment]
Closed by https://github.com/elastic/rally/pull/1070
