### ISSUE TITLE
Facing problem while running esrally command

### ISSUE THREAD

**Issue by rajeevkri** [elastic/rally#1005]
**Rally version** (get with `esrally --version`): 1.4.1

**Invoked command**: esrally

**Configuration file (located in `~/.rally/rally.ini`))**:  Yes

**JVM version**: 14.0.1

**OS version**: Ubuntu 18.04.4 LTS

**Description of the problem including expected versus actual behavior**: while running esrally facing below error 
[ERROR] Cannot race. ('Could not clone from [https://github.com/elastic/elasticsearch.git] to [/usr/share/elasticsearch]', None)
        Traceback (most recent call last):

**Steps to reproduce**:
 1. install my own elasticsearch 7.7.0 version 
 2. installed esrally and called "configure --advanced-config" to configure and map to current elasticsearch
 3. run esrally command, then i got this error

**Provide logs (if relevant)**:

`
    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

[INFO] Preparing for race ...
[ERROR] Cannot race. ('Could not clone from [https://github.com/elastic/elasticsearch.git] to [/usr/share/elasticsearch]', None)
        Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/esrally/mechanic/mechanic.py", line 565, in receiveMsg_StartNodes
    self.mechanic.start_engine()
  File "/usr/local/lib/python3.6/dist-packages/esrally/mechanic/mechanic.py", line 676, in start_engine
    binaries = self.supply()
  File "/usr/local/lib/python3.6/dist-packages/esrally/mechanic/supplier.py", line 218, in __call__
    supplier.fetch()
  File "/usr/local/lib/python3.6/dist-packages/esrally/mechanic/supplier.py", line 236, in fetch
    SourceRepository("Elasticsearch", self.remote_url, self.src_dir).fetch(self.revision)
  File "/usr/local/lib/python3.6/dist-packages/esrally/mechanic/supplier.py", line 443, in fetch
    self._try_init(may_skip_init=revision == "current")
  File "/usr/local/lib/python3.6/dist-packages/esrally/mechanic/supplier.py", line 453, in _try_init
    git.clone(self.src_dir, self.remote_url)
  File "/usr/local/lib/python3.6/dist-packages/esrally/utils/git.py", line 53, in clone
    raise exceptions.SupplyError("Could not clone from [%s] to [%s]" % (remote, src))
esrally.exceptions.SupplyError: ('Could not clone from [https://github.com/elastic/elasticsearch.git] to [/usr/share/elasticsearch]', None)

Getting further help:
*********************
* Check the log files in /root/.rally/logs for errors.
* Read the documentation at https://esrally.readthedocs.io/en/1.4.1/
* Ask a question on the forum at https://discuss.elastic.co/c/elasticsearch/rally
* Raise an issue at https://github.com/elastic/rally/issues and include the log files in /root/.rally/logs.

-------------------------------
[INFO] FAILURE (took 6 seconds)
`

**Describe the feature**: getting error while running esrally command

**Comment by dliappis** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Rally forum](https://discuss.elastic.co/c/elasticsearch/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch/rally) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
