### ISSUE TITLE
Revamp command line results table

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#103]
Currently, the command line results table is one big chunk. We should do the following changes:

* Separate queries from other statistics (as they take up quite some space)
* Use another format, ideally one that we can directly paste as Github flavored Markdown

Thanks to @rjernst for the suggestions.

**Comment by monk-ee** [comment]
Hi @danielmitterdorfe, I would be happy to give this one a bash. I will have a look at the current blob - and see what options we have to display. When we agree on the display format, i can then implement it.

**Comment by monk-ee** [comment]
Current stats look like this:
Racing on track [geonames] and challenge [append-no-conflicts] with car [defaults]
  Benchmarking indexing at 16729.2 docs/s                            [100% done]
  Benchmarking stats (warmup iteration 100/100)                      [100% done]
  Benchmarking stats (iteration 100/100)                             [100% done]
  Benchmarking search (warmup iteration 1000/1000)                   [100% done]
  Benchmarking search (iteration 0/1000)                             [  0% done]
  Benchmarking search (iteration 1000/1000)                          [100% done]
------------------------------------------------------
    _______             __   _____                    
   / ____(_)___  ____ _/ /  / ___/_________  ________ 
  / /_  / / __ \/ __ `/ /   \__ \/ ___/ __ \/ ___/ _ \
 / __/ / / / / / /_/ / /   ___/ / /__/ /_/ / /  /  __/
/_/   /_/_/ /_/\__,_/_/   /____/\___/\____/_/   \___/ 
------------------------------------------------------
                                                   Metric     Value
---------------------------------------------------------  --------
                         Min Indexing Throughput [docs/s]     16322
                      Median Indexing Throughput [docs/s]     16758
                         Max Indexing Throughput [docs/s]     17354
                                      Indexing time [min]   65.2369
                                         Merge time [min]   14.2558
                                       Refresh time [min]   5.48265
                                         Flush time [min]   0.41285
                                Merge throttle time [min]   1.16163
  Query latency country_agg_cached (90.0 percentile) [ms]    1.4993
  Query latency country_agg_cached (99.0 percentile) [ms]   1.64125
  Query latency country_agg_cached (99.9 percentile) [ms]   5.20068
   Query latency country_agg_cached (100 percentile) [ms]   5.48076
             Query latency default (90.0 percentile) [ms]   39.4852
             Query latency default (99.0 percentile) [ms]   50.1238
             Query latency default (99.9 percentile) [ms]   51.3614
              Query latency default (100 percentile) [ms]   55.6018
              Query latency scroll (90.0 percentile) [ms]    20.775
              Query latency scroll (99.0 percentile) [ms]   21.4549
              Query latency scroll (99.9 percentile) [ms]   21.7414
               Query latency scroll (100 percentile) [ms]   21.8215
                Query latency term (90.0 percentile) [ms]    1.4881
                Query latency term (99.0 percentile) [ms]   4.03789
                Query latency term (99.9 percentile) [ms]   5.02154
                 Query latency term (100 percentile) [ms]   5.15831
              Query latency phrase (90.0 percentile) [ms]   1.90016
              Query latency phrase (99.0 percentile) [ms]   4.76495
              Query latency phrase (99.9 percentile) [ms]   5.29573
               Query latency phrase (100 percentile) [ms]   8.38323
Query latency country_agg_uncached (90.0 percentile) [ms]   264.426
Query latency country_agg_uncached (99.0 percentile) [ms]   304.563
Query latency country_agg_uncached (99.9 percentile) [ms]   332.257
 Query latency country_agg_uncached (100 percentile) [ms]   366.988
                             Median CPU usage (index) [%]     692.5
                             Median CPU usage (stats) [%]     142.9
                            Median CPU usage (search) [%]    217.15
                                   Total Young Gen GC [s]    53.877
                                     Total Old Gen GC [s]     8.131
                                          Index size [GB]   3.24356
                                     Totally written [GB]   18.3658
                              Heap used for segments [MB]   21.3325
                            Heap used for doc values [MB]  0.112911
                                 Heap used for terms [MB]   19.7005
                                 Heap used for norms [MB]  0.078125
                                Heap used for points [MB]  0.771404
                                Heap used for points [MB]  0.669525
                                            Segment count       101
                      Indices Stats(90.0 percentile) [ms]    4.2005
                      Indices Stats(99.0 percentile) [ms]   4.53104
                       Indices Stats(100 percentile) [ms]   4.67669
                        Nodes Stats(90.0 percentile) [ms]   4.31434
                        Nodes Stats(99.0 percentile) [ms]    4.7264
                         Nodes Stats(100 percentile) [ms]   5.35763

**Comment by monk-ee** [comment]
Maybe a screen shot:
![image](https://cloud.githubusercontent.com/assets/365583/15660229/93aeff9c-271c-11e6-852c-1f1c9c67aa02.png)

**Comment by monk-ee** [comment]
Thoughts in this are:

- Choose your output format eg --output=(json | markdown | summary)
- Choose your output destination --output-destination=(screen | file | elasticsearch)

**Comment by danielmitterdorfer** [comment]
> Choose your output format eg --output=(json | markdown | summary)

I think this is a good idea and I sense the default should be Markdown. Btw, I also had a short look on this and it seems that `tabulate` supports Markdown with `tablefmt="pipe" (see also the [tabulate page on PyPI](https://pypi.python.org/pypi/tabulate)).

> Choose your output destination --output-destination=(screen | file | elasticsearch)

All data are already kept in the metrics store. If your metrics store is Elasticsearch you already have everything. I would just write the report to stdout and the log file (which is already the case). It could make sense though to support an option to write the report directly to a file.

What do you think?

**Comment by danielmitterdorfer** [comment]
I have now added two new options:

* `--report-format`: markdown (default) or csv
* `--report-file`: which specifies a file to write the report to. The report will always be shown on the console in the selected report format
