### ISSUE TITLE
Getting help link redirects to 404 URL

### ISSUE THREAD

**Issue by bartier** [elastic/rally#1036]
When trying to find rally discuss forum, I ran into a 404 page, I'm not sure if it is a Elastic private link or something. 

The link is from the README.md getting help section, the URL ["Rally Discuss forum"](https://discuss.elastic.co/c/elasticsearch/rally).

I also noted this occurs in [ISSUE_TEMPLATE](https://raw.githubusercontent.com/elastic/rally/master/.github/ISSUE_TEMPLATE.md).

![image](https://user-images.githubusercontent.com/18057391/88613361-a7932700-d063-11ea-9d88-51cf3f46e5ec.png)

**Comment by danielmitterdorfer** [comment]
Thanks for reporting. I've pushed https://github.com/elastic/rally/pull/1037 to update the URL.
