### ISSUE TITLE
Elasticsearch as a data store fails for the default test.

### ISSUE THREAD

**Issue by monk-ee** [elastic/rally#104]
**Rally version** (get with `esrally --version`):
rally 0.3.0.dev0

**Invoked command**:
 ./rally --pipeline=from-distribution --distribution-version=5.0.0-alpha2

**Configuration file (located in `~/.rally/rally.ini`))**:

**JVM version**:
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

**OS version**:
Ubuntu 16.04 LTS \n \l
Linux ip-172-31-50-139 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
When you select elasticsearch as the store for the test, there are no queries in the track.

If you run the in-memory data store option, the benchmark runs fine.

Traceback (most recent call last):
  File "/home/rally/.local/bin/esrally", line 9, in <module>
    load_entry_point('esrally', 'console_scripts', 'esrally')()
  File "/home/rally/rally/esrally/rally.py", line 271, in main
    success = dispatch_sub_command(cfg, sub_command)
  File "/home/rally/rally/esrally/rally.py", line 225, in dispatch_sub_command
    return race_control.start(sub_command)
  File "/home/rally/rally/esrally/racecontrol.py", line 288, in start
    raise e
  File "/home/rally/rally/esrally/racecontrol.py", line 267, in start
    metrics.race_store(self._config).store_race(t)
  File "/home/rally/rally/esrally/metrics.py", line 649, in store_race
    "queries": [q.name for q in t.queries],

**Steps to reproduce**:
 1. Select advanced configuration and add an external elasticsearch server to store results.
 2. Run the default test

**Comment by danielmitterdorfer** [comment]
Thanks for reporting this @monk-ee. Upon first glance I introduced this bug by restructuring tracks. This should be fixed soon. Btw, this problem does not occur with the in-memory store as it does not store races at all (storing races is currently only needed to support the [tournament mode](https://esrally.readthedocs.io/en/latest/tournament.html)).

**Comment by danielmitterdorfer** [comment]
@monk-ee The issue should be fixed now. You should just need to run the original command again as it automatically updates Rally if your local checkout is clean. Otherwise you can also manually rebase your local working copy and rerun the command.
