### ISSUE TITLE
How to download the benchmark files before run a test?

### ISSUE THREAD

**Issue by godlockin** [elastic/rally#1042]
As the poor web connection and network speed, I always met the read timeout exception during i my first step of run a race -> download the benchmark file 

```
[INFO] Downloading data for track nyc_taxis (4.5 GB total size)                   [  1.8%]
[ERROR] Cannot race. Error in track preparator (HTTPConnectionPool(host='benchmarks.elasticsearch.org.s3.amazonaws.com', port=80): Read timed out.)
```

Is there able to download the benchmark files into the benchmark folder before run the rally? If so, what is the files' download path?

**Comment by godlockin** [comment]
yes, I know I can make a custom race myself, but it's quite difficult for me to preparing so a benchmark dataset with so much data lines to do that :(

**Comment by dliappis** [comment]
Thanks very much for your interest in Rally.

This appears to be a user question, and we'd like to direct these kinds of things to the [Rally forum](https://discuss.elastic.co/tags/c/elastic-stack/elasticsearch/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/tags/c/elastic-stack/elasticsearch/rally) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
