### ISSUE TITLE
Support datastreams in Rally

### ISSUE THREAD

**Issue by gingerwizard** [elastic/rally#1053]
Propose the following features be core operations in Rally due to the applicability to common workloads:

- [x] Create a datastream - https://www.elastic.co/guide/en/elasticsearch/reference/master/set-up-a-data-stream.html#manually-create-a-data-stream
- [x] Delete a datastream - https://www.elastic.co/guide/en/elasticsearch/reference/master/set-up-a-data-stream.html#delete-a-data-stream
- [x] Bulk indexing - https://www.elastic.co/guide/en/elasticsearch/reference/master/use-a-data-stream.html#data-streams-bulk-indexing-requests I'm not sure we need changes here as the structure is the same as a bulk request @dliappis but we might want to limit to create actions only. 
- [x] Stats API support - https://github.com/elastic/rally/issues/1161
- [x] ~Ability to rollover a datastream - https://www.elastic.co/guide/en/elasticsearch/reference/master/use-a-data-stream.html#manually-roll-over-a-data-stream We can potentially support this through a new runner. Note the event data supports this via [this runner](https://github.com/elastic/rally-eventdata-track/blob/master/eventdata/runners/rollover_runner.py). We want this rollover to occur during indexing, however - so we may want to incorporate it into the bulk action itself. To discuss with @dliappis. This is low priority and likely to be used infrequently if we recommend using ILM for rollover.~ Dropped in support of ILM. https://github.com/elastic/rally/issues/1087

Datastreams support a[ number of other operations](https://www.elastic.co/guide/en/elasticsearch/reference/master/use-a-data-stream.html#manually-roll-over-a-data-stream) e.g. Updating documents by query. I don't believe these will be used regularly in workloads however and can be implemented as custom runners if needed.

**Comment by hub-cap** [comment]
I have hit an issue on the [prometheus track PR](https://github.com/elastic/rally-internal-tracks/pull/14) that also needs `create-datastream`, and would love to see this done as a good first step. Lets chat tomorrow @gingerwizard about timing of this first step.

**Comment by gingerwizard** [comment]
Code merged. Pending IT and docs.

**Comment by gingerwizard** [comment]
@danielmitterdorfer we will need data streams stats. My initial instinct is to add as a runner like https://esrally.readthedocs.io/en/stable/track.html?highlight=index%20stats#index-stats? Any other approaches you'd like to consider?

**Comment by danielmitterdorfer** [comment]
If we want custom metrics I suggest we implement a so-called telemetry device similar to: https://github.com/elastic/rally/blob/4d4f8633a91c34b5fe9a58734a2ffc30c815569b/esrally/telemetry.py#L1243.

**Comment by gingerwizard** [comment]
👍  appreciate the guidance.
