### ISSUE TITLE
Support composable templates 

### ISSUE THREAD

**Issue by gingerwizard** [elastic/rally#1054]
7.8 introduced [composable and component templates](https://www.elastic.co/guide/en/elasticsearch/reference/7.8/index-templates.html). The unique api endpoints mean this is work.

We may want to separate these into different operations given the unique endpoints. A user would therefore index a set of component templates, followed by their composable templates. 

Alternatively, we could extend the current [create-template action](https://esrally.readthedocs.io/en/stable/track.html#create-index-template) to accept a `mode` where it first inserts the declared `component_templates` and then `composable_templates` that have been declared in the track. This would be a non breaking change as the mode would default to `legacy` which would cause the current behaviour.

@dliappis @danielmitterdorfer happy to take but please advise

**Comment by danielmitterdorfer** [comment]
Thanks for raising this. I tend to the first option of dedicated runner(s) as I don't think Rally should abstract the Elasticsearch APIs much.

**Comment by dliappis** [comment]
Also :+1: on dedicated runners; these should be first class citizens in Rally.

**Comment by gingerwizard** [comment]
@danielmitterdorfer @dliappis the current template implementation uses the deprecated API. I'm not sure if the intention is to remove this in 8.0. For now, i propose we make these additions.

Do we want these to be first class definitions in the track? i.e.  `component_templates` and `index_templates` (composable). The former need to be inserted before the latter i believe so a runner could consume both definitions and ensure this occurs.

Alternatively, we could require a single definition e.g. `index_templates` under which the user defines both composable and component templates. The runner could then either inspect the body to determine the appropriate API or use a `type` field defined in the track definition for each template e.g. 

```
"index_templates": [
    {
        "name": "my-default-index-template",
        "index-pattern": "my-index-*",
        "template": "default-template.json",
        "type": "component"
    }
]
```

The benefit of declaring these as first class citizens is that we can use the definitions in other runners should we need them e.g. for validation.

**Comment by gingerwizard** [comment]
Closed by https://github.com/elastic/rally/pull/1099
