### ISSUE TITLE
Update documentation to mention that --include-tasks and --exclude-tasks does not affect order of execution

### ISSUE THREAD

**Issue by tlrx** [elastic/rally#1056]
I've been confused today by how the `--include-tasks` and `--exclude-tasks` command line flags are working when a subset of tasks is specified for the run.

For example, I wrote a challenge which contains:
```json 
{
  "name": "my-challenge",
  "schedule": [
          {
            "name": "task-A", ...
          },
          {
            "name": "task-B", ...
          },
          {
            "name": "task-C", ...
          }
  ], ...
}
```

Then I executed a benchmark in Rally using `--include-tasks=task-C,task-B,task-A` and I'd expect the tasks to be executed in the order they are specified in the command (C then B then A) but actually they are executed in the order they are defined in the challenge (A then B then C).

I think the documentation should be updated to mention that the `--include-tasks` (and --exclude-tasks) just filters out the tasks to be executed but does not affect the order they are executed.

I also think that being able to specify a different order for a subset of tasks is useful.

**Comment by danielmitterdorfer** [comment]
Closed by https://github.com/elastic/rally/pull/1102
