### ISSUE TITLE
Allow to define operation parameters dynamically

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#107]
After #58 and #64 are implemented, we can have parameters for operations. However, these parameters are only static but for certain use cases we want to change parameter values for each invocation. Examples are:

* Retrieving random documents (see #106)
* Dynamically changing the terms that should be queried in order to provoke query cache misses
* Dynamically creating synthetic data for indexing instead of defining a data file

**Comment by AndyDev2017** [comment]
@danielmitterdorfer 
Hi, I would like to know if the requirement **"Dynamically changing the terms that should be queried in order to provoke query cache misses"** was implemented as I would like the means to supply a list of query terms to be randomly used. Thanks, Andrew

**Comment by danielmitterdorfer** [comment]
@AndyDev2017 yes this has been implemented. You need to write something called a "custom parameter source" to make this work. An [example is provided in the docs](http://esrally.readthedocs.io/en/stable/adding_tracks.html#custom-parameter-sources). With #365 
 we will implement better support in Rally.

If you have follow-up questions, it's better to post them in [our user forum](https://discuss.elastic.co/c/elasticsearch/rally) as other users might be interested as well and the discussion is easier to find there.
