### ISSUE TITLE
Adding glossary of metrics 

### ISSUE THREAD

**Issue by eugenemiretsky** [elastic/rally#109]
It would be great to have a list of all the metric Rally stores. 

Right now, building a Kibana dashboard requires reverse engineering the names. Also some of the metrics are not obvious (for example: cpu_utilization_1s)

**Comment by danielmitterdorfer** [comment]
Great idea. I see if I can get it in for the next release. Please be aware that some of the metric keys will change a bit due to #108. As we'll capture throughput and latency for each operation now, I had to come up with more generic names for these metrics. But the others should stay as is IIRC.

**Comment by danielmitterdorfer** [comment]
@eugenemiretsky: As a workaround in the meantime you can look at https://github.com/elastic/rally/blob/master/esrally/reporter.py, there you'll find all metrics that are reported on the command line.
