### ISSUE TITLE
Allow users to pick ID

### ISSUE THREAD

**Issue by eugenemiretsky** [elastic/rally#111]
Right now the options for Index Ids are:
- NoConflicts: Produce no id conflicts
- SequentialConflicts: A document id is replaced with a document id with a sequentially increasing id
- RandomConflicts: A document id is replaced with a document id with a random other id

It would be nice to add an option to use our own IDs.

**Comment by danielmitterdorfer** [comment]
Currently, the data files contain only the data in a bulk-friendly format (i.e. one JSON record per line). Rally automatically adds the "action and meta data line" (see also [bulk docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html)). We could introduce a mode that just indexes the file as is and assumes that the data file contains also the "action and meta data line". So instead of:

```
{"@timestamp": 893964617, "clientip":"40.135.0.0", "request": "GET /images/hm_bg.jpg HTTP/1.0", "status": 200, "size": 24736}
{"@timestamp": 893964653, "clientip":"232.0.0.0", "request": "GET /images/hm_bg.jpg HTTP/1.0", "status": 200, "size": 24736}
```

your data file would contain:

```
{"index": {"_index": "logs", "_type": "http, "_id": "1"}}
{"@timestamp": 893964617, "clientip":"40.135.0.0", "request": "GET /images/hm_bg.jpg HTTP/1.0", "status": 200, "size": 24736}
{"index": {"_index": "logs", "_type": "http, "_id": "2"}}
{"@timestamp": 893964653, "clientip":"232.0.0.0", "request": "GET /images/hm_bg.jpg HTTP/1.0", "status": 200, "size": 24736}
```

The only trappy part from a usability perspective is that you still need to provide the number of data records in the data file (i.e. number of lines / 2) in the track.json file.

**Comment by danielmitterdorfer** [comment]
Setting preliminary target to 0.4.0 (but it might not make it)

**Comment by danielmitterdorfer** [comment]
Marking as "Blocked", we should not start work on this ticket until #108 is in.

**Comment by eugenemiretsky** [comment]
As an alternative solution to, could we just assume that the first field is the id? Or use 'id' as a reserved field name? 
So the data file would look like 
`{"id": 1, @timestamp": 893964617, "clientip":"40.135.0.0", "request": "GET /images/hm_bg.jpg HTTP/1.0", "status": 200, "size": 24736}
{"id": 2, "@timestamp": 893964653, "clientip":"232.0.0.0", "request": "GET /images/hm_bg.jpg HTTP/1.0", "status": 200, "size": 24736}`

**Comment by danielmitterdorfer** [comment]
Hi Eugene, thanks for your idea but I'd rather not do this. For starters: we currently treat the input file as opaque string. If we do this we have to start parsing JSON on a critical code path and I'd rather avoid this. 

I think we're much more flexible if we just add support for the "normal" bulk index format.

And it would still depend on the monster ticket #108 which I currently implement so we cannot get this in any faster...

What do you think?

**Comment by danielmitterdorfer** [comment]
@eugenemiretsky Do you have any issues with the approach that I have in mind? The only disadvantage that I've come up with is that it increases the size of the benchmark file. But apart from that it is quite flexible and should not be that complex to implement.

**Comment by danielmitterdorfer** [comment]
In version 0.4.5, the index operation will support a new option `action-and-meta-data` which is `generate` by default and does not need to be specified. If you want to provide your own action and meta-data line, you'd specify:

```json
{
      "name": "index-append",
      "operation-type": "index",
      "bulk-size": 5000,
      "action-and-meta-data": "sourcefile"
}
```

Rally, will then just read 5.000 documents (i.e. 10.000 lines!) from the file that you define for the associated index and send it to Elasticsearch via the bulk API. You can also specify `none` and in that case Rally will set index and type in the bulk request to Elasticsearch.
