### ISSUE TITLE
Allow to benchmark against externally provisioned clusters with https + basic auth

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#114]
This is really a (very) lightweight-version of #60. If we want to benchmark a cluster with Shield enabled, there is no possibility so far as Rally always assumes http traffic so far. With this ticket, we'll add support to the `--benchmark-only` pipeline (and only to that one) to allow users to specify the protocol (http/https) and credentials.

**Comment by danielmitterdorfer** [comment]
We now allow to define arbitrary client options with `--client-options` (see [docs](http://esrally.readthedocs.io/en/latest/command_line_flags.html#client-options)).

**Comment by lightkz** [comment]
Thank you Daniel!

**Comment by danielmitterdorfer** [comment]
Much appreciated Askar. I hope you find it useful. :)
