### ISSUE TITLE
Support Point-in-time API

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#1141]
Currently Rally only supports the scroll API for paginating search results. Elasticsearch has introduced a [point-in-time API](https://www.elastic.co/guide/en/elasticsearch/reference/current/point-in-time-api.html) that we should also support similar to how we do it with async search since https://github.com/elastic/rally/pull/1129 (i.e. also assume the same restrictions such as it is only allowed in the context of a `composite` task). We should specifically make sure to add support for [`search_after`](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after) using the point-in-time API.

**Comment by DJRickyB** [comment]
I've started on this.  there are a couple of structural considerations, ultimately I've started down the path of each of the following being a supported operation:
* Open Point In Time (requires composite context)
* Close Point In Time (requires composite context)
* Query with Search After Pagination (P-I-T, and hence composite, optional)
The meat of this approach is here -> 80b4390ab65580484ae48ea2518889668206361d
