### ISSUE TITLE
UnicodeEncodeError when `esrally configure`

### ISSUE THREAD

**Issue by goofansu** [elastic/rally#115]
**Rally version** (get with `esrally --version`): 0.3.0

**Invoked command**: `esrally configure`

**JVM version**: 

```
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**OS version**: `Linux ELK-Data1 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. esrally configure

# Additional Information

python version: `3.4.3`

pip version: `pip 1.5.4 from /usr/lib/python3/dist-packages (python 3.4)`

# Error

```
Traceback (most recent call last):
  File "/usr/local/bin/esrally", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/esrally/rally.py", line 245, in main
    ensure_configuration_present(cfg, args, sub_command)
  File "/usr/local/lib/python3.4/dist-packages/esrally/rally.py", line 212, in ensure_configuration_present
    config.ConfigFactory().create_config(cfg.config_file, advanced_config=args.advanced_config)
  File "/usr/local/lib/python3.4/dist-packages/esrally/config.py", line 222, in create_config
    self.o("[\u2713] Autodetecting available third-party software")
UnicodeEncodeError: 'ascii' codec can't encode character '\u2713' in position 1: ordinal not in range(128)
```

**Comment by danielmitterdorfer** [comment]
This is most likely caused by an environment problem. It seems you don't have set the LANG environment variable (or to some value that does not support UTF-8).

Can you please run `echo $LANG`? If it prints nothing, you can set it with `export LANG="en_US.UTF-8"` and then invoke `esrally configure`. If this works, you should permanently add LANG to your environment (e.g. add it to `/etc/default/locale` if you are the admin or else to your shell config (e.g. `~/.bash_profile`)

**Comment by danielmitterdorfer** [comment]
If this does not help, can you please add the output of `env | grep LC` to this ticket?

**Comment by goofansu** [comment]
Hi, `LANG` is already`en_US.UTF-8`. Then I set `export LC_ALL="en_US.UTF-8"` and it succeed.

**Comment by danielmitterdorfer** [comment]
Great, thanks for the feedback. Then I'll add a hint to the docs so it doesn't bite other users as well.

**Comment by goofansu** [comment]
Thank you for the quick reply 👍

**Comment by danielmitterdorfer** [comment]
Sure, you're welcome. The new docs are already online: https://esrally.readthedocs.io/en/latest/#configuring-rally
