### ISSUE TITLE
Allow configuring sniff option 

### ISSUE THREAD

**Issue by eugenemiretsky** [elastic/rally#116]
Allow configuring  sniffing options to pass into ElasticSearch constructor  (instead of the default ON)

`es = Elasticsearch(
    ['esnode1', 'esnode2'],
    # sniff before doing anything
    sniff_on_start=True,
    # refresh nodes after a node fails to respond
    sniff_on_connection_fail=True,
    # and also every 60 seconds
    sniffer_timeout=60
)`

**Comment by danielmitterdorfer** [comment]
We now allow to define arbitrary client options with `--client-options` (see [docs](http://esrally.readthedocs.io/en/latest/command_line_flags.html#client-options)).
