### ISSUE TITLE
Create datastreams-stats telemetry device

### ISSUE THREAD

**Issue by dliappis** [elastic/rally#1161]
As mentioned in https://github.com/elastic/rally/issues/1053 we need a telemetry device to consume the [data streams stats](https://www.elastic.co/guide/en/elasticsearch/reference/master/data-stream-stats-api.html) available in Elasticsearch.

**Comment by danielmitterdorfer** [comment]
For starters it would probably make sense to gather the following information for each data stream at the end of a benchmark:

* `data-stream`: name of the data stream
* `backing-indices`: number of indices backing this data stream
* `store-size`: number of bytes taken up by the data stream

We should capture this for all `open` data streams (which is the default anyway, see `expand_wildcards` in the [data stream stats API docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/data-stream-stats-api.html)).
