### ISSUE TITLE
Allow setting cluster config

### ISSUE THREAD

**Issue by eugenemiretsky** [elastic/rally#117]
Rally allows setting Index configs from a config file- is there a way to change Cluster configs? For example threadpool size (https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-threadpool.html)

**Comment by danielmitterdorfer** [comment]
It's currently not possible. The workaround in this case is to use `--pipeline=benchmark-only` and to set up the cluster by yourself. I expect that we need to revisit cluster configuration anyway with #71. I mention this ticket there as a reminder.

**Comment by danielmitterdorfer** [comment]
Closing in favor of #159 (we will tackle this problem there though).
