### ISSUE TITLE
Unable to use --kill-running-proccesses

### ISSUE THREAD

**Issue by Dranaxel** [elastic/rally#1186]
**Rally version** (get with `esrally --version`): 1.4.1

**Invoked command**: pipenv run esrally race --kill-running-processes --distribution-version=7.10.1 --target-hosts=XXX.XXX.XXX --track-params=params.json --pipeline=benchmark-only --track=$TRACK --report-file=~/esrally/$TRACK-result-$(date +%F%X)

**Configuration file (located in `~/.rally/rally.ini`))**:
```
[meta]
config.version = 17

[system]
env.name = local

[node]
root.dir = /home/ubuntu/.rally/benchmarks
src.root.dir = /home/ubuntu/.rally/benchmarks/src

[source]
remote.repo.url = https://github.com/elastic/elasticsearch.git
elasticsearch.src.subdir = elasticsearch

[benchmarks]
local.dataset.cache = /home/ubuntu/.rally/benchmarks/data

[reporting]
datastore.type = in-memory
datastore.host =
datastore.port =
datastore.secure = False
datastore.user =
datastore.password =

[tracks]
default.url = https://github.com/elastic/rally-tracks

[teams]
default.url = https://github.com/elastic/rally-teams

[defaults]
preserve_benchmark_candidate = False

[distributions]
release.cache = true
```

**OS version**: ubuntu 18.04 on every computer

**Description of the problem including expected versus actual behavior**:
I was expected to be able to kill all my processes without using htop, unfortunatelly I get the following answer: "esrally: error: unrecognized arguments: --kill-running-processes"

**Comment by danielmitterdorfer** [comment]
Thanks for your report! This flag has been introduced with Rally 2.0.0 in https://github.com/elastic/rally/pull/954 and is therefore not available in the version 1.4.1 that you're using so I suggest you upgrade to the latest version of Rally if you want to use this. 

You saw that flag probably in the documentation for the current stable version. You can use the versioned link for your version instead: https://esrally.readthedocs.io/en/1.4.1/
