### ISSUE TITLE
If there is a jinja error you don't get any error message

### ISSUE THREAD

**Issue by nik9000** [elastic/rally#1187]
I'm hacking on a track change now and getting messages like:
```
[ERROR] Cannot race. Error in race control (Could not load '/home/nik9000/Code/Elastic/rally-tracks/http_logs/track.json'. The complete track has been written to '/tmp/tmpo8b2g1ng.json' for diagnosis.)
```
There isn't a `/tmp/tmpo8b2g1ng.json`. I'm fairly sure this is because I have a syntax error in my jinja somewhere and jinja is bailing before it can write the file. I *think* jinja should have an error message telling me what I'm doing wrong. But I *think* we're eating the error message and not reporting it. Can we?

**Comment by nik9000** [comment]
In my case it was because I had a kebab case variable (`rutime-fields`) in the jinja. It needs snake case (`runtime_fields`).

**Comment by nik9000** [comment]
I see something pretty similar now with a message like:
```
[ERROR] Cannot race. Error in race control (Could not load file template for 'definition for index logs-181998 in index-runtime-fields.json')
```
I'm guessing I have new and unique jinja errors.

**Comment by nik9000** [comment]
It looks like I can get some or all of this from `rally.log`. It'd be nice to have the actual message from the json parser or jinja on the regular output though.

**Comment by ilam-es** [comment]
This is a more technical one, not a meta item that I am looking at for overall priority.
Daniel can decide on where this goes in terms of priority.
