### ISSUE TITLE
Description of available operation types in the docs

### ISSUE THREAD

**Issue by feng-tao** [elastic/rally#1189]
Is there a place in the doc which I could find all the available operation-type and what it is testing against? thanks

**Comment by feng-tao** [comment]
It seems to be defined in https://github.com/elastic/rally/blob/b8592a6071e549be99ac5538f960fe3026e513fb/esrally/track/track.py#L562-L607 . I wonder we could have a doc about what endpoint for each operation it tests it against. thanks.

**Comment by feng-tao** [comment]
Also my main question is "is it possible to test query search during bulk indexing"? Currently bulk index and query search are defined as two different operations. I wonder whether there is a way we could define one single operation to test query search during bulk indexing (our target workload pattern).

**Comment by feng-tao** [comment]
NVM, I end up using https://esrally.readthedocs.io/en/stable/track.html#composite to build my custom operation.

**Comment by danielmitterdorfer** [comment]
Hi! Operations are intended as primitives that you use to build your workload. If you want to execute a search workload concurrently while bulk indexing you should rather use a `parallel` element to specify that you want to execute both in parallel (see [example in the docs](https://esrally.readthedocs.io/en/stable/track.html#running-tasks-in-parallel). We also have a [rather complex example in the eventdata track](https://github.com/elastic/rally-eventdata-track/blob/master/eventdata/challenges/daily-log-index-fixed-throughput-and-query.json) which also takes advantage of Rally's templating features.

As we use Github only for bug reports and feature requests and have a [dedicated forum for questions](https://discuss.elastic.co/tags/c/elastic-stack/elasticsearch/6/rally) like these can I please ask you to stop by there if you have any more questions? I hope you don't mind that I therefore close this issue.

**Comment by feng-tao** [comment]
thanks
