### ISSUE TITLE
Mixed workload benchmark

### ISSUE THREAD

**Issue by eugenemiretsky** [elastic/rally#119]
It would be nice to be able to run a benchmark that mixes reads and writes to better simulate real world workloads. 
It is possible to do this now by running 2 Rally benchmark at the same time (one for read, and one for write), but it is not as scientific and reproducible.

**Comment by danielmitterdorfer** [comment]
I agree with you. I originally thought of adding this in the scope of #108 (see last sub task) but this ticket is already huge. I'd say this should be a separate ticket (this one).

**Comment by danielmitterdorfer** [comment]
That's now doable by using the `parallel` element to run multiple operations concurrently.
