### ISSUE TITLE
Line up decimal places please!

### ISSUE THREAD

**Issue by nik9000** [elastic/rally#1202]
When I run `esrally compare` I get a table that contains this bit:
```
| 1666.85 | 1555.73 | -111.116 | ms |
| 37.6112 |  38.016 |  0.40475 | ms |
| 2875.04 | 2934.54 |   59.493 | ms |
|  1515.4 | 1151.45 | -363.957 | ms |
```

That is hard for me to read so I always manually reformat it to:
```
| 1666.85   | 1555.73  | -111.116   | ms |
|   37.6112 |   38.016 |    0.40475 | ms |
| 2875.04   | 2934.54  |   59.493   | ms |
| 1515.4    | 1151.45  | -363.957   | ms |
```

Is that something rally could do by default?

**Comment by danielmitterdorfer** [comment]
We use the `tabulate` library to render tables and [column alignment can be configured](https://github.com/astanin/python-tabulate#column-alignment). Currently, Rally uses `numalign=right`:

https://github.com/elastic/rally/blob/1562fde791dc3c2343d935b5ce2dd02a15ca2e8a/esrally/reporter.py#L78

If we change this to `decimal` we get the output that you describe. IMHO that makes the layout a bit more "noisy" so I'd rather not enable this by default. Maybe we can make this configurable though.

**Comment by pquentin** [comment]
I believe this was done in #1236 and can be closed now.
