### ISSUE TITLE
Support Mount API for Searchable Snapshots

### ISSUE THREAD

**Issue by gingerwizard** [elastic/rally#1210]
A simple runner for the [mount API ](https://www.elastic.co/guide/en/elasticsearch/reference/7.11/searchable-snapshots-api-mount-snapshot.html)is trivial. 

However, in reality, we will want to mount multiple indices in a snapshot. Currently, the API only allows one index to be mounted at a time i.e. one per call. We need to verify we can run many at once, tracking the restore through the restore API.

I propose we support reading the snapshot and providing a mechanism to mount all the indices which match a pattern provided to the task e.g. `indices: logs-*`. I would imagine this will also mean providing a `rename_pattern` and `rename_replacement`to the task, which would, in turn, provide a `renamed_index` param for each `_mount` call.

cc @dliappis

**Comment by gingerwizard** [comment]
Confirmed there is no plan to support rename patterns or multiple indices in amount call. I propose we deal with this logic in a runner - given the need to make a snapshot GET call and find the matching indices/data-streams.

**Comment by ebadyano** [comment]
completed in https://github.com/elastic/rally-tracks/pull/306?
