### ISSUE TITLE
esrally CLI should always return 130 when cancelled

### ISSUE THREAD

**Issue by DJRickyB** [elastic/rally#1222]
Currently, if the actor system is initialized and tasks have started, a Ctrl+C sent to the CLI causes an orderly shutdown and logs a SUCCESS message, returning return code `0`.  For the sake of shell scripts or other invocations with `trap`s it would be nice if these were seen as a reason to tear down the outer workflow.

Current behavior (note tasks `delete-index` and `create-index` here are running.  If tasks are running, send Ctrl+C):
```
% esrally race --track=geonames --test-mode

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

[INFO] Preparing for race ...
[INFO] Racing on track [geonames], challenge [append-no-conflicts] and car ['defaults'] with version [8.0.0-SNAPSHOT].
Running delete-index                                                           [100% done]
Running create-index                                                           [  0% done]^C
--------------------------------
[INFO] SUCCESS (took 15 seconds)
--------------------------------

 % echo $?
   0
```

desired behavior (for instance):
```
% esrally race --track=geonames --test-mode

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

[INFO] Preparing for race ...
[INFO] Racing on track [geonames], challenge [append-no-conflicts] and car ['defaults'] with version [8.0.0-SNAPSHOT].
Running delete-index                                                           [100% done]
Running create-index                                                           [  0% done]^C
--------------------------------
[INFO] ABORTED (took 15 seconds)
--------------------------------

 % echo $?
   130
```

Note that `SUCCESS` is now `ABORTED`, and the return code of the command is `130` instead of `0`.  Bonus points if after Ctrl+C is sent some sort of acknowledgement is printed to `stderr` such as:
`Rally has detected KeyboardInterrupt. Shutting down...`

**Comment by madlad33** [comment]
Hello, can I work on this issue?

**Comment by DJRickyB** [comment]
@madlad33 Sure! Please submit a PR when you are ready 😄

**Comment by DJRickyB** [comment]
Also, in case you haven't seen it before, this project is governed by Elastic's Contributor License Agreement (CLA):
https://www.elastic.co/contributor-agreement

You must agree and sign there before we can merge in any contributions.  Thanks for looking at this!
