### ISSUE TITLE
Example command for "Running Rally with Docker" needs to be updated

### ISSUE THREAD

**Issue by jamshid** [elastic/rally#1232]
**Rally version** (get with `esrally --version`):
```
$  docker run elastic/rally --version 
esrally 2.1.0
```
**Invoked command**:
Just trying to run example from https://esrally.readthedocs.io/en/latest/docker.html

**Configuration file (located in `~/.rally/rally.ini`))**:
n/a (default from image)
**JVM version**:
n/a (default from image)
**OS version**:
n/a but Docker for Mac 
**Description of the problem including expected versus actual behavior**:
The example command given in docs should continue to work with latest version of the image.

**Steps to reproduce**:
 1.
```
$  docker run elastic/rally  --track=nyc_taxis --test-mode --pipeline=benchmark-only --target-hosts=192.168.1.147:9200
usage: esrally [-h] [--version]
               {race,list,info,create-track,generate,compare,download,install,start,stop}
               ...
esrally: error: unrecognized arguments: --track=nyc_taxis --test-mode --pipeline=benchmark-only --target-hosts=192.168.1.147:9200
```
 2. It does work if I specify image tag `:1.2.1`.

**Comment by danielmitterdorfer** [comment]
Thanks for your report. Indeed, Rally 2.1.0 requires now a subcommand and in the Docker examples we did not add the `race` subcommand in these examples.
