### ISSUE TITLE
Record shard and segment allocation

### ISSUE THREAD

**Issue by gingerwizard** [elastic/rally#1242]
Shard allocation can be critical to identifying potential performance issues e.g. hot spots.

We need a means to record which shards have been allocated to which nodes and their segment count. Ideally we also record the index and data stream to which these shards belong.

A runner might be sufficient initially, but given shard allocation changes during the lifetime of a test e.g. as indices rollover, a telemetry device similar to node stats would be preferable.

**Comment by dliappis** [comment]
Let's implement this as a telemetry device.
