### ISSUE TITLE
Collect stats telemetry at start and end of each operation

### ISSUE THREAD

**Issue by ywelsch** [elastic/rally#1246]
Rally provides a number of handy stats telemetry devices, e.g. node-stats or searchable-snapshot-stats. These are currently collected concurrently to running the track. When creating complex tracks with multiple operations, it would be handy, however, to have the stats collected at specific points as well, for example before or after each operation, so that the effect of operations can be better understood (especially shorter ones that take less time than the stats collection interval).

**Comment by dliappis** [comment]
Related to https://github.com/elastic/rally/issues/1224

**Comment by dliappis** [comment]
Thanks for raising this!

As discussed offline, I will close this in favor of #1248 where we'll explore ideas and layout implementation paths.
