### ISSUE TITLE
Suppress warning about clean state if it was within a threshold time

### ISSUE THREAD

**Issue by ebadyano** [elastic/rally#1251]
After https://github.com/elastic/elasticsearch/pull/71505 enabled geoip downloader by default, creates an index causing rally to issue warning:
```
[WARNING] indexing_total_time is 99 ms indicating that the cluster is not in a defined clean state. Recorded index time metrics may be misleading.
[WARNING] refresh_total_time is 72 ms indicating that the cluster is not in a defined clean state. Recorded index time metrics may be misleading.

```
 Define a non-configurable threshold (e.g. one second). If the value is below this threshold we suppress this warning.

**Comment by nik9000** [comment]
> Define a non-configurable threshold (e.g. one second). If the value is below this threshold we suppress this warning.

Could we subtract out the stats for the geoip index?

**Comment by danielmitterdorfer** [comment]
> Could we subtract out the stats for the geoip index?

The problem with building specific logic in Rally around how certain features are implemented is that we increase coupling. That can be ok but I sense that the coupling is too tight given the benefit we'd get. The intention behind this warning is to make the user aware that they might have run multiple benchmarks without restarting the cluster and thus results are not reproducible. By implementing a threshold we make this feature more robust against such changes that are rather insignificant for benchmark results.

**Comment by ebadyano** [comment]
There is a change coming: https://github.com/elastic/elasticsearch/pull/72377 to hide .geoip index, I wonder if that will make it that it's not included in the index stats. I might wait for the change to get merged and see before adding a threshold in rally.
