### ISSUE TITLE
Support exiting of parallel block on first completed task

### ISSUE THREAD

**Issue by gingerwizard** [elastic/rally#1261]
The parallel element provides a completed-by property but this only works if the task that should determine the exit condition is known upfront.

The proposal is that that we add a new property e.g. complete-on-first-task-completed. This would cause a parallel block to exit as soon as one task exits.

This is useful when running queries in parallel for example. As soon as one task exits the load reduces overall, invalidating all subsequent executions by other tasks. This would ensure a clean exit.

Note the naming above is a proposal by @danielmitterdorfer only and we're open to suggested better ones.

**Comment by DJRickyB** [comment]
Has a mixed-type `completed-by` been considered?  an `int` for number of tasks to end before marking completed or a `string` for a named task? Having a single parameter vs two that are mutually exclusive makes the natural default behavior (all tasks complete) a little easier to grok, I would think

**Comment by danielmitterdorfer** [comment]
> Has a mixed-type completed-by been considered?

No, but your proposal made me think whether we should allow the special value `any` for `completed-by` with the meaning that whichever task within a parallel block finishes first, completes the entire parallel block.
