### ISSUE TITLE
max_connections value is misleadingly logged prior to being overridden 

### ISSUE THREAD

**Issue by b-deam** [elastic/rally#1278]
**Describe the feature**:
Currently `esrally` logs the output of  the `client_options` parameter at the time an [Elasticsearch client](https://github.com/elastic/rally/blob/master/esrally/client.py#L125) is created, for example:
```
2021-06-07 02:17:11,408 ActorAddr-(T|:62446)/PID:42037 esrally.client INFO Creating ES client connected to [{'host': '127.0.0.1', 'port': 39200}] with options [{'timeout': 180, 'max_connections': 2}]
```

The value displayed above for the `max_connections` is actually misleading. In the above log line, `max_connections` is equal to the number of simulated clients allocated per available core, yet this value is actually overridden later by [`AIOHttpConnection`](https://github.com/elastic/rally/blob/master/esrally/async_connection.py#L171) to a minimum of 256 per Elasticsearch client.
```
maxsize=max(256, kwargs.get("max_connections", 0)),
```

[The documentation is correct](https://esrally.readthedocs.io/en/stable/command_line_reference.html?highlight=max_connection#client-options) in explaining that the `max_connections` value is equal to the number of simulated clients, but _at least_ 256 connections. 

Therefore it is misleading for users to see this value being logged _before_ it is overridden.

**Comment by pquentin** [comment]
@sethmlarson Any idea about the best way to proceed here? Specifically:

 * Is there a public API to get the actual `max_connections`?
 * Is it a good idea altogether to try to expose `max_connections`?
 * If it's a good idea but there's no public API, what is the best private way to get the correct value?

**Comment by sethmlarson** [comment]
Currently there's no way to inspect into the transport, connection pools, and connections themselves, that's something that I'd like to add. Currently there's no public API. There's an issue created here: https://github.com/elastic/elasticsearch-py/issues/1502
