### ISSUE TITLE
Query and Disk Usage Telemetry Devices

### ISSUE THREAD

**Issue by gingerwizard** [elastic/rally#1289]
The [field usage API](https://github.com/elastic/elasticsearch/issues/73944) will provide us a breakdown on the usage of certain fields by queries. We should evaluate whether collecting these statistics using a telemetry device is valuable.

Additionally, the [disk usage index API](https://github.com/elastic/elasticsearch/pull/74051) should be valuable for tracking disk usage by field. It is unlikely we will want this throughout the benchmark, so an operation might be more appropriate.

**Comment by nik9000** [comment]
I might have a look at this one. I really would like disk usage telemetry for something I'm working on right now.

**Comment by nik9000** [comment]
OK! So. I've put together a prototype for field disk usage over in #1428. We were having a discussion about the output format in another channel. Rally usually wants to summarize outputs but my prototype reports the disk usage for each structure that each field in each index. To the screen. It's huge. But it's totally the kind of thing I need it to do when I'm working on field usage. I think it does the important thing for graphing already - it dumps the usage statistics to the reporting repository. We build the graphs based on that.

But the questions is - what should we really do here? When I'm really doing field usage stuff, I want it broken out per field. Not some summary. I'm not 100% sure how I'd summarize anyway. *and* I want to be able to do the `esrally compare` thing and see the change in field usage between tests. Per field. That'd be super useful.

**Comment by jpountz** [comment]
Maybe we can close this issue, I'm unsure how useful field usage would be to Rally since it controls the queries that run.

**Comment by dliappis** [comment]
> Maybe we can close this issue, I'm unsure how useful field usage would be to Rally since it controls the queries that run.

I also agree
