### ISSUE TITLE
Add a check-all Makefile target

### ISSUE THREAD

**Issue by pquentin** [elastic/rally#1297]
As mentioned by @dliappis in https://github.com/elastic/rally/pull/1281#pullrequestreview-695899949, it would be useful to do `make check-all`. It's easy to implement:

```
check-all: lint test it
```

But I don't know where to mention it. For example, we don't mention `it` tests anywhere. (And we probably should, I took some time to understand that those were integration tests.)

Maybe this can be left undocumented, as it is something that only the core team will actually run?

**Comment by dliappis** [comment]
> Maybe this can be left undocumented, as it is something that only the core team will actually run?

We cou

> But I don't know where to mention it. For example, we don't mention `it` tests anywhere. (And we probably should, I took some time to understand that those were integration tests.)

We could mention it in the [contributor's guide](https://github.com/elastic/rally/blob/master/CONTRIBUTING.md#submitting-your-changes). Right now step 1 is `python3 setup.py test` but instead it could be to first format the changes and then ensure all tests pass with `make check-all`.
