### ISSUE TITLE
Add possibility for put-pipeline operation to describe a body as an external JSON file

### ISSUE THREAD

**Issue by 111andre111** [elastic/rally#1301]
As of today the put-pipeline content has to be configured inline
https://esrally.readthedocs.io/en/stable/track.html?highlight=ingest%20pipeline#put-pipeline

However it would extremely helpful to have the put-pipeline as an external JSON file.

Would that be possible?

**Comment by danielmitterdorfer** [comment]
This could be solved via a [Jinja include](https://jinja.palletsprojects.com/en/2.11.x/templates/#include), e.g. (untested):

Create a file `my-pipeline.json`:

```json
{
  "description": "Extracts location information from the client IP.",
  "processors": [
    {
      "geoip": {
        "field": "clientip",
        "properties": [
          "city_name",
          "country_iso_code",
          "country_name",
          "location"
        ]
      }
    }
  ],
  "on_failure": [
    {
      "set": {
        "field": "_index",
        "value": "failed-{{ _index }}"
      }
    }
  ]
}
```

which you could reference in your Rally track with:

```json
{
  "name": "define-ip-geocoder",
  "operation-type": "put-pipeline",
  "id": "ip-geocoder",
  "body": {% include "my-pipeline.json" %}
}
```

Would that work for you?

**Comment by 111andre111** [comment]
Oh, cool. Thank you @danielmitterdorfer I'll check that. Do you have something in mind that I could even make the filename of the pipeline parameterizable, for instance with track-params, so that it could just be controlled from the command line what exact pipeline will be chosen?

**Comment by DJRickyB** [comment]
Tested and working with the following examples:

### my-pipeline.json
```json
{
  "description": "Extracts location information from the client IP.",
  "processors": [
    {
      "geoip": {
        "field": "clientip",
        "properties": [
          "city_name",
          "country_iso_code",
          "country_name",
          "location"
        ]
      }
    }
  ],
  "on_failure": [
    {
      "set": {
        "field": "_index",
        "value": "failed-{{ _index }}"
      }
    }
  ]
}
```

### track.json
```json
{
  "schedule": [
    {
      "name": "define-ip-geocoder",
      "#COMMENT#": {{ otherarg | default("") }},
      "operation" : {
      "operation-type": "put-pipeline",
      "id": "ip-geocoder",
      "body": {% include pipeline_file %}
      }
    }
  ]
}
```

### Command Line
```bash
 esrally race --kill-running-processes --track-path . --distribution-version 7.11.1 --track-params="pipeline_file:my-pipeline.json,otherarg:1234"
```

**Note**: I had to add another argument in the `--track-params` flag here because `rally` does not consume comma-separated params if the string ends in `.json`.  To work around this, one would use different parameter ordering, or use JSON-formatted `track params`
