### ISSUE TITLE
Collect master node during benchmark execution

### ISSUE THREAD

**Issue by b-deam** [elastic/rally#1324]
It'd be handy to be able to regularly sample/collect the current elected master node during the execution of our benchmarks. This would mainly assist in performance analysis by allowing us to observe which node was acting as master throughout the duration of a benchmark.

[The ES client already exposes this via the `Cat` client](https://elasticsearch-py.readthedocs.io/en/v7.14.1/api.html?highlight=master%20node#elasticsearch.client.CatClient.master).

I propose we add either an internal, always on telemetry device to collect this on a regular sample throughout the benchmark. The functionality is similar to that implemented in `ClusterEnvironmentInfo`, however this is a static telemetry device that is only run once at the start of a benchmark.

**Comment by pquentin** [comment]
Since the cat API is designed for human consumption, we're going to use the [nodes info API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html) instead. Is it enough to store the name of the master node, or should we also store its ip and host?

**Comment by b-deam** [comment]
> Since the cat API is designed for human consumption, we're going to use the [nodes info API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html) instead. Is it enough to store the name of the master node, or should we also store its ip and host?

I'm not sure that the nodes info API contains the current master, and instead just shows whether or not that node has been assigned the `master` _role_ (i.e. it _can_ be a master).

If we don't want to use the cat API, then we should fetch it directly from the cluster state [via `ClusterClient.state`](https://elasticsearch-py.readthedocs.io/en/v7.14.1/api.html?highlight=master%20node#elasticsearch.client.ClusterClient.state), e.g. `elasticsearch.client.cluster.master`. This will give you back a node ID that you'll need to use to lookup the actual node _name_.
