### ISSUE TITLE
Rally fails when using 8.0.0 as a metrics store

### ISSUE THREAD

**Issue by pquentin** [elastic/rally#1335]
**Rally version**: master, using the 7.14.0 Python client

**Description of the problem including expected versus actual behavior**:

When using Elasticsearch 8.0.0-alpha1 as a metric store, I get the following error from Rally:

```
esrally.exceptions.RallyError: Error in race control (A transport error occurred while running the operation [put_template] against your Elasticsearch metrics store on host [localhost] at port [9200].)                                                                                                              
```

ES reports this:

```
{
  "@timestamp": "2021-09-16T11:30:17.312Z",
  "log.level": "DEPRECATION",
  "data_stream.dataset": "deprecation.elasticsearch",
  "data_stream.namespace": "default",
  "data_stream.type": "logs",
  "ecs.version": "1.7",
  "elasticsearch.event.category": "api",
  "event.code": "deprecated_route_PUT_/_template/{name}",
  "message": "Legacy index templates are deprecated in favor of composable templates.",
  "service.name": "ES_ECS",
  "process.thread.name": "elasticsearch[b403f8a317e0][transport_worker][T#4]",
  "log.logger": "org.elasticsearch.deprecation.rest.RestController",
  "event.dataset": "deprecation.elasticsearch",
  "elasticsearch.cluster.uuid": "QeCQ-vzJQt2LeuhphpaLaA",
  "elasticsearch.node.id": "HYBcZ8ZxS2uwfTjDPvmqnQ",
  "elasticsearch.node.name": "b403f8a317e0",
  "elasticsearch.cluster.name": "docker-cluster"
}
```

We *do* use a deprecated feature, but it's surprising that we actually fail. To be investigated after #653 which is closely related.

**Steps to reproduce**:
 1. Run 8.0.0: `docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:8.0.0-alpha1`
 2. Configure rally.ini to use this as a metric store
 2. Run any race: `esrally race --distribution-version=7.14.1 --car="4gheap" --track=geonames --test-mode`

**Comment by pquentin** [comment]
I was surprised by the behavior, so I looked at the actual answer from Elasticsearch 8.0.0-alpha2. What happens on the master branch is that we use `include_type_name` to put a typed template, but per https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html this parameter is now ignored.

So the request fails with "The mapping definition cannot be nested under a type [_doc] unless include_type_name is set to true" (which is quite ironic). I haven't managed to find if there's an Elasticsearch issue to track this, otherwise I would be happy to report that the error message is confusing.

As it turns out, #1342 fixes the issue here because we no longer set the `include_type_name` parameter and we no longer use a nested mapping definition. However, we still use legacy templates, so I would still like to work on this to use composable templates when the metrics store is 7.8+.

**Comment by danielmitterdorfer** [comment]
@pquentin I think we can close this issue based on your analysis above as #1342 has been merged now?

**Comment by pquentin** [comment]
Right, when I said that I would still like to support composable templates on 7.8+ clusters, I had basically nothing else to do :)

Closing, we can revisit if/when Elasticsearch drops legacy templates support.
