### ISSUE TITLE
Upgrade Docker base image

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#1339]
We're currently using Python 3.8.2 (and Debian 10) in our base image:

https://github.com/elastic/rally/blob/ec160e002750c0d29d29c7a1e997be98e3871bb0/docker/Dockerfiles/Dockerfile-release#L1

As this version is already dated we should look into upgrading to a newer version (and also use Debian 11).

**Comment by dliappis** [comment]
This is an easy one; I'll pick it up as I was already looking into something else related to the Rally Docker image.
