### ISSUE TITLE
Support data streams in create-track

### ISSUE THREAD

**Issue by michaelbaamonde** [elastic/rally#1360]
The `create-track` command generates tracks from clusters with existing indices specified by the user, but does not support doing so for data streams. This would be a useful enhancement.

**Comment by pquentin** [comment]
@muralidharanvenkataraman stumbled upon this: https://discuss.elastic.co/t/create-track-using-datastreams/289097

**Comment by ruflin** [comment]
Data streams is the way we by now ingest all our time series data for observability and security, especially based on the [data stream naming scheme](https://www.elastic.co/blog/an-introduction-to-the-elastic-data-stream-naming-scheme). We are planning to use rally more on this data so having native support for data streams in rally is important.

**Comment by dliappis** [comment]
@michaelbaamonde FYI AFAIK @gizas is currently hacking Rally to add this functionality so you may wanna sync with him to avoid duplication of effort.

**Comment by michaelbaamonde** [comment]
@gizas Thanks for taking this up! Let me know if you need help. Otherwise, just add me as a reviewer to the PR and I'll be happy to help get it merged.

**Comment by b-deam** [comment]
Closed via https://github.com/elastic/rally/pull/1531
