### ISSUE TITLE
Measure overhead of ingest pipelines

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#1365]
Currently it's not possible to determine the overhead of ingest pipelines in Rally. One option to provide high-level insights is to expose the `ingest_took` metric in summary reports as well as `took`. 

If the bulk operation is configured with `detailed-results` set to `true`, Rally already captures these two metrics for individual bulk requests in `meta.took` and `meta.ingest_took` (see [`BulkIndex#detailed_stats()`](https://github.com/elastic/rally/blob/35de44efdac135730ac0c59258a7082c9fd1d239/esrally/driver/runner.py#L558-L571)) but does not aggregate these when calculating summary statistics (see [`GlobalStatsCalculator`](https://github.com/elastic/rally/blob/35de44efdac135730ac0c59258a7082c9fd1d239/esrally/metrics.py#L1750-L1760)). Adding them there as well would allow us to visualize the overhead of ingest pipeline with charts such as this one (for the logging track in our nightly benchmarks):

<img width="939" alt="ingest pipeline breakdown" src="https://user-images.githubusercontent.com/1699576/137482004-97eed800-7bc8-4c56-9eb1-82df58302ab8.png">

IMHO it's not necessary that these data also show up in the command line report but we should be able to create summary charts based on aggregated metrics.

**Comment by b-deam** [comment]
Alternative approach here is to implement a specific Ingest Pipeline/processor stats telemetry device, as per processor, per pipeline stats are available through the node stats API. 

This gives us a much clearer idea of _exactly_ where time is being spent per pipeline than the high level `ingest_took`.

Example:
```
GET _nodes/stats
{
  "_nodes" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "cluster_name" : "docker-cluster",
  "nodes" : {
      [...]
      "ingest" : {
        "total" : {
          "count" : 0,
          "time_in_millis" : 0,
          "current" : 0,
          "failed" : 0
        },
        "pipelines" : {
          "logs-system.syslog-1.6.4" : {
            "count" : 0,
            "time_in_millis" : 0,
            "current" : 0,
            "failed" : 0,
            "processors" : [
              {
                "grok" : {
                  "type" : "grok",
                  "stats" : {
                    "count" : 0,
                    "time_in_millis" : 0,
                    "current" : 0,
                    "failed" : 0
                  }
                }
              },
              {
                "remove" : {
                  "type" : "remove",
                  "stats" : {
                    "count" : 0,
                    "time_in_millis" : 0,
                    "current" : 0,
                    "failed" : 0
                  }
                }
              },
              {
                "rename" : {
                  "type" : "rename",
                  "stats" : {
                    "count" : 0,
                    "time_in_millis" : 0,
                    "current" : 0,
                    "failed" : 0
                  }
                }
              },
              {
                "compound:CompoundProcessor-null-null" : {
                  "type" : "conditional",
                  "stats" : {
                    "count" : 0,
                    "time_in_millis" : 0,
                    "current" : 0,
                    "failed" : 0
                  }
                }
              },
              {
                "compound:CompoundProcessor-null-null" : {
                  "type" : "conditional",
                  "stats" : {
                    "count" : 0,
                    "time_in_millis" : 0,
                    "current" : 0,
                    "failed" : 0
                  }
                }
              },
              {
                "remove" : {
                  "type" : "remove",
                  "stats" : {
                    "count" : 0,
                    "time_in_millis" : 0,
                    "current" : 0,
                    "failed" : 0
                  }
                }
              }
              [...]
            ]
          }
        }
      }
      [...]
    }
  }
}


```
