### ISSUE TITLE
Add more term / phrase queries to balance retrieval load.

### ISSUE THREAD

**Issue by vsop-479** [elastic/rally#1375]
It seems that rally requests same term query with constant condition (body = physician in pmc) every time.
If it is true, every query retrievals same docs, it will make the shard which fetch more docs get more load.
So, it would be nice to add more term queries, or use variable query condition.

**Comment by dliappis** [comment]
This is a duplicate of https://github.com/elastic/rally-tracks/issues/209, so if you don't mind I'll close this one.
