### ISSUE TITLE
Improve support Elasticsearch 5 as metrics store

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#138]
While Rally's mapping for the metrics store currently works also with ES 5 due to backwards compatibility features (`string` / `not_analyzed` is automatically converted to `keyword`), we should natively support it as this feature in ES will likely be removed at some point.

**Comment by jpountz** [comment]
I'm curious which API break is responsible for the fact that it does not work with 5.0?

**Comment by danielmitterdorfer** [comment]
@jpountz I worried about the use of `string`/ `not_analyzed` instead of `keyword`. I've just tried it with ES 5.0 alpha3 and it works due to a fallback that auto-converts these fields automatically to `keyword`. So I'll relabel it as an enhancement because this auto-conversion will be removed at some point in ES.

**Comment by jpountz** [comment]
Thanks! The auto conversion should be removed in 6.0 indeed.

**Comment by danielmitterdorfer** [comment]
As we'll change the metrics store structure in #279 anyway and Elasticsearch 5.0 is now out for quite some time, we should target this for the next release.
