### ISSUE TITLE
Custom parameter sources do not honor detailed-results

### ISSUE THREAD

**Issue by pquentin** [elastic/rally#1390]
This was reported by kingswan on Discuss: https://discuss.elastic.co/t/how-to-config-esrally-metric-store-so-that-meta-of-rally-metrics-can-record-took-of-each-query/290024/3. I was able to reproduce it with Rally master.

**Description of the problem including expected versus actual behavior**: When using a customer parameter source, `detailed-results` does not have any effect: metrics don't include `took` as expected.

**Steps to reproduce**:
 1. Use `detailed-results` on a normal `search` operation type, see that `took` is logged in metrics.
 2. Switch to a custom parameter source, notice that `took` isn't logged any more

**Comment by kingswanwho** [comment]
Hi Quentin, I am the issue reporter, is there any way that I can help with the issue fix.

**Comment by danielmitterdorfer** [comment]
> Switch to a custom parameter source, notice that took isn't logged any more

It's not clear to me whether that custom parameter source explicitly passes `detailed_results` to the runner? If that's not the case, the query runner will set `detailed_results` to `False`:

https://github.com/elastic/rally/blob/57475be8c2f134c3ae5889752f5708369877df9d/esrally/driver/runner.py#L824

Later on, the runner checks this flag to decide whether to retrieve detailed statistics:

https://github.com/elastic/rally/blob/57475be8c2f134c3ae5889752f5708369877df9d/esrally/driver/runner.py#L888

So it's worth checking that the parameter source implementation *explicitly* sets this parameter (it won't be passed implicitly, even if it is defined in the track JSON file).

**Comment by pquentin** [comment]
Right, when we set `detailed-results` to `True` in track.py, then that works correctly. That's surprising, probably because I don't understand custom parameter sources well.
