### ISSUE TITLE
Document that OSS Elasticsearch clusters aren't supported out of the box

### ISSUE THREAD

**Issue by pquentin** [elastic/rally#1408]
Since we use the 7.14.0 Elasticsearch Python client, it will refuse by default to connect to OSS clusters. But we do support Elasticsearch 6.0.0 and above, so we should either:

 * document that we don't support the OSS releases in https://esrally.readthedocs.io/en/stable/versions.html
 * or support the OSS releases by setting `es.transport._verified_elasticsearch` to `True`

**Comment by karan-kaushik** [comment]
Hey @pquentin 
Please have a look at https://github.com/elastic/rally/pull/1414 for the documentation edit requested.
