### ISSUE TITLE
Ability to specify ingest node pipeline

### ISSUE THREAD

**Issue by eskibars** [elastic/rally#142]
**Describe the feature**:
Elasticsearch 5.0+ supports adding an [ingest processor](https://www.elastic.co/guide/en/elasticsearch/reference/master/pipeline.html).  It would be neat if Rally could support adding the `pipeline=foo` parameter as part of its indexing parameters, ala `PUT my-index/my-type/my-id?pipeline=my_pipeline_id`

**Comment by danielmitterdorfer** [comment]
Rally 0.4.3 will support a new parameter `pipeline` for the index operation in a track. This will only work if users define the pipeline before-hand, i.e. Rally is currently not able to setup an ingest node pipeline (but #105 will help with that).
