### ISSUE TITLE
Should we force Rally to clean up SSL connections?

### ISSUE THREAD

**Issue by b-deam** [elastic/rally#1466]
During some recent benchmarking work we discovered [that a bug in how Elasticsearch handles the closing of existing SSL connections when TLS 1.3 is used](https://github.com/elastic/elasticsearch/issues/76642) can end up manifesting itself as a memory leak in Rally, and given enough time will eventually cause the benchmark to fail as the host machine memory utilisation grows to 100% and the OOMKiller is invoked. 

An example of this can be seen in the below screenshot:
![image](https://user-images.githubusercontent.com/54515790/159850699-913f2de1-463e-4413-a94c-74d5c7b022bb.png)

The bug isn't yet fixed in Elasticsearch, and may not be for a while. Luckily for us the workaround for this is very simple. [All that is needed is to set the client opt `enable_cleanup_closed: true`](https://esrally.readthedocs.io/en/stable/command_line_reference.html#client-options). 

So, given how simple this fix is, should we consider changing our current default of `false` to `true`? 
https://github.com/elastic/rally/blob/45e43e2d7165712e9e497a9beb3f65e429a7d23c/esrally/async_connection.py#L209 

Acknowledging both the fact that environments that do leak connections will almost definitely see an increase in performance, and that we haven't got any baseline for environments that do not currently suffer from this issue. Whether an environment is affected or not depends both on the version of Elasticsearch and whether or not TLS 1.3 is in use.

Discuss.

**Comment by pquentin** [comment]
(We do need to understand why we're not reusing connections, but that can be a separate issue.)

**Comment by pquentin** [comment]
This was also fixed in elasticsearch-py 7.17: https://github.com/elastic/elasticsearch-py/issues/1910. But simply upgrading to 7.17 would not be enough as we override `AIOHTTPConnection._create_aiohttp_session`.
