### ISSUE TITLE
Add refresh operation-type to chart generator

### ISSUE THREAD

**Issue by DJRickyB** [elastic/rally#1511]
Chart should be generated per track and display a single line/area per task, each representing the whole duration of the task

cc @mayya-sharipova

**Comment by ebadyano** [comment]
@DJRickyB should we close this, as we agreed to drop chart generator?

**Comment by DJRickyB** [comment]
Yes, good catch. In fact the refresh time chart is up on the public dashboards already :) https://elasticsearch-benchmarks.elastic.co/#tracks/dense_vector/nightly/default/30d
