### ISSUE TITLE
Allow Rally to handle master -> main migration of Elasticsearch repo

### ISSUE THREAD

**Issue by pquentin** [elastic/rally#1528]
Elasticsearch is moving to main (https://github.com/elastic/elasticsearch/issues/76950) and even has plans to remove the master branch. How can we handle this transition in Rally?

Most of it is documentation/comments:
  * README.rst "always adapts accordingly to the latest master version"
  * docs/developing.rst: change "build setup requirements" URL to master (even if GitHub will redirect)
  * docs/car.rst: The master branch of team repos needs to work with the **main** branch of Elasticsearch
  * docs/track.rst: The master branch needs to work with the latest **main** branch of Elasticsearch (and various mentions of master below - :warning: this file also mentions the master branch of the track repos, this should stay)
  * docs/elasticsearch_plugin.rst: By default Rally assumes that you want to benchmark the latest **main** version of Elasticsearch.
  * docs/command_line_reference.rst: --revision=latest: use the HEAD revision of from origin/main
  * esrally/racecontrol:BenchmarkCoordinator.setup: change master to main (or latest?)
  * esrally/rally.py: in `install_parser` change master to main (or latest?)
  * esrally/track/loader: in `tracks` docstring change master to main (or latest?)

But there are changes to code too.
 * esrally/mechanic/supplier: SourceRepository should call `git.pull` and `git.pull_ts` with `branch="main"` for Elasticsearch but not plugins
 * if we have an existing clean checkout, we convert it to main

Teams/tracks don't need to change, we'll move to main eventually but it's out of scope here.

Open questions:
 * Should we assume that all plugins use the main branch too? The only one I'm aware of that has not moved: https://github.com/BigDataBoutique/elasticsearch-repository-swift. If no, then SourceRepository needs to know the default branch. Should it be configured? I'm not sure how much effort we should put into plugins given the official ones got integrated in Elasticsearch itself.
 * How do we handle existing checkouts? "if the branch is master and clean, then git fetch origin and git checkout main"?

**Comment by dliappis** [comment]
@pquentin I'd also take a look at the steps related to Rally releases (some of which don't live in this repo though, but are related to Rally nonetheless).

**Comment by pquentin** [comment]
Thanks! I checked but don't think there is anything to do here as Rally will continue using the master branch for now.

**Comment by mark-vieira** [comment]
In case it's not clear it's worth pointing out that changes to point at `main` can be done now at any time. The `main` branch exists and is continually kept in since with `master` so working off of `main` or `master` for the elasticsearch repo is functionally equivalent unless any part of your automation actually _commits_ to the repo but I suspect that is not the case.

**Comment by mark-vieira** [comment]
> @mark-vieira The main question left is Elasticsearch plugins that live in their own git repos. We currently assume that they use the master branch. Should we continue doing that or should we assume `main` from now on? Do we even have official plugins that are in their own repos now? Your thoughts would be much appreciated here.

Which plugins are these? For now we are only changing the `elastic/elasticsearch` repo.

**Comment by pquentin** [comment]
For what it's worth another popular plugin uses the master branch: https://github.com/alexklibisz/elastiknn

**Comment by pquentin** [comment]
Yes, all the other repos are already migrated, they only needed doc changes.

However, if this breaks our nightly benchmarks we'll have to revert. They run at 6PM UTC, so let's wait until tomorrow to be sure.
