### ISSUE TITLE
bulk opertaion not able to insert parent child track document

### ISSUE THREAD

**Issue by yogiprogram** [elastic/rally#1592]
When bulk operation happing on parent child document. parent id as routenot set .

	Cannot run task [bulk]: Request returned an error. Error type: transport, Description: null_pointer_exception ({'error': {'root_cause': [{'type': 'null_pointer_exception', 'reason': 'id must not be null'}], 'type': 'null_pointer_exception', 'reason': 'id must not be null'}, 'status': 500})

**Comment by DJRickyB** [comment]
Hi!

Thanks for reporting. Can you please provide an example track and corpora file for this issue?

**Comment by ebadyano** [comment]
closing this as there hasn't been response in a while. @yogiprogram please re-open if you have example.
