### ISSUE TITLE
Return both exit code, and output in process module

### ISSUE THREAD

**Issue by b-deam** [elastic/rally#1595]
In https://github.com/elastic/rally/pull/1591 it became clear that it'd be nice to modify an existing function in our [`process` module](https://github.com/elastic/rally/blob/master/esrally/utils/process.py) to return both the stdout/stderr of the subprocess as well as the exit code.

**Comment by pquentin** [comment]
Thanks for this issue. I would like to avoid just adding one more method, we can likely change `run_subprocess` to do that, maybe by returning a tuple or a `subprocess.CompletedProcess`.
