### ISSUE TITLE
Add delay and duration parameters for the JFR telemetry device

### ISSUE THREAD

**Issue by dliappis** [elastic/rally#1617]
The [JFR telemetry device](https://esrally.readthedocs.io/en/stable/telemetry.html#jfr) while very useful, currently, only captures flight recordings from the time that ES starts until it's been stopped. This makes it hard to grab more focused JFRs for specific tasks, e.g. the [scroll task](https://github.com/elastic/rally-tracks/blob/c86b3ad1e6fe831ff3cc61e0bca2b5134b16319d/http_logs/challenges/common/default-schedule.json#L145-L150) in `http_logs`.

The current workaround is to leverage [include|exclude tasks](https://esrally.readthedocs.io/en/stable/command_line_reference.html?highlight=include-tasks#include-tasks) to reduce the amount of operations but often it's not an option as indexing usually needs to take place anyway and also skipping preceding tasks tends to affect reproducability.

Until we get a way to coordinate tasks and telemetry device execution in Rally, a short-term improvement could be allowing to pass the `delay` and `duration` parameters to `jcmd`, as per the official [jcmd docs](https://docs.oracle.com/en/java/javase/19/docs/specs/man/jcmd.html) for `JFR.start`. Currently we only support one parameter (`recording-template`) for the `jfr` telemetry device, and adding those two should be a straightforward task.

**Comment by debanjanc01** [comment]
Hey @dliappis, if this issue is up for grabs then I'd like to take it up.

**Comment by dliappis** [comment]
@debanjanc01 sure go for it.

**Comment by debanjanc01** [comment]
Thanks @dliappis ! Could you please assign this to me?

**Comment by dliappis** [comment]
> Thanks @dliappis ! Could you please assign this to me?

Done

**Comment by debanjanc01** [comment]
@dliappis I've raise the PR for this.
