### ISSUE TITLE
Improve logging and probing for cluster health

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#164]
With Elasticsearch 5.0, the parameter `wait_for_relocating_shards` was removed and clients have to specify `wait_for_no_relocating_shards` instead. Rally assumes the pre 5.0 API by default and contains also some potentially scary logging (see e.g. https://github.com/elastic/elasticsearch/issues/20855#issuecomment-252933506)

We should use the 5.0 API by default and use the previous API as fallback. We should also just log on `INFO` level instead of `WARN` or `ERROR` because this is really an expected condition.

**Comment by bleskes** [comment]
does it make more sense to pre quest `GET /` and get the ES version and avoid guessing?

**Comment by danielmitterdorfer** [comment]
Rally does this already in certain cases. The problem is that we need to be able to benchmark any git revision so I cannot rely on the ES version as Rally would then just not work at all for certain git revisions of Elasticsearch and have resorted to probing in this case. 

However, as time moves on, it will not be important to be able to benchmark the git revisions in the range where this change has happened and then I'd remove the probing code and rely on version detection in this case. Makes sense?

**Comment by bleskes** [comment]
> Makes sense?

Yep. Thx.
