### ISSUE TITLE
Handle errors in git -C more gracefully

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#166]
`-C` is a handy git option for Rally but from time to time people have an older version of git installed and run into errors that we can avoid by not relying on it. We should implement it in a more compatible way (either get rid of it, show a better error message, etc. etc.)

**Comment by jasontedor** [comment]
I'm not sure, those are some very outdated versions of git that do not [support](https://github.com/git/git/commit/44e1e4d67d5148c245db362cc48c3cc6c2ec82ca) `-C`. I think a friendlier error message is all that's needed?

**Comment by danielmitterdorfer** [comment]
@jasontedor Well, that's a good point. I'll think about the issue tomorrow. :)

**Comment by danielmitterdorfer** [comment]
I've decided that an error message is the best solution. Rally will show `Your git version is [$GIT_VERSION] but Rally requires at least git 1.9. Please update git.` in case you invoke Rally with an outdated git version.
