### ISSUE TITLE
Allow .ini definable in environment variable or pass as command line runtime value instead of persisting it in .ini file

### ISSUE THREAD

**Issue by hp0620** [elastic/rally#1670]
**Describe the feature**:

Currently, metrics store password has to be defined in the `.ini` file. This is fine, but some users would prefer not to persist the password in the .ini file, so either allowing the password to be configured as an environment variable or allowing it to be passed as a runtime flag would be helpful in this use case scenario. 

The workaround for now is to move the .ini file in the `/dev/shm` directory and symlink it to avoid persisting the value in the disk.  

Thank you for the consideration!

**Comment by pquentin** [comment]
Hello @hp0620, thanks for sending this feature request! I'd be happy to accept a pull request that adds environment variable support for the metrics store password.
