### ISSUE TITLE
Move 'body' parameters to new typed parameters

### ISSUE THREAD

**Issue by b-deam** [elastic/rally#1672]
As part of [the ES client upgrade to 8.x](https://github.com/elastic/rally/pull/1669), all client method's [now expose the JSON 
body' field as typed parameters,](https://github.com/elastic/elasticsearch-py/issues/1680), and the use of the `body` parameter is deprecated.

For example:
```python
client.search(
    index="test-index",
    size=10,
    body={
        "runtime_mappings": {
            "day_of_week": {
                "type": "keyword",
                "script": "emit(doc['@timestamp'].value.dayOfWeekEnum)"
            }
        },
        "aggs": {
            "day_of_week_count": {
                "value_count": {
                    "field": "day_of_week"
                }
            }
        }
    }
)
``` 

Would become:
```python
client.search(
    index="test-index",
    size=10,
    runtime_mappings={
        "day_of_week": {
            "type": "keyword",
            "script": "emit(doc['@timestamp'].value.dayOfWeekEnum)"
        }
    },
    aggs={
        "day_of_week_count": {
            "value_count": {
                "field": "day_of_week"
            }
        }
    }
)
```

We need to refactor all of our runners (and [custom runners in rally-tracks](https://github.com/elastic/rally-tracks)) to use these new parameters.

**Comment by pquentin** [comment]
Another option here is to use `**body` instead of `body`.

**Comment by b-deam** [comment]
[Looks like a decision was made](https://github.com/elastic/elasticsearch-py/issues/2181#issuecomment-1490932964) to un-deprecate the removal of the `body` param. 

Closing this one out for now.
