### ISSUE TITLE
Cluster health check should handle HTTP 408 in version detection

### ISSUE THREAD

**Issue by jaymode** [elastic/rally#168]
It looks like Rally tries to do some version checking based on the error code/response received back from the cluster health check. However, if the cluster health check times out waiting for green/no relocating shards, a HTTP 408 response code is returned, which trips this [check](https://github.com/elastic/rally/blob/master/esrally/driver.py#L482) that then switches to use the older version of the cluster health check, which will fail against a 5.0+ version.

I worked around this by changing the line to:

```
if 400 <= e.status_code < 500 and 408 != e.status_code:
```

Maybe we should just check for the exact response code, which I believe is `400`, and then do the fallback?

**Comment by danielmitterdorfer** [comment]
Thanks for the report. I'll check!

**Comment by danielmitterdorfer** [comment]
I've now removed the fallback logic entirely and do a proper version check. Versions up to and including Elasticsearch 5.0.0-alpha5 use the old cluster health check API (i.e. `wait_for_relocating_shards=0`), newer versions use `wait_for_no_relocating_shards=true`. This means that the detection will not work for some source code revisions between alpha5 and beta1 which I think is ok.
