### ISSUE TITLE
Detect when benchmark candidate fails with OutOfMemoryError

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#169]
At the moment, Rally cannot detect when the benchmark candidate fails with an OutOfMemoryError and just hangs. We should at a best-effort detection for these cases and terminate early.

**Comment by danielmitterdorfer** [comment]
When the benchmark candidate encounters an `OutOfMemoryError` Rally aborts and shows:

```
ERROR: Cannot race

Reason: ('Error in load generator [0]', ConnectionError('N/A', '<urllib3.connection.HTTPConnection object at 0x10f323390>: Failed to establish a new connection: [Errno 61] Connection refused', NewConnectionError('None: None',)))
```

In the logs we'll see:

```
2016-10-17 11:56:00,887 rally.launcher INFO rally-node0: java.lang.OutOfMemoryError: Java heap space
2016-10-17 11:56:00,888 rally.launcher INFO rally-node0: Dumping heap to java_pid13397.hprof ...
2016-10-17 11:56:03,470 rally.launcher INFO rally-node0: Heap dump file created [1050300418 bytes in 2.582 secs]
2016-10-17 11:56:03,470 rally.launcher INFO rally-node0: Terminating due to java.lang.OutOfMemoryError: Java heap space
```

Although we are not (yet) able to show a specific error message when this happens, we can detect this condition reliably and have at least a hint in the logs.

Test case: `esrally --pipeline=from-distribution --distribution-version=1.7.5 --track=geopoint --challenge=append-no-conflicts`

**Comment by jasontedor** [comment]
Since elastic/elasticsearch#19272, Elasticsearch will exit with error code 127 when an `OutOfMemoryError` occurs.

**Comment by danielmitterdorfer** [comment]
Thanks, good to know! I think it makes sense to check the ES exit code but for older versions of Elasticsearch we still need to rely on this flag to detect OOME conditions.
