### ISSUE TITLE
Configurable timezone for Rally logging

### ISSUE THREAD

**Issue by dliappis** [elastic/rally#1694]
As discussed in https://discuss.elastic.co/t/how-to-set-other-time-zone-in-rallys-log/328683/2, right now the out of the box [logging.json](https://github.com/elastic/rally/blob/71688bcf5175cd1330481e8021f51d9c525785e1/esrally/resources/logging.json#L7) uses a [UTC formatter](https://github.com/elastic/rally/blob/71688bcf5175cd1330481e8021f51d9c525785e1/esrally/log.py#L29-L36) without a possibility to change it.

We could support configuring the timezone in a user friendly manner e.g. via an additional `timezone` property. A primitive, insecure and naive implementation could be as simple as:

```diff
$ git diff
diff --git a/esrally/log.py b/esrally/log.py
index 189a1b8..9423b1a 100644
--- a/esrally/log.py
+++ b/esrally/log.py
@@ -32,7 +32,10 @@ def configure_utc_formatter(*args, **kwargs):
     timestamps across all deployments regardless of machine settings.
     """
     formatter = logging.Formatter(fmt=kwargs["format"], datefmt=kwargs["datefmt"])
-    formatter.converter = time.gmtime
+    if user_tz := kwargs.get("timezone"):
+        formatter.converter = getattr(time, user_tz)
+    else:
+        formatter.converter = time.gmtime
     return formatter
 ```

which would allow changing the logging config file to e.g.:

```diff
diff --git a/esrally/resources/logging.json b/esrally/resources/logging.json
index ba559e2..91cca4c 100644
--- a/esrally/resources/logging.json
+++ b/esrally/resources/logging.json
@@ -4,6 +4,7 @@
     "normal": {
       "format": "%(asctime)s,%(msecs)d %(actorAddress)s/PID:%(process)d %(name)s %(levelname)s %(message)s",
       "datefmt": "%Y-%m-%d %H:%M:%S",
+      "timezone": "localtime",
       "()": "esrally.log.configure_utc_formatter"
     },
     "profile": {
```

**Comment by dliappis** [comment]
Thank you @vaibhavsolanki1193 I've assigned it to you.

**Comment by kimchidonut0** [comment]
Hey there, is this issue still open?

**Comment by b-deam** [comment]
Thanks for your interest in Rally and for asking. https://github.com/elastic/rally/pull/1727 should've closed this out, but it was obviously missed. 

There are [plenty of other issues labeled with `good first issue`](https://github.com/elastic/rally/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) that you can take a look at if you're interested in contributing.
