### ISSUE TITLE
`make prereq` is failing while setting up development environment

### ISSUE THREAD

**Issue by vaibhavsolanki1193** [elastic/rally#1700]
**Rally version** (get with `esrally --version`): 2.7.1

**Invoked command**: `make prereq`

**Configuration file (located in `~/.rally/rally.ini`))**:

**JVM version**: 

**OS version**: 

**Description of the problem including expected versus actual behavior**: Should install all the python version mentioned in `.ci/variables.json` however failing with this error:
```
pyenv install --skip-existing null
python-build: definition not found: null
```

Possibly because of a tag error for 3.11.2

**Steps to reproduce**:
 1. Run `make prereq`

**Provide logs (if relevant)**:

**Describe the feature**:

** comments**
After Typo fix 
```python
diff --git a/.ci/variables.json b/.ci/variables.json
--- a/.ci/variables.json
+++ b/.ci/variables.json
@@ -9,7 +9,7 @@
     "PY38": "3.8.16",
     "PY39": "3.9.16",
     "PY310": "3.10.10",
-    "PY310": "3.11.2",
+    "PY311": "3.11.2",
     "MIN_PY_VER": "3.8.13"
   }
 }
 ```
 The command might still fail with error 
 ```
 rm: .pyenv/shims/shims: is a directory
 make: *** [prereq] Error 1
 ```
 If it fails further, please take a look. Thanks for all your work!!!

**Comment by pquentin** [comment]
Good catch, thanks! Can you please submit your fix as a pull request?

The other error is a pyenv error, I can't help with that unfortunately. What command is trying to run rm? Are you sure pyenv is installed correctly? Have you tried... removing .pyenv and trying again?
