### ISSUE TITLE
Installing Rally develop mode blocked by transitive dependency

### ISSUE THREAD

**Issue by maxhniebergall** [elastic/rally#1751]
**Rally version** (get with `esrally --version`):
esrally 2.8.1.dev0 (git revision: 7d913f7c9e4ec6bc039fee22ee1b91a662fbcd75)

**Invoked command**:
`make install`
**Configuration file (located in `~/.rally/rally.ini`))**:

**JVM version**:
java version "17.0.7" 2023-04-18 LTS
**OS version**:
macOS 13.4.1 (c) (22F770820d)

**Description of the problem including expected versus actual behavior**:
Rather than install correctly, when executing `make install`, pip is getting blocked by this issue (https://github.com/yaml/pyyaml/issues/601) in pyyaml. This appears to be caused by the release of Cython 3.0 which happened today, and which fails to build pyyaml. Pyyaml has two open pull requests (https://github.com/yaml/pyyaml/pull/602, https://github.com/yaml/pyyaml/pull/702) for this issue. 

A maintainer has just stated that they will be releasing the fix in issue 702 [imminently](https://github.com/yaml/pyyaml/pull/702#issuecomment-1638914670). 

**Steps to reproduce**:
 1. make install
 2.
 3.

**Provide logs (if relevant)**:

**Comment by gbanasiak** [comment]
Thank you for reporting.

Has recent PyYML `6.0.1` release addressed this issue for you?

I've failed to reproduce this problem using documented dev [installation steps](https://esrally.readthedocs.io/en/stable/developing.html#installation-instructions-for-development), also with the previous PyYML `6.0.0`. However, pip downloads PyYML binary packages in Wheel format for me. PyYML source build as reported in https://github.com/yaml/pyyaml/issues/601 does not occur. I'm wondering if you're using custom installation steps or different processor architecture (ARM)?
