### ISSUE TITLE
Report additional metdata from runners

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#179]
Currently we only return a weight and unit from each runner. We should return more data:

* HTTP response code (consequence: we won't abort on bulk errors anymore (see #181); maybe revisit later and let the user decide)
* runner-specific metadata, e.g.:
    * for searches: number of search results
    * for bulk requests: number of successful, failed items

**Comment by cdahlqvist** [comment]
It would be great if it was possible to pass through a dictionary with custom parameters from custom parameter sources to the runner and have this be part of the detailed results.
