### ISSUE TITLE
Specifying exclude.tasks as json string yields unexpected behaviour

### ISSUE THREAD

**Issue by martijnvg** [elastic/rally#1809]
Specifying `"exclude.tasks": "compression-stats"` doesn't exclude the `compression-stats` task. Only when specifying it as: `"exclude.tasks": ["compression-stats"],` the `compression-stats` task gets excluded.

I would expect that the former notation would also work?

**Comment by gbanasiak** [comment]
Rally command-line option is documented [here](https://esrally.readthedocs.io/en/stable/command_line_reference.html#exclude-tasks). It would be `--exclude-tasks="compression-stats"`.

The `"exclude.tasks": ["compression-stats"]` invocation applies to internal tool which uses JSON format.
