### ISSUE TITLE
Modify bulk load runner to gracefully handle failures

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/rally#181]
When pushing a cluster hard during a long running benchmark, it is not uncommon to occasionally get errors for either full bulk requests (429 responses due to overload) or individual events. At the moment it seems like the bulk request runner treats all of these as fatal errors and terminates, which is not always desirable. It would be great it the bulk runner could be configured to report various types of errors and just continue processing instead.

Maybe this should extend also to other types of runners?

**Comment by danielmitterdorfer** [comment]
> Maybe this should extend also to other types of runners?

Yes, indeed. I will take care of adapting all existing runners in core so that they don't abort the benchmark anymore.

**Comment by danielmitterdorfer** [comment]
The bulk runner has been modified so it does not actively throw an exception when bulk errors occur (but instead adds them as meta-info). Also, we will just store any failures from Elasticsearch in a meta-data field instead of aborting the benchmark.
