### ISSUE TITLE
Create standard Kibana dashboard runner

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/rally#182]
When using Rally to benchmark and simulate realistic cluster load, having the ability to simulate the execution of full Kibana dashboards in addition to various other types of queries will be important.

While a custom parameter source can be created to generate the _msearch requests issued by Kibana, each request typically also needs to deal with expanding index patterns using the field stats API the same way as Kibana does in order to provide a realistic result.

As this behaviour is somewhat different from other query types in that it has the potential to involve more than one request, it should ideally be supported by a dedicated runner.

**Comment by danielmitterdorfer** [comment]
I need to think a bit how to best integrate it into Rally. Preliminary targeting 0.4.5 for this although it might slip to a later one. As a workaround, it should always be possible to write this as a custom track-specific runner.

**Comment by cdahlqvist** [comment]
I will have a look at this one and see if I can contribute it as a pull request.

**Comment by danielmitterdorfer** [comment]
I thought about this operation type over the weekend. At the moment, we only provide basic operations where one Rally operation correspond exactly to one Elasticsearch API call. This seems to introduce a new concept and I am not quite sure how to model it. To me it seems that there are no drawbacks if we keep this operation out of Rally itself, implement it for the track where we need it and keep it on track level. As we gain more experience, we can move it to Rally. What do you think about this approach?

**Comment by cdahlqvist** [comment]
Although I think it would be a very useful standard runner, I think it makes sense to experiment with it as a track-specific runner for now.

**Comment by danielmitterdorfer** [comment]
Ok, then let's gather some experience outside of the core Rally codebase with it and then we'll see how we best represent this concept. I'm moving the ticket to the backlog for now.

**Comment by danielmitterdorfer** [comment]
Closing for now. We will reopen it when necessary.
