### ISSUE TITLE
Adding custom parameters at the Race level

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/rally#183]
When running large number of benchmarks that are related, it would be very useful to be able to specify custom parameters at the Race level that gets included in all metrics document. This could be either through configuration files or maybe even through command line parameters when starting the race. This will greatly enhance the ability to group results in Kibana and Timelion during analysis in a custom way, which will make analysis of complex benchmark sets a lot easier.

**Comment by danielmitterdorfer** [comment]
We currently have a limited way of expressing that with `--user-tag` (although it gets attached to the `race` record, not to each `metrics` record for this race). I'd like to keep the `--user-tag` feature in mind and evolve it into something more flexible. Targeting 0.4.6, maybe 0.4.5 is possible.

**Comment by cdahlqvist** [comment]
Having a list of tags make it difficult to aggregate on it in Kibana, so the ability specify multiple separate fields would be much better.

**Comment by danielmitterdorfer** [comment]
Sure, I got that. It was more of a reminder for me so the `--user-tag` feature is not forgotten.

**Comment by cdahlqvist** [comment]
No idea how I ended up closing it...

**Comment by danielmitterdorfer** [comment]
The following elements in the track structure will allow to define a `meta` object:

1. track
2. operation
3. challenge
4. task

Properties with the same key in different sub-structures will be overridden (higher number wins). Consider this example:

```json
{
    "meta": {
        "foo": 1,
        "bar": "baz"
    },
    "operations": [
        {
            "name": "bulk-index",
            "operation-type": "index",
            "meta": {
                "foo": 1
            }
        }
    ]
}
```

The resulting meta data for bulk-index samples is `"foo"=5, "bar"="baz"`. The former key is overridden by the operation meta-data, the latter key is copied from the track meta-data.

Note: As tracks currently allow a `meta` element for defining the elements `description`, `short-description` and `data-url`, we will move these elements to the top-level of a track and deprecate the current syntax.
