### ISSUE TITLE
Loosen some constraints on indices in track specification

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#188]
Currently Rally assumes it needs to populate data in an index from a data file. Since the introduction of custom parameter sources (see #107) this assumption is not correct anymore and it is awkward to have users specify properties such as URLs.

**Comment by cdahlqvist** [comment]
I did hit this with my track that generated data and does not load it from file. Is there any workaround?

**Comment by danielmitterdorfer** [comment]
@cdahlqvist I don't know the exact error you're hitting but for this problem there are two workarounds:

1. Fill in the required fields with bogus data OR
2. Use the master version of Rally (see [docs](http://esrally.readthedocs.io/en/latest/developing.html#installation-instructions-for-development)) as I've fixed the issue on master already.
