### ISSUE TITLE
Enable users to manage indices manually

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#189]
Rally assumes complete control over the indices in a track (i.e. it can destroy them at will). Sometimes, especially for search-only benchmarks on huge indices, it does not make sense to populate the index from scratch all the time. Hence, we should allow users to override the behavior of Rally.

Note: This is a feature for advanced users and Rally will *not* do any sanity checks and assume that users know what they're doing.

Solution: Add a new boolean property `auto-managed` with the default value `true` on an index. Example snippet:

```json
  "indices": [
    {
      "name": "pmc",
      "auto-managed": false,
      "types": [
        {
          "name": "articles",
          "documents": "documents.json.bz2",
          "document-count": 574199,
          "compressed-bytes": 5928712141,
          "uncompressed-bytes": 23256051757
        }
      ]
    }
  ]
```

**Comment by cdahlqvist** [comment]
If 'auto-managed' is set to false, which may indicate that no data is to be loaded, are all the parameters provided in the example above really required? What does a minimal config for test against an existing index/set of indices look like?

**Comment by danielmitterdorfer** [comment]
This should be the minimum that's currently needed:

```json
  "indices": [
    {
      "name": "pmc",
      "auto-managed": false,
      "types": [ ]
    }
  ]
```

**Comment by danielmitterdorfer** [comment]
@cdahlqvist: I've pushed another commit on master that simplifies this case to:

```json
  "indices": [
    {
      "name": "pmc",
      "auto-managed": false
    }
  ]
```
