### ISSUE TITLE
Improve error message for unknown tracks

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#190]
If users specify an unknown track, they get a highly confusing error message:

```
2016-11-30 19:18:55,856 root ERROR Cannot run subcommand [race].
Traceback (most recent call last):
  File "/home/elastic/rally/esrally/track/loader.py", line 336, in read
    rendered = render_template_from_file(track_spec_file)
  File "/home/elastic/rally/esrally/track/loader.py", line 278, in render_template_from_file
    return render_template(loader=jinja2.FileSystemLoader(io.dirname(template_file_name)), template_name=io.basename(template_
file_name))
  File "/home/elastic/rally/esrally/track/loader.py", line 272, in render_template
    template = env.get_template(template_name)
  File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/usr/lib/python3.4/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: track.json
```

We should provide a clear and actionable error message instead.

**Comment by cdahlqvist** [comment]
Would it be possible to make Rally search all repositories listed in rally.ini by default?

**Comment by danielmitterdorfer** [comment]
@cdahlqvist Sure, it's possible technically. However, I think it has a couple of negative implications on usability:

* If we search, across repositories and stop at the first match, it can lead to surprising results when your track names are not unique across repositories (unless we go so far as to define a priority)
* The search across repositories also takes time because we'd need to do a `git pull --rebase` for each repository.
* Not each repository needs to define branches for each Elasticsearch version. E.g. it's fine if you want to benchmark 1.7 against 2.0 with a custom track and create a repo for that. If you'd then run a benchmark for 5.x and we encounter this repository which has no matching branch, we could now either skip this track repo entirely (because it has no matching branch) or we could check the current branch (or the master branch?) and check whether a track with this name exists and notify the user that the track is there but in a wrong version.

In summary this could get more complex than it looks and I'm not sure whether it's worth the effort. 

**However**: If you just want Rally to use your track repository by default you can just replace the default track repository definition. Here is an example:

`~/.rally/rally.ini`:

```
...
[tracks]
default.url = git@github.com:elastic/rally-tracks.git
mytrackrepo.url = https://github.com/danielmitterdorfer/ct.git
```

Say, you want Rally to run with `mytrackrepo.` by default. Then just define it as `default.url`. E.g.:

`~/.rally/rally.ini`:

```
...
[tracks]
default.url = https://github.com/danielmitterdorfer/ct.git
old-rally-default.url=git@github.com:elastic/rally-tracks.git
```

Don't forget to rename the folder of the local working copy:

```
cd ~/.rally/benchmarks/tracks/
mv default old-rally-default
mv mytrackrepo default
```

From now on, Rally will treat your repository as default and you need to run Rally with `--track-repository=old-rally-default` if you want to use the out-of-the-box Rally tracks.

Does this help you? If not, then I'd say we should create a new ticket because this problem is related and needs to be fixed nonetheless.

**Comment by cdahlqvist** [comment]
Those reasons make perfect sense. Using the trick by changing the default repository will work for me if needed.

**Comment by danielmitterdorfer** [comment]
Great! Then we'll keep it as is. I think it could make sense to add this trick also to the docs.
