### ISSUE TITLE
Support target-interval for operations

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/rally#191]
When rate limiting operations it is currently possible to specify this through the "target-throughput" parameter. While this supports most scenarios, it is a bit cumbersome to use when you want to configure something to happen every X seconds as you have to calculate a decimal value that approximates this. Examples of this are simulating periodic scan and scroll jobs or very heavy queries.

For this type of scenarios it would be useful to be able to specify the "target-interval" in seconds instead of the throughput.

**Comment by danielmitterdorfer** [comment]
Postponing as there is a workaround available.
