### ISSUE TITLE
Meaning of schedule properties

### ISSUE THREAD

**Issue by sterchelen** [elastic/rally#192]
Hi,

First of all, I want to thank you for this useful tool !!

I'm writing my own track and I'm a bit confused with the meaning of the schedule properties, like :

- warmup-time-period
- warmup-iterations
- target-throughput
- etc.

I think that the documentation is missing the description of these properties ... 
Could you explain me the meaning of them ?

Thank you !

**Comment by danielmitterdorfer** [comment]
Hi @sterchelen,

Glad to you like Rally. :) Most of these properties are described in the [JSON schema](https://github.com/elastic/rally/blob/master/esrally/resources/track-schema.json). However, I think are more thorough documentation would be really helpful. I try to add that within the next days.

`target-throughput`  is one of the properties that is not documented in the JSON schema, so I'll quickly explain here: If you don't specify it, this means that Rally will execute the operation as fast as it can. This is mostly useful for batch operations (e.g. bulk indexing) where you want to add documents as fast as possible. However, when you run queries, you're typically interested in getting a timely result (i.e. a relatively low latency is important). Also, your system has some specific query load, say for example on average you get 10 searches per second. If you want to benchmark this scenario, you can set `target-throughput` to 10 (operations / second). Rally will then ensure that it runs only 10 queries per second, even if Elasticsearch responds much faster.

**Comment by sterchelen** [comment]
Quick and useful response ! Thank you @danielmitterdorfer  👍

**Comment by sterchelen** [comment]
Hi @danielmitterdorfer ,

I have another question about the result meaning. We have min, median, max, 50th percentile latency ... etc.

In the doc I've not found any information on the result :(

**Comment by danielmitterdorfer** [comment]
@sterchelen: I guess min and max is pretty clear and the most confusing ones are:

* Median: Sort all data and take the value in the middle. Contrary to the mean, this value is more stable against outliers. https://en.wikipedia.org/wiki/Median
* Percentiles: See https://en.wikipedia.org/wiki/Percentile

I hope that helps you in the meantime. I'll add a bit more information on that to the docs.

What's already available though is a [definition of all metric keys](http://esrally.readthedocs.io/en/latest/metrics.html#metric-keys) (e.g. what's the difference between service time and latency?)

**Comment by danielmitterdorfer** [comment]
@sterchelen I've create a reference documentation for tracks now. You can already have a look at the [preview version](http://esrally.readthedocs.io/en/latest/track.html).
