### ISSUE TITLE
Cluster health on expected indices only

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/rally#201]
I am trying to run a against a single node cluster that is in yellow state because marvels indices are not fully replicated:

 ```
root@benchmark:/var/lib/waagent/custom-script/download/0# curl --user es_admin:pass http://data-0:9200/_cat/shards 
geonames                3 p STARTED       0    159b 10.0.0.6 data-0                                                                                                                                                                                              geonames                4 p STARTED       0    159b 10.0.0.6 data-0
geonames                1 p STARTED       0    159b 10.0.0.6 data-0
geonames                2 p STARTED       0    159b 10.0.0.6 data-0
geonames                0 p STARTED       0    159b 10.0.0.6 data-0
.marvel-es-data-1       0 p STARTED       2   4.2kb 10.0.0.6 data-0
.marvel-es-data-1       0 r UNASSIGNED
.marvel-es-1-2017.01.16 0 p STARTED    2189 740.4kb 10.0.0.6 data-0
.marvel-es-1-2017.01.16 0 r UNASSIGNED        
```

```                                                                                                                                                                                      root@benchmark:/var/lib/waagent/custom-script/download/0# curl --user es_admin:pass http://data-0:9200/_cat/health?v
epoch      timestamp cluster          status node.total node.data shards pri relo init unassign pending_tasks max_task_wait_time active_shards_percent
1484575979 14:12:59  my-azure-cluster yellow          1         1      7   7    0    0        2             0                  -                 77.8%
```

`esrally` does not like it because it waits for cluster state `green` but should it be  more selective on the indices to wait for cluster state green on e.g `/_cluster/health/geonames,etc?wait_for_status=green`

Not a blocker on my end, will run against a 3 node cluster when provisioning is all scripted.

**Comment by danielmitterdorfer** [comment]
The main reason why Rally checks the cluster status (and also expects it to be `green`) is that I want to avoid running benchmarks while the cluster might be relocating shards thus affecting performance without the user noticing.

To still allow running benchmarks in these cases, we currently use an undocumented command line parameter `--cluster-health`. I'd rather turn this into a documented parameter than to implicitly starting a benchmark regardless of cluster health (I know that only checking at the beginning is not perfect but it's better than nothing IMHO). Wdyt?

**Comment by danielmitterdorfer** [comment]
Closing as `--cluster-health` is now a documented command line option.
