### ISSUE TITLE
Make track configuration more modular

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/rally#205]
Currently all track configuration must reside inside the track.json file. This makes it easy to use the track as it is but hard to update, extend or modify, at least as long as one want to easily be able to benefit from improvements or modifications to the original track.

It would be a lot easier to extend and modify tracks if the configuration could be spread out across an arbitrary number of files and Rally was able to read all these and join them at startup. Which files that are read could be controlled through either file type (e.g. all json files in directory) or suffix (e.g. .challenge files for challenges etc).

This would allow users to fork the repository and add new challenges and operations without having these new files conflict with the original repository. For simple tracks the benefit is perhaps not that great, but as more complicated tracks including custom runners and parameter sources are developed, being able to easily merge improvements in the parent repository will be more important.

**Comment by danielmitterdorfer** [comment]
Docs are available at http://esrally.readthedocs.io/en/latest/adding_tracks.html#structuring-your-track
