### ISSUE TITLE
Make challenges composable

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/rally#206]
At the moment I believe Rally is limited to running a single track at a time per host. In order to create complex and more realistic loads in order to accurately simulate real production workloads, tracks run the risk of quickly becoming very complex and difficult to reuse efficiently. Combining workloads from multiple tracks currently means that a completely new track need to be created.

As more complex tracks simulating specific workloads are developed by the community, it would be useful if the track repositories were treated more as modules, so that it would be possible to create tracks/challenges that import from multiple existing tracks. This would make it easier to reuse work done by the community and reduce the time it takes to configure a new benchmark configuration.

**Comment by danielmitterdorfer** [comment]
Another concrete use case for this: Somebody wants to write a new track but reuse data from an existing one.

**Comment by danielmitterdorfer** [comment]
Closing in favor of #366.
