### ISSUE TITLE
Show total size of payload in track info when listing tracks

### ISSUE THREAD

**Issue by geekpete** [elastic/rally#210]
I used to use the tiny track to do quick/simple rally testing because I knew it was a small track to both download and store.

With the other tracks, you have no idea of the size required on disk or the network impact (size and time) without going into the track file and adding up all the payload file sizes or by running it once to see the resulting payload files on disk after they're retrieved.

It would be neat to show a total size indicator when listing tracks with rally.

This might even just be easy to add to the end of the description, but would be nicer if it was calculated from the track file where the sizes of payloads are specified.

**Comment by danielmitterdorfer** [comment]
> I used to use the tiny track to do quick/simple rally testing because I knew it was a small track to both download and store [...] with the other tracks, you have no idea of the size required on disk or the network impact (size and time)

Are you aware of [`--test-mode`](http://esrally.readthedocs.io/en/latest/command_line_reference.html#test-mode)? It download only a tiny portion of the benchmark corpus (1.000 docs) and you can use it for all our tracks in the default repository. E.g.:

```
esrally --track=geopoint --test-mode
esrally --track=logging --test-mode
```

Does this help or do you still think we need to show the corpus size in the list command?

**Comment by geekpete** [comment]
Yeah test-mode is probably fine for "just getting some data in there", but it still needs to download the full payload first?

**Comment by danielmitterdorfer** [comment]
No, test mode does not download the full data set. The track author needs to prepare a stripped down file containing just the first 1.000 docs with the suffix `-1k` for that (I admit the docs are light on that one). E.g. if your data are contained in `documents.json.bz2` you need to provide `documents-1k.json.bz2` as track author (and all our default tracks do just that).

**Comment by danielmitterdorfer** [comment]
So I guess if that is sufficient for you I'd close the ticket as "Won't fix".
