### ISSUE TITLE
Add unique ID for the execution of a challenge

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/rally#218]
For analysis it would be convenient to have an identifier (hash or UUID) that uniquely identifies the execution of a specific challenge added to all metrics records related to it. This makes it possible to easily drill in using a single parameter in Kibana and makes it easier to work with a central metrics store where multiple Rally instances concurrently write metrics to.

**Comment by danielmitterdorfer** [comment]
At the moment Rally uses the race timestamp for that. For each race we store the following information:

```json
{
  "car": "4gheap",
  "target-hosts": [
    "some-host:9200"
  ],
  "selected-challenge": {
    "operations": [
      "index"
    ],
    "name": "append-no-conflicts"
  },
  "user-tag": "",
  "track": "percolator",
  "pipeline": "from-sources-skip-build",
  "environment": "nightly",
  "trial-timestamp": "20170209T075251Z",
  "revision": "f707132",
  "laps": 1,
  "distribution-version": "6.0.0-alpha1"
}
```
and we use the `environment` and the  `trial-timestamp` as the "natural" key usually (e.g. when identifying races in tournament mode). Is this sufficient or do you think we need an technical id in addition?

**Comment by cdahlqvist** [comment]
In order to use it efficiently in Kibana visualisations I have usually created it as a not_analyzed/keyword field. Am not sure how easy it would be to use a date field in the same way. I therefore think a UUID might be a good addition.

**Comment by danielmitterdorfer** [comment]
Sounds reasonable. But I think we should have only one user-facing key for a race (e.g. for tournaments). Ideally, we will also not present the full-length UUID to the user but rather shorten it (similar to what git does).

So, while the actual change is pretty easy and isolated, I think we should go the extra-mile and make this consistent across the codebase.

**Comment by cdahlqvist** [comment]
I like the idea around the shortened UUID. I think this would be more useful than the starting time of the benchmark.

**Comment by russmac** [comment]
@cdahlqvist The trial-timestamp('s) can be hardcoded into a search or with a boolean AND query, Or left out of the search and used in the visualization on the x axis as a terms aggregation. 

Personally I think adding a UUID does not add much. A string describing the particular trial would be more useful. At the moment I name my visualizations in sequence , matching the sequence of dates in the legend. Which obviously cant work when using the field to fetch the X most recent trials.. (Although it sounds like I can do this by changing the environment each trial, some users might want to retain env to its specific meaning)

**Comment by danielmitterdorfer** [comment]
I'll close this ticket as "Won't fix" because this can be achieved by user tags. You could provide a human-readable name, e.g.  `--user-tag="name:filesystem-settings-benchmark"`. If you need to have a UUID you can generate one with `uuidgen` which is available on Unix, e.g.: `--user-tag="id:`uuidgen`"`.

Notes:

* It is possible to define multiple user tags separated by a comma (e.g. `--user-tag="name:filesystem-settings-benchmark,fs:ext4,options:noatime"`)
* Rally will store the user tag not only for raw metrics but also for aggregated results in the indices `rally-results-*` and `rally-races-*` starting with Rally 0.9.2 (see #392 for details)
