### ISSUE TITLE
Report number of hits, not just pages, for scroll queries

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/rally#222]
It is useful to know how many hits that were retrieved by a scroll query, not just the number of pages, as this allows analysis of the efficiency of various page sizes more easily.

**Comment by danielmitterdorfer** [comment]
This can be solved pretty easily and is completely local to `Query#scroll_query()`. We just need to keep track of the results count and return a `dict` with the meta-data instead of a tuple.
