### ISSUE TITLE
Allow unlimited number of pages for scroll queries

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/rally#223]
Often it is difficult to determine the number of pages that will be required for the result set of a scroll query. It would be useful to be able to specify the maximum number of pages as unlimited instead of having to set it to a very large value, which would probably have the same effect.

**Comment by danielmitterdorfer** [comment]
You  are right: Setting the number of pages to a very large value is a sufficient workaround. Hence, moving this to backlog.

**Comment by danielmitterdorfer** [comment]
If you specify `"pages": "all"` (instead of e.g. `"pages": 5`) the scroll query will be executed until all results have been retrieved.
