### ISSUE TITLE
Issue(s) with --user-tags

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/rally#224]
In the documentation an example is given where user-tag can be specified as follows:

`--user-tag=github-issue-1234-baseline`

This does however result in the following error on master:

```
2017-02-09 15:06:36,140 root ERROR Cannot run subcommand [race].
Traceback (most recent call last):
  File "/Users/acd/github/rally/esrally/metrics.py", line 229, in open
    user_tag_key, user_tag_value = user_tag.split(":")
ValueError: not enough values to unpack (expected 2, got 1)
```

It seems the following format is required:

`--user-tag=env:laptop`

When trying to specify multiple tags, none of the following works:

`--user-tag=env:laptop,disk:ssd`  (Results in error)

`--user-tag=env:laptop --user-tag=disk:ssd` .  (Only last tag applied)

**Comment by danielmitterdorfer** [comment]
Thanks for bringing this up. While this is mainly a documentation issue, you raise an important point: The name "tag" may imply that you can have an arbitrary number of them (which is not the case). 

We should definitely fix the documentation bug as an immediate measure but I think we should also either rename it to something else that makes it clear that only one key-value pair is supported or support multiple of them. Btw, I'd prefer the syntax `--user-tag=env:laptop,disk:ssd` in the latter case.

**Comment by danielmitterdorfer** [comment]
I fixed the doc bug in this issue. Please open a new one in case we should extend this feature (as described above).
