### ISSUE TITLE
Enhance flexibility of user tagging

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/rally#227]
It would be useful to enhance the --user-tag functionality to allow the user to add multiple tags at the execution level as discussed in the following issue: https://github.com/elastic/rally/issues/224#issuecomment-278877145

It would be great if both the following formats could be supported, but either one is otherwise fine.

`--user-tag=env:laptop,disk:ssd`

`--user-tag=env:laptop --user-tag=disk:ssd`

**Comment by DBarthe** [comment]
I think I also need this feature.

How people do currently manage to benchmark multiple, possibly mixable, parameters (and then process some aggregations from kibana) ?

**Comment by danielmitterdorfer** [comment]
With the next release of Rally (0.6.2) it will be possible to specify multiple tags separated by a comma, e.g. `esrally --user-tag="disk:SSD,data_node_count:4"`.
