### ISSUE TITLE
Make logging level configurable

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/rally#230]
It would be very convenient to have a command line parameter for Rally that allows the logging level to be specified for a race, e.g. `--log-level=debug`.

**Comment by danielmitterdorfer** [comment]
Agreed. This definitely makes sense. Just a reminder for the implementation: Python logging is a bit tricky (esp. w.r.t. to initialization of loggers) and we also need to consider that in the distributed case, the actor system manager might already be running in the background and we need to take care of that one too.

**Comment by danielmitterdorfer** [comment]
We'll not solve this with a command line parameter but instead externalize the current logging configuration to a configuration file. This should be much simpler and also allows for more control (e.g. logging format, log file rotation, different appenders, ...).
