### ISSUE TITLE
Make client execution more flexible

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/rally#236]
If I configure a task in a schedule to run once every 10 seconds using 2 clients (as in example below), e.g. in order to be able to execute the correct number of operations during the benchmark even if the service time starts to exceed 10 seconds, it seems like both clients issue a request at the same every 20 seconds.

```
{
  "operation": "index-append-1000",
  "warmup-time-period": 0,
  "time-period": 600,
  "target-interval": 10,
  "clients": 2
}
```

It would be useful to have the option to be able to stagger, or even randomize, the initial starting time for each client so that requests would get spread out.

**Comment by danielmitterdorfer** [comment]
I tend to close this one in favor of #251. Because if you have a non-uniform request distribution anyway I doubt that you still care about what happens at the first request which is usually during the warmup phase (and after that clients will not issue requests at exactly the same time in the general case due to the non-uniform distribution).

**Comment by danielmitterdorfer** [comment]
Closing in favor of #251 as it will allow users to specify arbitrarily complex scheduling strategies.

**Comment by cdahlqvist** [comment]
I still think this is valuable as it allows spreading out requests over time without having to write a scheduler (it would still be hard to coordinate multiple processes through a scheduler).

**Comment by danielmitterdorfer** [comment]
> I still think this is valuable

With the current scheduler implementations you can already randomize right from the beginning. Here is an example that shows how different scheduling strategies behave that I've already implemented:

![schedules](https://cloud.githubusercontent.com/assets/1699576/24614982/3cd73e24-188d-11e7-9e05-1c99cd1c9f2a.png)

It just shows the first ten seconds and all three strategies have been configured for a target throughput of 1 operation per second. I have to come up with a better name but "equal" is the strategy that Rally has used so far. Uniform and Poisson are two new distributions and you can already see that the problem that clients will issue requests always at exactly the same time will not happen anymore.

> it would still be hard to coordinate multiple processes through a scheduler

There will be no global coordination - even with a scheduler. The "master" load driver actor will attempt to start all clients at the same time. A scheduler instance is bound to one client and decides locally when to issue the next request (and depending on the scheduler implementation this will be at different times for different clients).
