### ISSUE TITLE
A question for result benchmark

### ISSUE THREAD

**Issue by phucvinh52** [elastic/rally#243]
I have a result benchmark
https://docs.google.com/spreadsheets/d/1DtZw7omQR5jqehCCtgJn-tY2H0Nnepktt6cJ4mgGzZM/edit?usp=sharing

- When I increase data node and replicas, term latency increase and throught put decrease. Do my config  have a problem?
This is my config es master so same es data 
```
cluster.name: cluster-es
node.name: node-xxx
network.host: ["xxx.90.33.22"]
http.port: 9200
discovery.zen.ping.unicast.hosts: ["xxx.90.33.18"]
discovery.zen.minimum_master_nodes: 2
thread_pool.search.queue_size: 1000000
thread_pool.bulk.queue_size: 1000000
indices.breaker.fielddata.limit: 75%
```

**Comment by danielmitterdorfer** [comment]
Hi @phucvinh52. I am sorry but Github is reserved for reporting issues only. Can you please ask your question instead in the user forum at https://discuss.elastic.co/c/elasticsearch/rally?
