### ISSUE TITLE
Connection behind a proxy fails. has_internet_connection() returns False

### ISSUE THREAD

**Issue by Erni** [elastic/rally#245]
I´ve been trying to use Rally from behind a proxy in a clean installation but it doesn´t work because it "thinks" there is no internet connection.
Even if Rally gets the proxy url when the `http_proxy` environment variable is available, the function `has_internet_connection()` in `esrally/utils/net.py` does not check this. It tries to open a socket to `www.github.com` without considering the proxy, thus failing and returning `False`. Then Rally works in `offline` mode, which is not what it should.

**Comment by danielmitterdorfer** [comment]
Thanks for the report. That's a good point. The connection check should also go through the proxy if there is one.

**Comment by Erni** [comment]
Great. Thanks for quick response and fix :)

**Comment by danielmitterdorfer** [comment]
@Erni I've just released Rally 0.5.2 (see also https://discuss.elastic.co/t/rally-0-5-2-released/77300) so you might want to upgrade.

**Comment by Erni** [comment]
Thank you very much!
