### ISSUE TITLE
Saving tournament report

### ISSUE THREAD

**Issue by keyur9** [elastic/rally#249]
Hello,

It would be great if we could save the tournament report in markdown file. This command is not working `esrally compare --baseline=XX --contender=XX --report-file=tournament.md`

**Comment by keyur9** [comment]
Hello @danielmitterdorfer , 

Could you please look at the PR - Saving tournament report [Closes #249] and let me know your thoughts.

Thank you,

**Comment by danielmitterdorfer** [comment]
Added target release 0.5.3 based on the assumption that #250 gets merged.
