### ISSUE TITLE
Support for non-deterministic distribution of operations

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/rally#251]
There are use cases where it would be desirable to vary the request rate over time, e.g. when replaying user sessions and/or varying load to simulate daily patterns in long running benchmarks. It would be great to have support for this in Rally as it would add a lot of flexibility.

I have spent the last few days thinking about ways to do this, and one reasonably simple way could be to allow a custom parameter source to return the duration until it expects to run the next request and have Rally use this to override the fixed interval used when in rate limiting mode.

It is a simple way to give control to the parameter source, which allows scripting this, but maybe not the ultimate solution.

**Comment by danielmitterdorfer** [comment]
As you describe, the current request throttling strategy is based on a uniform distribution. It is implemented in [driver.py](https://github.com/elastic/rally/blob/3bd07cce8efe3f9f388636807daf85530f67b0f7/esrally/driver/driver.py#L744-L747). 

I was also thinking about allowing other distributions (like Poisson processes) at some point and I think we should keep request throttling based on any statistical distributions within Rally but let users choose via `track.json` which distribution to use.

However, you mention simulating more complex traffic patterns and this might even warrant introducing a new concept in addition to parameter sources and runners.

**Comment by cdahlqvist** [comment]
When simulating traffic based e.g. on data from a file, it would be convenient to control this from the parameter source. I however don't see why allowing this would preclude us from also offer another method that might e.g. be more suited to altering patterns around large bulk requests.
