### ISSUE TITLE
Rally should show the size of the index in the report when pipeline is benchmark-only

### ISSUE THREAD

**Issue by trevan** [elastic/rally#252]
I run rally with benchmark-only (to run against a system closer to our production) and I noticed that it doesn't report the index size.  If I switch to the default pipeline, it does show the index size.

It would be nice if rally would grab the index size through the index stats or the shard stats and report that when the pipeline is benchmark-only.

**Comment by danielmitterdorfer** [comment]
The reason for the difference is that Rally captures the index size by actually inspecting the file system after it has shutdown the cluster to get the most accurate results and this is something it cannot do when you use the benchmark-only pipeline.

We might be able to get a proxy metric (but I would not assign it the same name to avoid confusion).

**Comment by danielmitterdorfer** [comment]
With the next version of Rally (0.10.0) we will show two new metrics in the summary report:

* Store size
* Translog size

as reported by the [indices stats API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html). While the sum of both values (store size + translog) are very close to the actual size on the file system in my tests (difference of a few KB on a multi-GB index), I want to stress that we use different methods to retrieve those three metrics (indices stats API while the cluster is running vs. measuring file size on the file system after the cluster has been shut down).
