### ISSUE TITLE
Forcemerge should report index size, segment count, and heap usage

### ISSUE THREAD

**Issue by trevan** [elastic/rally#254]
Running force-merge changes index size, segment count, and heap usage.  It would be nice if esrally reported the new values after force-merge runs in addition to the original values from the original index operation.

**Comment by danielmitterdorfer** [comment]
That is the point of force-merge: We run it as an intermediate step in our benchmarks to get better reproducible results for queries. The metrics you describe are also not gathered during the benchmark but rather at the very end of it (index size is even determined only after the cluster has been shutdown).

If you are interested in metrics without running force-merge, I think the best option is to create two challenges:

* run only an index operation
* run indexing, then force-merge

However, you should account for run-to-run variation by repeating the benchmark several times.
