### ISSUE TITLE
Some wrong about remote test 

### ISSUE THREAD

**Issue by mcgino** [elastic/rally#255]
Hi，
    I‘m trying to test my ES.I install ESRALLY in my VM and install ES in my server.
    When I try to test,system always say error.
    Plz help me.Thanks

   

**Rally version** (get with `esrally --version`):
esrally 0.5.2
**Invoked command**:
   esrally --target-hosts=172.18.20.100:9200 --pipeline=benchmark-only
**Configuration file (located in `~/.rally/rally.ini`))**:

**JVM version**:
gaofan@ubuntu:~$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**OS version**:
ubuntu  16.10 x86
**Description of the problem including expected versus actual behavior**:

**Comment by danielmitterdorfer** [comment]
@mcgino We reserve Github for bug reports and have a dedicated Discuss forum at https://discuss.elastic.co/c/elasticsearch/rally. Can you please ask your question there? If you create a post over there please include specific detail about which error you get.
