### ISSUE TITLE
Document additional decompression options

### ISSUE THREAD

**Issue by ppf2** [elastic/rally#256]
http://esrally.readthedocs.io/en/latest/track.html?highlight=gz

It says that the documents passed in must be compressed in a file using bz2, zip or tar.gz formats, but as part of https://github.com/elastic/rally/pull/88, we added more [decompression](https://github.com/elastic/rally/blob/master/esrally/utils/io.py#L145) options right?

**Comment by danielmitterdorfer** [comment]
I confirm. It makes sense to document all of them.
