### ISSUE TITLE
Can we use the slowlog to generate tracks?

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#262]
Currently users need to tell Rally very explicitly what queries they want to run and at which rate. With the recent addition of schedules added in #251 we introduced a bit more flexibility but it is still a bit cumbersome to create tracks based on observed production traffic. We should investigate whether it is possible to use Elasticsearch's query slowlog (with a threshold of 0 to capture all queries) as an input to create a new track.

**Comment by HonzaKral** [comment]
I would love to be able to point a `search` action to a file containing the slowlog information and have it just replay the queries within. Unless I am missing something (entirely possible) it sounds feasible with a subclass of `Query` runner that will just iterate over the slowlog file, parsing it on the fly, instead of just return same (parametrized) `body`. If parsing will prove too expensive we can always pre-process it similarly to how we uncompress data files.

I am not sure we can actually replay the queries contained within in the exact time intervals specified in the logs, but I also don't think that's required.

Either way it would be an incredibly useful feature!

**Comment by danielmitterdorfer** [comment]
I can have a closer look for the current 0.9.x series. I'll adjust the target milestone accordingly.

**Comment by danielmitterdorfer** [comment]
W.r.t. to the time interval of query executions we should analyze the time stamps in the log file and it may make sense to allow speed up / slowdown by a factor too.

**Comment by danielmitterdorfer** [comment]
I had a closer look and there are several challenges that need to be solved for this to work. In the description below I assume that Rally does not parse the slowlog on the fly but we rather use a pre-processing step. The reasons why I think a pre-processing step makes more sense will hopefully become clearer after reading the text below.

# Challenges

## Task Scheduling

From the log time stamps we can infer when to schedule an operation. Although the timestamp just reflects when the query was logged (not when it has been sent by the client), it is probably still a close-enough approximation that we can use.

However, we cannot infer how many clients we should use nor whether it is always the same number of clients regardless of the type of query (this brings us to the next point).

## Reporting

If we implement this naively we would just treat all of the queries as a single type of queries but it is highly likely that there are different types of query that just vary in their parameters. So it would make sense to apply some sort of classifier. For the first version I'd rather keep it simple and leave this up to the user.

## Long queries are likely truncated

Log4J2 allows to define a maximum line length (see [docs](https://logging.apache.org/log4j/2.x/manual/layouts.html#PatternLayout)) and we currently use the following configuration in Elasticsearch:

```
appender.index_search_slowlog_rolling.layout.pattern = [%d{ISO8601}][%-5p][%-25c] %marker%.-10000m%n
```

This means that we truncate queries with a source that is longer than roughly 10000 characters by default (unless the user changes this). I say "roughly" because it actually specifies the length of the complete log message, not just the source.

There is nothing we can do in this case and we should fail *hard* (i.e. we will not silently skip these queries). It is up to the user to provide a slowlog file that contains only valid queries.

# Potential Solution

Several of the steps above (e.g. query classification) may require human intervention so I think for the time being it makes sense to decouple workload specification (i.e. from a slowlog file to a track) from workload execution (i.e. running the benchmark).

## Workload Specification

We will add a generator to Rally that can read one (or more) slowlog files and produces one output file that contains the following fields:

* A timestamp that is the time in seconds relative to the start of the benchmark (type: float). This timestamp defines when a query should be executed.
* The number of seconds it took the query to execute (type: float).
* A string containing the query to execute.
* A string containing a name of the query type for reporting (e.g. "query-users", "hourly-site-hits", "error-rate-per-api"). At the moment, this field will always be empty and needs to be amended by the user. We *may* provide a generated name for queries with equal query bodies (i.e. an exact match).

The file contents will be ordered (ascending) by the timestamp. 

After the output file has been amended by the user (with at least the query type), we will process this file again to assign clients in the next step.

### Client Assignment

Two questions that we need to answer as well:

* How many clients should execute the workload?
* Which client executes which queries?

#### Number of Required Clients

To answer the first question we will use a list of triples (`start timestamp`, `duration`, `query`) as input data structure. We will call this list `query_workload`. We will derive these triples by reading the file generated in the first step (for the following discussion we will ignore the query type. Although it is important later on, it is not relevant for the discussion here).

We will apply the following algorithm:

1. Iterate over each item in `query_workload`. In each step, append the current triple into a new list called `concurrent_requests`.
2. Check for "overlaps" between all triples in the list `concurrent_requests`. Two triples `P` and `Q` (with the property that the `start timestamp` of `P` <= `start timestamp` of `Q`) "overlap" if and only if `start timestamp` + `duration` of `P` >= `start timestamp` of `Q`. If `P` and `Q` do not overlap, remove `P` from the list `concurrent_requests`.
3. Determine the maximum size of `concurrent_requests` while iterating. This size is the minimum number of clients that is needed to execute the benchmark.

**Example**

Consider the following list of triples (`start timestamp` in seconds, `duration` in seconds, `query`):

```python
(100.0, 10.0, "{ "query": { "match_all": {}}}")
(103.0, 5.0, "{ "query": { "match_all": {}}}")
(110.0, 3.0, "{ "query": { "match_all": {}}}")
(111.0, 7.0, "{ "query": { "match_all": {}}}")
```

In the following example, we will refer to each triple only by their `start timestamp` to keep the example readable. In reality, we'd put the whole triple into the list.

Item 0:

* In step 1, we add the current triple to `concurrent_requests`, so `concurrent_requests = [100.0]`.
* In step 2 we only have one list entry, hence we skip it.
* In step 3, we determine that `concurrent_requests` has a length of 1.

Item 1:

* In step 1, we add the current triple to `concurrent_requests`, so `concurrent_requests = [100.0, 103.0]`.
* In step 2 we compare both triples: as `100.0 + 10.0 >= 103.0` both entries overlap. We keep both entries in the list.
* In step 3, we determine that `concurrent_requests` has a length of 2.

Item 2:

* In step 1, we add the current triple to `concurrent_requests`, so `concurrent_requests = [100.0, 103.0, 110.0]`.
* In step 2 we compare: `100.0 + 10.0 >= 103.0` => overlap, `100.0 + 10.0 >= 110.0` => overlap and `103.0 + 5.0 >= 110.0` => no overlap. Hence, we remove the triple with the `start timestamp` 103.0 from the list and the result is `concurrent_requests = [100.0, 110.0]`
* In step 3, we determine that `concurrent_requests` has a length of 2.

Item 3:

* In step 1, we add the current triple to `concurrent_requests`, so `concurrent_requests = [100.0, 110.0, 111.0]`.
* In step 2 we compare: `100.0 + 10.0 >= 110.0` => overlap, `100.0 + 10.0 >= 111.0` => no overlap and `110.0 + 3.0 >= 111.0` => overlap. Hence, we remove the triple with the `start timestamp` 100.0 from the list and the result is `concurrent_requests = [110.0, 111.0]`
* In step 3, we determine that `concurrent_requests` has a length of 2.

The maximum value of `concurrent_requests` is 2 which is the number of clients that we need to execute that workload.

We can either use this value directly or just suggest it to the user which can adjust it in the track (that also depends a little bit when we execute this step but the requirement to let the user specify a different number of clients already suggests that we should run this step when generating the track).

#### Client Assignment

The second question is about client assignment. Here we can use the same list of triples as input data structure and the number of clients that we have determined in the first step (or provided by the user). A precondition is that the number of clients in this step must be greater than or equal to the number of clients determined in the first step (a smaller number of clients would lead to overlaps). To spread load we will assign queries to clients in a round-robin fashion. As queries have different expected durations, some clients might still be busy. We will use a similar algorithm to determine which client is available to execute the next query. We will build a matrix such as the following:

| client  |  slot 0         | 
|---------|-----------------| 
| client0 |  | 
| client1 |  | 


On the "y-axis" we have one slot per client and the "x-axis" represents the order in which queries will get executed. Our algorithm iterates over `query_workload` and starts to insert items from the top-left of the matrix to the bottom-right of the matrix (honoring the query duration). So, after the first two steps, the matrix will look as follows:

| client  | slot 0          | 
|---------|-----------------| 
| client0 | (100.0,10.0,q1) | 
| client1 | (103.0,5.0,q2)  | 


The next triple to insert is `(110.0, 3.0, "{ "query": { "match_all": {}}}"). There are no more clients left, so we will expand to the right now and start with `client0` again. Before inserting, we will check whether the query to our right (that is `(100.0,10.0,q1)`) has already finished (i.e. `100.0 + 10.0 < 110.0`). This is not the case so we move further down to `client1. The previous query has already finished so we will insert it here:

| client  | slot 0          | slot 1         | 
|---------|-----------------|----------------| 
| client0 | (100.0,10.0,q1) |                | 
| client1 | (103.0,5.0,q2)  | (110.0,3.0,q3) | 

Next is `(111.0, 7.0, "{ "query": { "match_all": {}}}")`. There are not all clients occupied in slot 1, so we try to insert in slot 1. We compare `client0`'s query in slot 0 to our candidate query: `100.0 + 10.0 < 111.0`. This time, the previous query has finished and we can insert it:

| client  | slot 0          | slot 1         | 
|---------|-----------------|----------------| 
| client0 | (100.0,10.0,q1) | (111.0,7.0,q4) | 
| client1 | (103.0,5.0,q2)  | (110.0,3.0,q3) | 

At this point, we can produce an output file that contains this matrix.

## Workload Execution

The final file, generated above can then be used as input for a track. This could be a potential structure:

```json
{
  "schedule": [
    {
      "operation": {
        "operation-type": "search",
        "workload": "queries.json"
      },
      "warmup-time-period": 240
    }
  ]
}
```

Depending on our further exploration the syntax can change significantly.

Rally already has a notion of a "schedule". At the moment, Rally core only implements a deterministic scheduler and a poisson scheduler which can iteratively calculate the next point in time when a query needs to be issued. We will need to implement a new type of scheduler that determines the timepoint to issue a query based on the workload input file.

Rally has a notion of a "parameter source" which provides queries. We will need to find a possibility to let the parameter source feed information to the schedule (or execute both of them in lockstep). Also, client assignment can already be handled in the parameter source easily.

**Comment by cdahlqvist** [comment]
Would it be possible to create some type of work queue, which the clients could pull from instead as they become available to process another job? This would add a bit of overhead, but would simplify scheduling. This would also prevent a query that runs much longer than expected to delay the whole benchmark.

**Comment by danielmitterdorfer** [comment]
> Would it be possible to create some type of work queue?

This is an interesting idea which we might look into later on. However, I think for the first iteration there is already enough complexity. Also, Rally uses a "share nothing" design where each client knows upfront which tasks it has to perform contrary to a pull-based model that you are suggesting, i.e. this would maybe also result in quite significant changes internally as well. However, it might be worthwhile to pursue mid- to long-term.

**Comment by danielmitterdorfer** [comment]
We should also take into account https://github.com/elastic/elasticsearch/issues/31521

**Comment by danielmitterdorfer** [comment]
Closing as there is currently no intention to work on this and we might come up with a different approach at a later time.
