### ISSUE TITLE
Documentation on settings and warning message when using a documents archive file

### ISSUE THREAD

**Issue by ppf2** [elastic/rally#264]
Per the documentation:

http://esrally.readthedocs.io/en/latest/track.html?highlight=compressed_size_in_bytes#indices

```
document-count (optional): Number of documents in the documents file. This number will be used to verify that all documents have been indexed successfully.
compressed-bytes (optional): The size in bytes of the compressed document file. This number is used to show users how much data will be downloaded by Rally and also to check whether the download is complete.
uncompressed-bytes (optional): The size in bytes of the documents file after decompression.
```

The above settings are optional.  But based on the code comments, these are needed if a document archive file is provided for proper recording of progress and verification of download and uncompression:

```
        :param number_of_documents: The number of documents in the benchmark document. Needed for proper progress reporting. Only needed if
         a document_archive is given.
        :param compressed_size_in_bytes: The compressed size in bytes of the benchmark document. Needed for verification of the download and
         user reporting. Only needed if a document_archive is given.
        :param uncompressed_size_in_bytes: The size in bytes of the benchmark document after decompressing it. Only needed if a
        document_archive is given.
```

If these settings are not provided, then when using an archive file, it will throw this ambiguous warning message:

```
[WARNING] None of the types for index [index_name] defines documents. Please check that you either don't want to index data or parameter sources are defined for indexing.
```

Because these settings are all initialized to be 0, and we [check](https://github.com/elastic/rally/blob/8576f00c4a9a1bc783f30a1485007ae1bb8d1085/esrally/track/track.py#L127) to make sure that they are >0 when determining if there is any valid documents for the type.

It will be nice to sync up the documentation with the comments in the code, and perhaps a more intuitive warning message?

**Comment by danielmitterdorfer** [comment]
`document-count` is still needed but the other two settings are optional now. I've improved the validation code in the track loader and updated the documentation so it matches the implementation.
