### ISSUE TITLE
Support referring to an alias in the  index operation

### ISSUE THREAD

**Issue by zumo64** [elastic/rally#268]
When using roll-over API while benchmarking we use an alias to point to the current "write index"
but we cannot specify an alias name in the index operation definition .
When we do (ex : active-logs is the write alias and apachelogs-1 is the current index)  , we get:

[ERROR] Cannot race. ('Fatal error in load generator [0]', RallyAssertionError('The provided index [active-logs] does not match any of the indices [apachelogs-1].',))

proposed enhancement : allow for 'alias' in the index operation

**Comment by cdahlqvist** [comment]
I do have some limited support for this in my track, which you may be able to use: https://github.com/elastic/rally-eventdata-track

**Comment by danielmitterdorfer** [comment]
I think it makes sense to add this to core.

**Comment by danielmitterdorfer** [comment]
Thinking about it again, this should already work if you define your indexing operation in the following way:

```json
{
  "name": "bulk-index-active-logs",
  "operation-type": "index",
  "index": "active-logs",
  "bulk-size": 5000
}
```

Did you try this already @zumo64?

**Comment by danielmitterdorfer** [comment]
Closing due to lack of feedback. Please feel free to reopen if there is new information.
