### ISSUE TITLE
Support the roll over API as an operation

### ISSUE THREAD

**Issue by zumo64** [elastic/rally#269]
This operation would allow performing roll-over API calls  in parallel of indexing 
In the operation definition we would specify the time interval at which it could be triggered

**Comment by cdahlqvist** [comment]
I added support for this in my track: https://github.com/elastic/rally-eventdata-track

**Comment by danielmitterdorfer** [comment]
I think it does not make sense at the moment to support this:

1. As Christian has mentioned, Rally supports adding this as [custom runner](http://esrally.readthedocs.io/en/latest/adding_tracks.html#custom-runners) with a little Python function:

```python
import elasticsearch

def rollover(es, params):
    es.indices.rollover(alias=params["alias"], body=params["body"])
    return 1, "ops"

def register(registry):
    registry.register_runner("rollover", rollover)
```

2. you can use all operations that Rally core provides across all supported versions (ES 1.x - ES 6.x) and the rollover operation is only available on 5.x or later.
