### ISSUE TITLE
ERROR: Cannot list

### ISSUE THREAD

**Issue by SamyCoenen** [elastic/rally#270]
esrally 0.3.3

**Configuration file (located in `~/.rally/rally.ini`))**:
[meta]
config.version = 6

[system]
root.dir = /home/es/.rally/benchmarks
log.root.dir = logs
env.name = local

[provisioning]
local.install.dir = install

[runtime]
java8.home = /usr/lib/jvm/java-8-openjdk-amd64

[benchmarks]
local.dataset.cache = ${system:root.dir}/data

[reporting]
datastore.type = in-memory
datastore.host = 
datastore.port = 
datastore.secure = 
datastore.user = 
datastore.password = 

[tracks]
default.url = https://github.com/elastic/rally-tracks

[defaults]
preserve_benchmark_candidate = False

**System**: 
Docker image java:8
See [Dockerfile](https://github.com/ebuildy/docker-esrally/blob/master/Dockerfile)
**Description of the problem including expected versus actual behavior**:
List tracks generates exception
**Steps to reproduce**:
 1. esrally list tracks

**Provide logs (if relevant)**:

ERROR: Cannot list

Reason: Track 'pmc' is invalid.

Error details: 'type' is a required property
Instance: {
    "bulk-size": 500,
    "name": "index-append",
    "operation-type": "index"
}
Path: deque(['operations', 0])
Schema path: deque(['properties', 'operations', 'items', 'required'])
es@3e29f63d0ae3:~$ cat .rally/benchmarks/races/2017-04-19-09-49-48/local/logs/rally_out.log 
2017-04-19 09:49:48,9 rally.main INFO Rally version [0.3.3]
2017-04-19 09:49:48,9 rally.main INFO Command line arguments: Namespace(advanced_config=False, car='defaults', challenge='append-no-conflicts', client_options='timeout:90,request_timeout:90', configuration='tracks', configuration_name=None, data_paths=None, distribution_repository='release', distribution_version='', effective_start_date=datetime.datetime(2017, 4, 19, 9, 49, 48, 7126), limit=10, offline=False, override_src_dir=None, pipeline='from-sources-complete', preserve_install='False', quiet=False, report_file='', report_format='markdown', revision='current', rounds=1, subcommand='list', target_hosts='localhost:9200', telemetry='', track='geonames', track_repository='default', user_tag='')
2017-04-19 09:49:48,739 rally.track INFO Rebasing on 'master' in '/home/es/.rally/benchmarks/tracks/default' for distribution version ''.
2017-04-19 09:49:48,785 rally.track INFO Rebasing on 'master' in '/home/es/.rally/benchmarks/tracks/default' for distribution version ''.
2017-04-19 09:49:48,825 rally.track INFO Reading track file /home/es/.rally/benchmarks/tracks/default/pmc/track.json.
2017-04-19 09:49:48,829 rally.track INFO Final rendered track for '/home/es/.rally/benchmarks/tracks/default/pmc/track.json': {
  "short-description": "Full text benchmark containing 574.199 papers from PMC",
  "description": "This test indexes 574.199 papers from PMC (total 23.2 GB json) using 8 client threads and 500 docs per bulk request against Elasticsearch",
  "data-url": "http://benchmarks.elasticsearch.org.s3.amazonaws.com/corpora/pmc",
  "#COMMENT": "DEPRECATED: The meta-properties below will stay for a while (for backwards compatibility). Please specify them on top-level for your own tracks",
  "meta": {
    "short-description": "Full text benchmark containing 574.199 papers from PMC",
    "description": "This test indexes 574.199 papers from PMC (total 23.2 GB json) using 8 client threads and 500 docs per bulk request against Elasticsearch",
    "data-url": "http://benchmarks.elasticsearch.org.s3.amazonaws.com/corpora/pmc"
  },
  "indices": [
    {
      "name": "pmc",
      "types": [
        {
          "name": "articles",
          "mapping": "mappings.json",
          "documents": "documents.json.bz2",
          "document-count": 574199,
          "compressed-bytes": 5928712141,
          "uncompressed-bytes": 23256051757
        }
      ]
    }
  ],
  "operations": [
    {
      "name": "index-append",
      "operation-type": "index",
      "bulk-size": 500
    },
    {
      "name": "index-update",
      "operation-type": "index",
      "bulk-size": 500,
      "conflicts": "random"
    },
    {
      "name": "force-merge",
      "operation-type": "force-merge"
    },
    {
      "name": "index-stats",
      "operation-type": "index-stats"
    },
    {
      "name": "node-stats",
      "operation-type": "node-stats"
    },
    {
      "name": "default",
      "operation-type": "search",
      "body": {
        "query": {
          "match_all": {}
        }
      }
    },
    {
      "name": "term",
      "operation-type": "search",
      "body": {
        "query": {
          "term": {
            "body": "physician"
          }
        }
      }
    },
    {
      "name": "phrase",
      "operation-type": "search",
      "body": {
        "query": {
          "match_phrase": {
            "body": "newspaper coverage"
          }
        }
      }
    },
    {
      "name": "articles_monthly_agg_uncached",
      "operation-type": "search",
      "cache": false,
      "body": {
        "size": 0,
        "aggs": {
          "articles_over_time": {
            "date_histogram": {
              "field": "timestamp",
              "interval": "month"
            }
          }
        }
      }
    },
    {
      "name": "articles_monthly_agg_cached",
      "operation-type": "search",
      "cache": true,
      "body": {
        "size": 0,
        "aggs": {
          "articles_over_time": {
            "date_histogram": {
              "field": "timestamp",
              "interval": "month"
            }
          }
        }
      }
    },
    {
      "name": "scroll",
      "operation-type": "search",
      "pages": 25,
      "results-per-page": 1000,
      "body": {
        "query": {
          "match_all": {}
        }
      }
    }
  ],
  "challenges": [
    {
      "name": "append-no-conflicts",
      "description": "Indexes the whole document corpus using Elasticsearch default settings. We only adjust the number of replicas as we benchmark a single node cluster and Rally will only start the benchmark if the cluster turns green. Document ids are unique so all index operations are append only. After that a couple of queries are run.",
      "default": true,
      "index-settings": {
        "index.number_of_replicas": 0
      },
      "schedule": [
        {
          "operation": "index-append",
          "warmup-time-period": 240,
          "clients": 8
        },
        {
          "operation": "force-merge",
          "clients": 1
        },
        {
          "operation": "index-stats",
          "clients": 1,
          "warmup-iterations": 100,
          "iterations": 100,
          "target-throughput": 50
        },
        {
          "operation": "node-stats",
          "clients": 1,
          "warmup-iterations": 100,
          "iterations": 100,
          "target-throughput": 50
        },
        {
          "operation": "default",
          "clients": 1,
          "warmup-iterations": 500,
          "iterations": 1000,
          "target-throughput": 20
        },
        {
          "operation": "term",
          "clients": 1,
          "warmup-iterations": 500,
          "iterations": 1000,
          "target-throughput": 20
        },
        {
          "operation": "phrase",
          "clients": 1,
          "warmup-iterations": 500,
          "iterations": 1000,
          "target-throughput": 20
        },
        {
          "operation": "articles_monthly_agg_uncached",
          "clients": 1,
          "warmup-iterations": 500,
          "iterations": 1000,
          "target-throughput": 20
        },
        {
          "operation": "articles_monthly_agg_cached",
          "clients": 1,
          "warmup-iterations": 500,
          "iterations": 1000,
          "target-throughput": 20
        },
        {
          "operation": "scroll",
          "clients": 1,
          "warmup-iterations": 50,
          "iterations": 100,
          "target-throughput": 1
        }
      ]
    },
    {
      "name": "append-no-conflicts-index-only",
      "description": "Indexes the whole document corpus using Elasticsearch default settings. We only adjust the number of replicas as we benchmark a single node cluster and Rally will only start the benchmark if the cluster turns green. Document ids are unique so all index operations are append only.",
      "index-settings": {
        "index.number_of_replicas": 0
      },
      "schedule": [
        {
          "operation": "index-append",
          "warmup-time-period": 240,
          "clients": 8
        },
        {
          "operation": "force-merge",
          "clients": 1
        }
      ]
    },
    {
      "#COMMENT": "Temporary workaround for more realistic benchmarks with two nodes",
      "name": "append-no-conflicts-index-only-1-replica",
      "description": "Indexes the whole document corpus using Elasticsearch default settings. We only adjust the number of replicas as we benchmark a single node cluster and Rally will only start the benchmark if the cluster turns green. Document ids are unique so all index operations are append only.",
      "index-settings": {
        "index.number_of_replicas": 1
      },
      "schedule": [
        {
          "operation": "index-append",
          "warmup-time-period": 240,
          "clients": 8
        },
        {
          "operation": "force-merge",
          "clients": 1
        }
      ]
    },
    {
      "name": "append-fast-no-conflicts",
      "description": "Indexes the whole document corpus using a setup that will lead to a larger indexing throughput than the default settings. Document ids are unique so all index operations are append only.",
      "index-settings": {
        "index.number_of_replicas": 0,
        "index.refresh_interval": "30s",
        "index.number_of_shards": 6,
        "index.translog.flush_threshold_size": "4g"
      },
      "schedule": [
        {
          "operation": "index-append",
          "warmup-time-period": 240,
          "clients": 8
        },
        {
          "operation": "force-merge",
          "clients": 1
        }
      ]
    },
    {
      "name": "append-fast-with-conflicts",
      "description": "Indexes the whole document corpus using a setup that will lead to a larger indexing throughput than the default settings. Rally will produce duplicate ids in 25% of all documents (not configurable) so we can simulate a scenario with appends most of the time and some updates in between.",
      "index-settings": {
        "index.number_of_replicas": 0,
        "index.refresh_interval": "30s",
        "index.number_of_shards": 6,
        "index.translog.flush_threshold_size": "4g"
      },
      "schedule": [
        {
          "operation": "index-update",
          "warmup-time-period": 240,
          "clients": 8
        },
        {
          "operation": "force-merge",
          "clients": 1
        }
      ]
    }
  ]
}

2017-04-19 09:49:48,833 root ERROR Cannot run subcommand [list].
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/esrally/track.py", line 413, in read
    jsonschema.validate(track_spec, self.track_schema)
  File "/usr/local/lib/python3.4/dist-packages/jsonschema/validators.py", line 478, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/usr/local/lib/python3.4/dist-packages/jsonschema/validators.py", line 123, in validate
    raise error
jsonschema.exceptions.ValidationError: 'type' is a required property

Failed validating 'required' in schema['properties']['operations']['items']:
    {'properties': {'bulk-size': {'description': '[Only for type == '
                                                 "'index']: Defines "
                                                 'the bulk size.',
                                  'minimum': 1,
                                  'type': 'integer'},
                    'clients': {'properties': {'compression': {'description': 'Whether '
                                                                              'to '
                                                                              'compress '
                                                                              'requests '
                                                                              'on '
                                                                              'the '
                                                                              'client.',
                                                               'type': 'boolean'},
                                               'count': {'description': 'Number '
                                                                        'of '
                                                                        'clients '
                                                                        'which '
                                                                        'should '
                                                                        'execute '
                                                                        'this '
                                                                        'operation.',
                                                         'maximum': 1024,
                                                         'minimum': 1,
                                                         'type': 'integer'}},
                                'required': ['count'],
                                'type': 'object'},
                    'conflicts': {'description': '[Only for type == '
                                                 "'index']: Type of "
                                                 'index conflicts to '
                                                 'simulate. If not '
                                                 'specified, no '
                                                 'conflicts will be '
                                                 'simulated. Valid '
                                                 'values are: '
                                                 "'sequential' (A "
                                                 'document id is '
                                                 'replaced with a '
                                                 'document id with a '
                                                 'sequentially '
                                                 'increasing id), '
                                                 "'random' (A document "
                                                 'id is replaced with '
                                                 'a document id with a '
                                                 'random other id).',
                                  'enum': ['sequential', 'random'],
                                  'type': 'string'},
                    'force-merge': {'description': '[Only for type == '
                                                   "'index']: Whether "
                                                   'to perform a force '
                                                   'merge after the '
                                                   'index benchmark is '
                                                   'done. It is '
                                                   'recommended to do '
                                                   'a force-merge when '
                                                   'benchmarking '
                                                   'search after '
                                                   'indexing in order '
                                                   'to reduce '
                                                   'run-to-run '
                                                   'variance.',
                                    'type': 'boolean'},
                    'index-settings': {'description': '[Only for type '
                                                      "== 'index']: "
                                                      'Defines the '
                                                      'index settings '
                                                      'of the '
                                                      'benchmark '
                                                      'candidate when '
                                                      'the index is '
                                                      'created.',
                                       'type': 'object'},
                    'iterations': {'description': '[Only for types '
                                                  "'stats', 'search']: "
                                                  'Defines the number '
                                                  'of times to run the '
                                                  'operation.',
                                   'minimum': 1,
                                   'type': 'integer'},
                    'name': {'description': 'A human-readable name of '
                                            'this operation',
                             'type': 'string'},
                    'queries': {'description': '[Only for type '
                                               "'search']: Defines the "
                                               'queries to execute.',
                                'items': {'properties': {'body': {'description': 'The '
                                                                                 'query '
                                                                                 'body.',
                                                                  'type': 'object'},
                                                         'cache': {'description': 'Whether '
                                                                                  'to '
                                                                                  'use '
                                                                                  'the '
                                                                                  'query '
                                                                                  'request '
                                                                                  'cache. '
                                                                                  'By '
                                                                                  'default, '
                                                                                  'Rally '
                                                                                  'will '
                                                                                  'define '
                                                                                  'no '
                                                                                  'value '
                                                                                  'thus '
                                                                                  'the '
                                                                                  'default '
                                                                                  'depends '
                                                                                  'on '
                                                                                  'the '
                                                                                  'benchmark '
                                                                                  'candidate '
                                                                                  'settings '
                                                                                  'and '
                                                                                  'Elasticsearch '
                                                                                  'version.',
                                                                   'type': 'boolean'},
                                                         'index': {'description': 'The '
                                                                                  'index '
                                                                                  'or '
                                                                                  'index '
                                                                                  'pattern '
                                                                                  'against '
                                                                                  'which '
                                                                                  'the '
                                                                                  'query '
                                                                                  'should '
                                                                                  'be '
                                                                                  'executed. '
                                                                                  'This '
                                                                                  'property '
                                                                                  'is '
                                                                                  'only '
                                                                                  'necessary '
                                                                                  'if '
                                                                                  'there '
                                                                                  'is '
                                                                                  'more '
                                                                                  'than '
                                                                                  'one '
                                                                                  'index '
                                                                                  'or '
                                                                                  'the '
                                                                                  'index '
                                                                                  'contains '
                                                                                  'more '
                                                                                  'than '
                                                                                  'one '
                                                                                  'type. '
                                                                                  'Otherwise, '
                                                                                  'Rally '
                                                                                  'will '
                                                                                  'derive '
                                                                                  'the '
                                                                                  'index '
                                                                                  'and '
                                                                                  'type '
                                                                                  'by '
                                                                                  'itself.',
                                                                   'type': 'string'},
                                                         'name': {'description': 'A '
                                                                                 'descriptive '
                                                                                 'name '
                                                                                 'for '
                                                                                 'the '
                                                                                 'query. '
                                                                                 'It '
                                                                                 'is '
                                                                                 'recommended '
                                                                                 'to '
                                                                                 'use '
                                                                                 'short '
                                                                                 'names '
                                                                                 'and '
                                                                                 'to '
                                                                                 'hyphenate '
                                                                                 'parts '
                                                                                 'of '
                                                                                 'the '
                                                                                 'words, '
                                                                                 'e.g. '
                                                                                 "'query-most-recent-docs'. "
                                                                                 'This '
                                                                                 'name '
                                                                                 'can '
                                                                                 'be '
                                                                                 'used '
                                                                                 'to '
                                                                                 'create '
                                                                                 'graphs '
                                                                                 'per '
                                                                                 'query '
                                                                                 'in '
                                                                                 'Kibana.',
                                                                  'type': 'string'},
                                                         'pages': {'description': '[Only '
                                                                                  'for '
                                                                                  'query-type '
                                                                                  "'scroll'] "
                                                                                  'Number '
                                                                                  'of '
                                                                                  'pages '
                                                                                  'to '
                                                                                  'retrieve.',
                                                                   'minimum': 1,
                                                                   'type': 'integer'},
                                                         'query-type': {'description': 'The '
                                                                                       'type '
                                                                                       'of '
                                                                                       'query. '
                                                                                       'Should '
                                                                                       'currently '
                                                                                       'only '
                                                                                       'be '
                                                                                       'set '
                                                                                       'for '
                                                                                       "'scroll' "
                                                                                       'queries '
                                                                                       '(as '
                                                                                       'they '
                                                                                       'require '
                                                                                       'additional '
                                                                                       'properties '
                                                                                       'and '
                                                                                       'also '
                                                                                       'behave '
                                                                                       'differently). '
                                                                                       'If '
                                                                                       'not '
                                                                                       'defined, '
                                                                                       'a '
                                                                                       'request '
                                                                                       'body '
                                                                                       'search '
                                                                                       'will '
                                                                                       'be '
                                                                                       'executed.',
                                                                        'enum': ['scroll'],
                                                                        'type': 'string'},
                                                         'results-per-page': {'description': '[Only '
                                                                                             'for '
                                                                                             'query-type '
                                                                                             "'scroll'] "
                                                                                             'Number '
                                                                                             'of '
                                                                                             'documents '
                                                                                             'to '
                                                                                             'retrieve '
                                                                                             'per '
                                                                                             'page.',
                                                                              'minimum': 1,
                                                                              'type': 'integer'},
                                                         'type': {'description': 'The '
                                                                                 'type '
                                                                                 'against '
                                                                                 'which '
                                                                                 'the '
                                                                                 'query '
                                                                                 'should '
                                                                                 'be '
                                                                                 'executed. '
                                                                                 'This '
                                                                                 'property '
                                                                                 'is '
                                                                                 'only '
                                                                                 'necessary '
                                                                                 'if '
                                                                                 'there '
                                                                                 'is '
                                                                                 'more '
                                                                                 'than '
                                                                                 'one '
                                                                                 'index '
                                                                                 'or '
                                                                                 'the '
                                                                                 'index '
                                                                                 'contains '
                                                                                 'more '
                                                                                 'than '
                                                                                 'one '
                                                                                 'type. '
                                                                                 'Otherwise, '
                                                                                 'Rally '
                                                                                 'will '
                                                                                 'derive '
                                                                                 'the '
                                                                                 'index '
                                                                                 'and '
                                                                                 'type '
                                                                                 'by '
                                                                                 'itself.',
                                                                  'type': 'string'}},
                                          'required': ['name'],
                                          'type': 'object'},
                                'minItems': 1,
                                'type': 'array'},
                    'type': {'description': 'Type of this operation. '
                                            'Possible values are: '
                                            "'index', 'stats', "
                                            "'search'.",
                             'enum': ['index', 'stats', 'search'],
                             'type': 'string'},
                    'warmup-iterations': {'description': '[Only for '
                                                         'types '
                                                         "'stats', "
                                                         "'search']: "
                                                         'Defines the '
                                                         'number of '
                                                         'times to run '
                                                         'the '
                                                         'operation in '
                                                         'order to '
                                                         'warmup the '
                                                         'benchmark '
                                                         'candidate. '
                                                         'Warmup '
                                                         'iterations '
                                                         'will not be '
                                                         'considered '
                                                         'in the '
                                                         'benchmark '
                                                         'result.',
                                          'minimum': 0,
                                          'type': 'integer'}},
     'required': ['name', 'type'],
     'title': 'Operation',
     'type': 'object'}

On instance['operations'][0]:
    {'bulk-size': 500, 'name': 'index-append', 'operation-type': 'index'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/esrally/rally.py", line 331, in dispatch_sub_command
    list(cfg)
  File "/usr/local/lib/python3.4/dist-packages/esrally/rally.py", line 305, in list
    track.list_tracks(cfg)
  File "/usr/local/lib/python3.4/dist-packages/esrally/track.py", line 230, in list_tracks
    tabular_data=[[t.name, t.short_description, ",".join(map(str, t.challenges))] for t in tracks(cfg)],
  File "/usr/local/lib/python3.4/dist-packages/esrally/track.py", line 224, in tracks
    for track_name in repo.track_names(distribution_version)]
  File "/usr/local/lib/python3.4/dist-packages/esrally/track.py", line 224, in <listcomp>
    for track_name in repo.track_names(distribution_version)]
  File "/usr/local/lib/python3.4/dist-packages/esrally/track.py", line 418, in read
    json.dumps(ve.instance, indent=4, sort_keys=True), ve.absolute_path, ve.absolute_schema_path))
esrally.track.TrackSyntaxError: Track 'pmc' is invalid.

Error details: 'type' is a required property
Instance: {
    "bulk-size": 500,
    "name": "index-append",
    "operation-type": "index"
}
Path: deque(['operations', 0])
Schema path: deque(['properties', 'operations', 'items', 'required'])

**Comment by danielmitterdorfer** [comment]
@SamyCoenen Rally 0.3.3 is very old and the track format has changed in the meantime. Can you please upgrade to the latest version by running `pip3 install --upgrade esrally` (`esrally --version` should show `esrally 0.5.3`) and retry?

**Comment by SamyCoenen** [comment]
@danielmitterdorfer I rebuild the container with the Dockerfile which installs the newest esrally with pip and now the error is gone, thank you.
