### ISSUE TITLE
esrally can't connect to elasticsearch when x-pack is enabled 5.3.0

### ISSUE THREAD

**Issue by zqc0512** [elastic/rally#281]
**Rally version** (get with `esrally --version`):
esrally 0.5.3
**Invoked command**:
esrally --pipeline=benchmark-only --target-hosts=11.11.165.61:9200,11.11.165.63:9200,11.11.165.64:9200,11.11.165.65:9200,11.11.165.66:9200,11.11.165.67:9200 --offline

**Configuration file (located in `~/.rally/rally.ini`))**:
[es@8 ~]$ more .rally/rally.ini 
[meta]
config.version = 8

[system]
env.name = ESTEST

[node]
root.dir = /home/es/.rally/benchmarks

[source]
local.src.dir = /home/es/.rally/benchmarks/src
remote.repo.url = https://github.com/elastic/elasticsearch.git

[build]
gradle.bin = /usr/gradle-2.13/bin/gradle

[runtime]
java8.home = /usr/java/jdk1.8.0_121/jre

[benchmarks]
local.dataset.cache = ${node:root.dir}/data

[reporting]
datastore.type = elasticsearch
datastore.host = 11.11.165.61:9200
datastore.port = 9200
datastore.secure = False
datastore.user = elastic
datastore.password = changeme

[tracks]
default.url = https://github.com/elastic/rally-tracks

[defaults]
preserve_benchmark_candidate = False

[es@8 ~]$ 
**JVM version**:
[es@8 ~]$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
[es@8 ~]$ 

**OS version**:
 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:
[ERROR] Cannot race. TransportError(401, 'security_exception', 'missing authentication token for REST request [/]')

**Describe the feature**:
[ERROR] Cannot race. TransportError(401, 'security_exception', 'missing authentication token for REST request [/]')

**Comment by danielmitterdorfer** [comment]
This is not an issue in Rally. As such, please (a) do not use the Github ticket and (b) do not post a question on Discuss *and* raise an issue at the same time.

**Comment by danielmitterdorfer** [comment]
For reference: This is the relevant Discuss thread: https://discuss.elastic.co/t/rally-cant-connect-to-the-remote-cluster-when-install-x-pack-and-is-enabled/84891
