### ISSUE TITLE
Provide the option to get number of hits when running search benchmark

### ISSUE THREAD

**Issue by mesfinmulugeta** [elastic/rally#295]
Currently Rally provides "number of hits" only when running scroll queries (where you provide values to the `pages` and `result-per-page` properties in the search benchmark). "Number of hits" isn't provided when running non-scroll queries. "Number of hits" is a very useful result that we can use to validate the result. To just give one example, when performing benchmarking using Rally, I ran into issues where the error rate was 0% in the benchmark result, but there was issue on my query benchmark. If I had the number of hits information in the result, I could have immediately identified that there was issue with my query. 

See also https://discuss.elastic.co/t/number-of-hits-when-running-non-scroll-queries/91660

**Comment by cdahlqvist** [comment]
It would be good if this could be enabled/disabled, e.g. in a similar way to how detailed stats are handled for bulk requests.

**Comment by danielmitterdorfer** [comment]
Contrary to bulk requests determining the number of hits has practically zero overhead (I've benchmarked it). It's only reading a single number from a Python dict. Hence I'd just include it per default for the moment. 

If we should gather more meta-data in the future, I totally agree that we should not enable it by default then and allow users to provide a flag in the track whether they want detailed statistics or not.
