### ISSUE TITLE
how can i store the report data  in a  remote ES-cluster？

### ISSUE THREAD

**Issue by huangfuyixiao** [elastic/rally#297]
**Rally version** (get with `esrally --version`):

**Invoked command**:

**Configuration file (located in `~/.rally/rally.ini`))**:

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by huangfuyixiao** [comment]
how can i store the report data in a remote ES-cluster？ then i can use kibana to show the report，i try to edit the file ：/.rally/rally.ini，i make the [reporting] datastore.type = in-memory datastore.host = myEs-clusterIp datastore.port = 9200 ，but i cant get the report data in the ES-cluster

**Comment by huangfuyixiao** [comment]
by  the way  ，i use  rally to test the remote  ES-cluster，i want to store the report data to it too

**Comment by huangfuyixiao** [comment]
how can i store the report data in a remote ES-cluster？then i can use kibana to show the report，i try to edit the file ：/.rally/rally.ini，i make the [reporting] datastore.type = in-memory datastore.host = myEs-clusterIp datastore.port = 9200 ，but i cant get the report data in the ES-cluster

**Comment by danielmitterdorfer** [comment]
Hi @huangfuyixiao, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Rally forum](https://discuss.elastic.co/c/elasticsearch/rally) instead. Thank you!
