### ISSUE TITLE
I use es with searchguard  how to connect to es with esrally

### ISSUE THREAD

**Issue by zqc0512** [elastic/rally#303]
I use es with searchguard  how to connect to es with esrally
need use and pass auth. also use **--client-options="basic_auth_user:'admin',basic_auth_password:'admin'"**?

thanks.

**Rally version** (get with `esrally --version`):

**Invoked command**:

**Configuration file (located in `~/.rally/rally.ini`))**:

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by danielmitterdorfer** [comment]
Hi @zqc0512, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Rally forum](https://discuss.elastic.co/c/elasticsearch/rally) instead. Thank you!
