### ISSUE TITLE
Add support for non-compress documents.json file

### ISSUE THREAD

**Issue by shaharmor** [elastic/rally#305]
**Describe the feature**:
Right now rally has to decompress the documents.json file on every run.
If the file is already decompressed (Or was decompressed once before), it just takes tons of time for a task that is not needed and gives no extra info.

There are two options:
1. give rally a raw documents.json file
2. make rally only decompress the compressed file once if the size/hash of the decompressed file is as expected already.

**Comment by danielmitterdorfer** [comment]
What you're describing should not happen. Are you using a standard track or did you create your own? 

Can you please share the following information?

* Output of `esrally --version`
* How you have invoked Rally (i.e. the command line arguments)
* In case you have created your own track, the header section of the track (see below for an example)
* The output of `ls -l ~/.rally/benchmark/data/NAME_OF_YOUR_TRACK`

Here is an example of what I mean by "header section":

```json
  "short-description": "Standard track in Rally (11.4M POIs from Geonames)",
  "description": "This track indexes 11.4M documents (POIs from Geonames) using 8 client threads and 5000 docs per bulk request against Elasticsearch",
  "data-url": "http://benchmarks.elasticsearch.org.s3.amazonaws.com/corpora/geonames",
  "indices": [
    {
      "name": "geonames",
      "types": [
        {
          "name": "type",
          "mapping": "mappings.json",
          "documents": "documents-2.json.bz2",
          "document-count": 11396505,
          "compressed-bytes": 264698741,
          "uncompressed-bytes": 3547614383
        }
      ]
    }
  ]
```

**Comment by shaharmor** [comment]
My bad, not sure why it happened but its not happening again. Sorry

**Comment by danielmitterdorfer** [comment]
Thanks for the feedback @shaharmor. Good to hear it's working now.

**Comment by shaharmor** [comment]
@danielmitterdorfer So I just gave it another shot and it really seems that you can't run on uncompressed data

**Comment by danielmitterdorfer** [comment]
> you can't run on uncompressed data

I assume that you have created your own track but did not create a compressed archive of your document data? If you've created your own track, then I'd still be interested in 

* the "header section" of your track (see above)
* the output of `ls -l ~/.rally/benchmark/data/NAME_OF_YOUR_TRACK`
* Your Rally version `esrally --version`

At the moment Rally has a very specific workflow implemented (see [track loader](https://github.com/elastic/rally/blob/69d1c3c/esrally/track/loader.py#L185-L205)):

1. Check if there is a compressed archive and the size matches. If not, attempt to download it.
2. Check if there is an uncompressed document file and the size matches. If not, decompress the archive.

The idea behind this workflow is that you want to share the data between multiple machines and need a central point where you're hosting it. For *very* simple use cases I can see that it is sufficient to just use the documents file as is and don't bother with the compressed archive.
