### ISSUE TITLE
track error

### ISSUE THREAD

**Issue by CircleLee114** [elastic/rally#306]
**Rally version** (get with `esrally --version`):0.6.2

**Invoked command**:esrally

**Configuration file (located in `~/.rally/rally.ini`))**:

**JVM version**:jdk1.8.0_77

**OS version**:(Red Hat 4.1.2-50)

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.esrally
 2.[INFO] Preparing for race ... [OK]
[INFO] Rally will delete the benchmark candidate after the benchmark
[INFO] Racing on track [geonames], challenge [append-no-conflicts] and car [defa
ults]

[ERROR] Cannot race. ('Could not execute benchmark', TypeError('unorderable type
s: ClusterHealthStatus() >= ClusterHealthStatus()',))

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by danielmitterdorfer** [comment]
Which Python version are you using?

**Comment by CircleLee114** [comment]
The problem has been solved.
I find my Python version is 3.3
I've solved this problem by install Python3.5
