### ISSUE TITLE
Introduce track parameters and allow to override them on the command line

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#310]
We should provide users an ability to override track parameters on the command line without the need to fiddle with tracks which can be [frustrating](https://discuss.elastic.co/t/how-can-change-the-bulk-size-with-geonames/94594).

To ensure results are still reproducible, we should also record the parameters somehow in the metrics store (e.g. as meta-data attached to metrics records).

Tasks:

* [x] Add a possibility to override variables on the command line (either directly or by specifying a file of key-value pairs)
* [x] Enhance metrics meta-data to include all track variables

**Comment by cdahlqvist** [comment]
This is great, as it will make it a lot easier to adjust tracks, e.g. primary shards, #connections, bulk-sizes and durations, to fit environments of different sizes.
