### ISSUE TITLE
Improve formatting of document count in list tracks output

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#327]
When running `esrally list tracks`, Rally only show the number of documents as raw number without any formatting which is hard to read. We should add thousand separators and also show a human readable summary, e.g. instead of showing `11396505`, we could print `11,396,505`.

**Comment by muralimani** [comment]
Daniel, I am interested in providing fix for this improvement. Please let me know the procedure to start on the fix.

**Comment by danielmitterdorfer** [comment]
Hi @muralimani! I am sorry but I missed your comment on this ticket and I just saw it because I went to this ticket from a PR that has already been opened. If you are interested in contributing in general, another issue that might be worthwhile is #382. We also have a [contribution guide](https://github.com/elastic/rally/blob/master/CONTRIBUTING.md) available in this repository.
