### ISSUE TITLE
Don't require git

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#339]
As Rally allows recently to define tracks as simple files there is no hard requirement that git is installed (but obviously usage is restricted to Rally as load generator with custom tracks).

**Comment by lukas-vlcek** [comment]
In similar fashion, can we also say **gradle** is not a hard requirement if `--distribution-version` is used?

**Comment by danielmitterdorfer** [comment]
Gradle is no hard requirement already. Rally will check whether it's present and then tell you that you can only use `--distribution-version`.
