### ISSUE TITLE
Add ability to restore from a snapshot

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#341]
Currently we always need to bulk-index data to get data into Elasticsearch but sometimes it would be better to just provide a snapshot and use that.

## Amended ticket with more information

_Amended on: 20191010_

In this ticket we want to tackle two things and implement two runners:

1. Register a repository

    Needs to support all settings per repository [type](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html). For cloud based types (e.g. `azure`, `gcs`, `s3`) the important ones are:
    - `bucket`
    - `base_path`
    - `client`
    - `max_snapshot_bytes_per_sec`
    - `max_restore_bytes_per_sec`
    - `readonly`

2. Restore snapshot

    This runner will [restore](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#restore-snapshot) from any registered repository which may be specified with 1.
    Needs to support specifying the body of the request where things like `include_global_state` can be defined.

    Implementation details:
        1. Would be ideal if all kinds of retrying could be disabled for the elasticsearch-py call
        2. Would make sense to have runner level user specified absolute timeout? I am thinking of this in case it's hard to find via subsequent ES API calls if there was a problem with restoration.
        3. After the initial restore call, should monitor progress and return when done. A good API to do this is `_cat/recovery?v\&format=json\&filter_path=bytes_percent`
        4. Progress is optional but nice to have (can be tackled after https://github.com/elastic/rally/pull/789 is in)

**Comment by k3v8ns** [comment]
When this feature be supported?
