### ISSUE TITLE
Elasticsearch Version Supported with Rally

### ISSUE THREAD

**Issue by debraj-manna** [elastic/rally#342]
I posted this in -

- [Stackoverflow](https://stackoverflow.com/questions/47049447/elasticsearch-version-supported-with-rally)
- [Elasticsearch Forum](https://discuss.elastic.co/t/elasticsearch-version-supported-with-rally/105983)

But I did not get any response in both the places. 

So posting this as an issue to to update the doc with the minimum elasticsearch version supported with Rally. I could not find any mention about the elasticsearch version in the docs.

**Comment by danielmitterdorfer** [comment]
> I did not get any response in both the places.

Sometimes maintainers also go on vacation. ;)

I've posted answers to SO and the Discuss forum.

**Comment by debraj-manna** [comment]
Thanks @danielmitterdorfer for replying. 

Can we add this information in the Rally docs as well?

**Comment by danielmitterdorfer** [comment]
You're welcome. I've added more info in fe6b9816628e49bb2b1b7b994c263834270b0376.
