### ISSUE TITLE
If python is required then python-dev should be as well

### ISSUE THREAD

**Issue by lukas-vlcek** [elastic/rally#343]
I was testing rally on an Linux machine and I hit the following error:
```
$ ./rally configure
Auto-updating Rally from origin
psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1
```
It turns out that I was missing python-dev package. Installing it like `yum install python3-devel.x86_64` fixed the issue. May be rally can check for this in advance and not run into error (which does not yield very informative message).

**Comment by danielmitterdorfer** [comment]
Your observation is correct and this is also covered [in the documentation](http://esrally.readthedocs.io/en/stable/developing.html#installation-instructions-for-development):

> If you get errors during installation, it is probably due to the installation of psutil which we use to gather system metrics like CPU utilization. Please check the installation instructions of psutil in this case. Keep in mind that Rally is based on Python 3 and you need to install the Python 3 header files instead of the Python 2 header files on Linux.

You run into this problem while `psutil` is installed which requires Python headers. While it may be possible to check this, I think the better option is to improve the documentation and provide concrete installation commands for all dependencies (Python + dev package) for major distributions.
