### ISSUE TITLE
Allow to use an ES distribution for plugins that are built separately

### ISSUE THREAD

**Issue by dadoonet** [elastic/rally#345]
**version**: Rally 0.7.4

I'd like to use Rally to benchmark a plugin I'm writing. Note that I'm not doing any modification in elasticsearch itself.

So here is what I need:

* Define the version I need for elasticsearch. `--distribution-version=6.0.0-rc2` is the way to go
* Define my plugin repository in `rally.ini`:

```ini
plugin.foo.remote.repo.url = file://path/to/foo/
plugin.foo.src.subdir = .
plugin.foo.build.task = assemble
plugin.foo.build.artifact.subdir = build/distributions
```

* Launch rally with my plugin with: 

```sh
esrally --revision="foo:master" --elasticsearch-plugins="foo" --distribution-version=6.0.0-rc2
```

this is failing with Rally 0.7.4

**Comment by danielmitterdorfer** [comment]
This was an intentional decision to keep the initial implementation simpler but I agree that it would be nice to have this working.

As a workaround, you can specify the respective git tag so something along these lines should work:

```
esrally --revision="elasticsearch:6.0.0-rc2,foo:master" --elasticsearch-plugins="foo"
```

**Comment by danielmitterdorfer** [comment]
With the next release, Rally will allow to install a plugin from sources into a released version of ES, e.g.:

```
esrally --revision="foo:12aefe3" --elasticsearch-plugins="foo" --distribution-version="6.0.0"
```

will fetch revision `12aefe3` of plugin "foo", build it and install it into an Elasticsearch 6.0.0 node.
