### ISSUE TITLE
Run In Kubernetes

### ISSUE THREAD

**Issue by gdmello** [elastic/rally#355]
**Describe the feature**:
Would like to be able to deploy and run rally in a kubernetes cluster.
I have set this up [here](https://github.com/gdmello/elasticsearch-rally). If there is interest for this feature, I could submit a PR.

**Comment by danielmitterdorfer** [comment]
Thanks for raising this! I am not really familiar with Kubernetes but to me it seems more sense to keep this in a separate repo (similar to the [Kubernetes Charts repo](https://github.com/kubernetes/charts))?

However, I think it would be a good idea to add your repo to the Rally docs so other users that want to run Rally also in Kubernetes know about it? What do you think?

**Comment by gdmello** [comment]
@danielmitterdorfer - I'll look into adding this to the kubernetes charts repo. Meanwhile, I'll open a PR to add this to the Rally docs. Good suggestion!

**Comment by danielmitterdorfer** [comment]
Sounds good! IMHO a good place would be in the [installation instructions](https://github.com/elastic/rally/blob/master/docs/install.rst).

**Comment by gdmello** [comment]
@danielmitterdorfer - done! in #373 373

**Comment by danielmitterdorfer** [comment]
Thanks! I've added a few review comments there.
