### ISSUE TITLE
Error run "esrally configure" faulthandler has no attribute 'register'

### ISSUE THREAD

**Issue by zhengcongyin** [elastic/rally#378]
**Rally version** (get with `esrally --version`):

**Invoked command**:

**Configuration file (located in `~/.rally/rally.ini`))**:

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Download esrally via pip
 2. Successfully install it
 3. Run "esrally configure"

**Provide logs (if relevant)**:

**Describe the feature**:
After successfully installing esrally, try to run esrally configure It shows an error message ("module faulthandler has no attribute register")

**Comment by danielmitterdorfer** [comment]
This sounds like a serious problem with the Python distribution. Can you please share more details about your environment?

* What's the Rally version? (`esrally --version`)
* What's your Python version? (`python3 -c "import sys ; print(sys.implementation)"`)

**Comment by zhengcongyin** [comment]
Thanks for your prompt reply.

python version: 3.7
esrally version: 0.8.1

I run it on MacOS. Now it shows an error message:  "stdarg.h" file not found.

Thanks for your attention.

**Comment by danielmitterdorfer** [comment]
These are very odd errors. Also, Python 3.7 is not yet released - it's only available as development release (according to https://docs.python.org/3.7/, currently 3.7.0a3). 

Can you please try with one of Python 3.4.x, 3.5.x or 3.6.x? These are also the versions that we regularly test in CI.

**Comment by danielmitterdorfer** [comment]
Closing due to lack of feedback. Please feel free to reopen if new info is available.
