### ISSUE TITLE
Add proxy support for benchmarking

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#382]
While we allow to set a proxy server for downloading artifacts, the load driver does not allow to use a proxy server. Hence, we should detect presence of the `http_proxy` variable and use the proxy server for benchmarking as well.

Implementation hints: urrlib3 defines a [ProxyManager](http://urllib3.readthedocs.io/en/latest/advanced-usage.html#proxies) which we can probably leverage in `EsClientFactory` which is responsible for creating the Elasticsearch client in the load test driver.

**Comment by zqc0512** [comment]
can give it in 0.8.2? thank so.
i use this test es cloud .
@danielmitterdorfer

**Comment by danielmitterdorfer** [comment]
The next release will probably be 0.9.0 and this release is probably already big enough. I will look into it but I cannot yet make promises about a targeted release. Btw, pull requests are always an option. ;)

**Comment by zqc0512** [comment]
thanks.  wating for you :)

**Comment by muralimani** [comment]
Daniel, I shall look into this issue. If no one has picked up the issue yet.

**Comment by danielmitterdorfer** [comment]
Sure, please go ahead!

**Comment by muralimani** [comment]
Daniel, i am setting up the environment on Linux. Do you have any dev environment which i can re-use?

**Comment by danielmitterdorfer** [comment]
I'm not sure what you are referring to? We have instructions how to setup your dev environment in https://esrally.readthedocs.io/en/stable/developing.html - are you missing something from these instructions?

**Comment by danielmitterdorfer** [comment]
We currently have no intention to support this in Rally. Benchmarking with intermediate proxies is also tricky because users need to pay extra attention not to introduce accidental bottlenecks. When we reconsider to support this in the future we can reopen the issue but I'm closing it for now to indicate that will not work on this for the foreseeable future.
