### ISSUE TITLE
install rally from  esrally-dist-0.8.1.tar.gz and benchmarking an existing cluster

### ISSUE THREAD

**Issue by wuyunfeng** [elastic/rally#385]
I want to know after download esrally-dist-0.8.1.tar.gz, run the install.sh, wheather can run esrally, in my enviroments nothings happen...
I need benchmarking an existing cluster,  and just only use the esrally, Is it OK?

**Comment by danielmitterdorfer** [comment]
Hi @wuyunfeng, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Rally forum](https://discuss.elastic.co/c/elasticsearch/rally) instead. Thank you!

**Comment by wuyunfeng** [comment]
OK, @danielmitterdorfer . thanks
