### ISSUE TITLE
Feature-Request:  Allow user to configure index names for rally-resusts, rally-races and rally-results

### ISSUE THREAD

**Issue by hatdropper1977** [elastic/rally#401]
**Describe the feature**:
My customer wanted to see multiple Rally tests run in order to gain confidence via consistent results.

I solved this problem by creating three independent Rally nodes, each which sent their results to a common, dedocated results database.

I separated the index names for each server's results by by configuring lines 700, 1254 and 1335 in [metrics.py](https://github.com/elastic/rally/blob/master/esrally/metrics.py).

It would be nice if I could set an index prefix for the indices in rally.ini.

**Comment by danielmitterdorfer** [comment]
You can solve this by choosing a different [environment name](http://esrally.readthedocs.io/en/stable/configuration.html#configuration-options) when configuring Rally. 

This is reflected in `~/.rally/rally.ini` in the property `env.name`. This name will be attached to each metrics document in the metrics store as `environment`. So you just need to add `environment:"my-env-name"` in your query and you're able to separate different environments.

**Comment by hatdropper1977** [comment]
That works, thank you.
