### ISSUE TITLE
Cannot report to ES cluster with self-signed certificate or in-house certificate authority

### ISSUE THREAD

**Issue by kesslerm** [elastic/rally#413]
The metrics module fails to connect to the Elasticsearch metrics store, if secure transport is used and the server has a self signed certificate or a certificate signed by a certificate authority that's not in the certificate store provided by `certifi`.

**Comment by danielmitterdorfer** [comment]
We probably need to enhance the metrics store configuration to allow passing these options. I would not go so far as to ask the user for a custom certificate in Rally's setup routine but we should probably allow to configure a custom certificate directly in the config file.
