### ISSUE TITLE
Enhance support for _routing parameters

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/rally#445]
[This thread on the Discuss forum](https://discuss.elastic.co/t/routing-in-search-operation/125103) brought up the question of support in Rally for queries. Now that it is easier to use Rally against existing indices, it would be very useful to extend the standard search/query runner to support the specification of `_routing` parameters. It would be useful if this could be specified as a single value, e.g. through a custom parameter source, or taken randomly from an array if that is specified.

As an extension to this, it would also be nice if it was possible to define a `_routing` parameter when indexing data through the bulk interface as well. Here it would be useful to either directly specify a value or allow the routing to be based on a specific field in the documents.

**Comment by danielmitterdorfer** [comment]
We currently have no intention to work on this feature but we might want to revisit this in the future if we'll leverage it. I'm closing the issue to indicate we'll not work on this for the forseeable future.
