### ISSUE TITLE
Add progress bar while uncompressing document corpus archives

### ISSUE THREAD

**Issue by dliappis** [elastic/rally#482]
This is a rather low priority item, but given that some corpus document archives are really large in our standard tracks (e.g. [http_logs](https://github.com/elastic/rally-tracks/blob/master/http_logs/track.json#L93-L97)) it would be beneficial to display a progress bar with Rally while it uncompresses the corpus files.

**Comment by dliappis** [comment]
While #947 doesn't solve this issue, it does mitigate it significantly by utilizing all available cores and making the wait much shorter on multicore load drivers.

Additionally as the traditional Python bz2 library will be used as fallback, supporting progress for both implementations will be fiddly and complex.

WDYT @danielmitterdorfer given other important areas for improvement and the age of this ticket, should we just close it?

**Comment by danielmitterdorfer** [comment]
Agreed, let's close this.
