### ISSUE TITLE
Improve release process

### ISSUE THREAD

**Issue by dliappis** [elastic/rally#483]
This is a small but annoying issue.

The current release workflow and script (`./release.sh`) rely on certain pip3 packages and is flaky while using a virtualenv.

In ticket we'll explore if there's a simpler and more reliable way to perform this.

We will start by experimenting with adding a `Makefile` target that allows us to `./release.sh` inside a Docker environment with all prerequisites satisfied.

**Comment by danielmitterdorfer** [comment]
@dliappis In `make install` we setup all required dependencies that are needed to do a release so I think we've solved this by now?

**Comment by dliappis** [comment]
Makes sense yes.
