### ISSUE TITLE
Detect node failures

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#527]
When a node dies for any reason Rally does not detect this and the benchmark appears to hang. This is especially problematic in a multi-node benchmark where there is still some sort of connectivity because not all nodes are gone.

We could solve this by checking periodically whether the node's process is still present and bail if not.

**Comment by cdahlqvist** [comment]
Should the Python client not handle this?

**Comment by danielmitterdorfer** [comment]
I think the Python client would notice that it cannot connect to a node but it would then just avoid connecting to that one. However, we want to be a little bit stricter in our benchmarks and fail if a node dies while a benchmark is executing. To be clear: This does not affect the case when you use Rally only as a load generator (benchmark-only) but rather when Rally itself spins up the cluster.

**Comment by danielmitterdorfer** [comment]
As Rally launches Elasticsearch now as a daemon and is not a parent process anymore (#719) and also our mid-term plan is to have dedicated subcommands for node provisioning, starting and stopping (see #697) this issue becomes irrelevant thus closing.
