### ISSUE TITLE
Support for rollover in the Rally metrics store

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/rally#531]
When running certain types of indexing heavy benchmarks, e.g. the [rally-eventdata-track](https://github.com/elastic/rally-eventdata-track), a lot of metrics can end up being generated in a short period of time. This can lead to very large `rally-metrics-*` indices. For these indices, it is hard to have them covering a fixed time period as it is easy to end up with too many or too few indices/shards.

It would be great if the `rally-metrics-*` indices would instead use the rollover index APIs to get a consistent and suitable size.

**Comment by danielmitterdorfer** [comment]
Makes sense. We'll target this for the 1.x series of Rally.

**Comment by danielmitterdorfer** [comment]
Meanwhile, Elasticsearch has also introduced ILM which we should use instead. Therefore I'll close this issue. Once we drop support for older metrics store versions we can think of introducing ILM (see also https://github.com/elastic/rally/issues/653).
