### ISSUE TITLE
TLS Client certificate verification is not working

### ISSUE THREAD

**Issue by dliappis** [elastic/rally#550]
This bug is the result of the discussion in https://discuss.elastic.co/t/esrally-elastic-mutual-tls/143515/13

#### Description

- Elasticsearch using xpack:security configured with `xpack.security.http.ssl.enabled: true` and `xpack.security.http.ssl.client_authentication: required`.
- Rally executed specifying client-options like:
    ```
    --client-options="use_ssl:true,verify_certs:true,ca_certs:'ca.crt',client_cert:'client.crt',client_key:'client.key',basic_auth_user:username,basic_auth_password:password"
    ```
- Returns the following error:
    ```
    elasticsearch.exceptions.SSLError: ConnectionError([SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:645)) caused by: SSLError([SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:645))
    ].
    ```
- Equivalent curl command works:
    ```
    curl --cacert ca.crt --cert client.crt --key client.key https://username:password@127.0.0.1:9200
    ```

#### Reproduction steps

https://gist.github.com/dliappis/97d013ab6e0e3250fdd6cbfba8e58a5c

The gist also contains a patch fixing this issue.

**Comment by rljie** [comment]
[ERROR] Cannot race. Error in race control (('Could not connect to your Elasticsearch metrics store. Please check that it is running on host [https://12.19.24.92] at port [9200] or fix the configuration in [/root/.rally/rally.ini].', None))

**Comment by rljie** [comment]
我的ES是7.2.0版本，使用了xpack加密，使用下面这条命令执行esrally，报上面这个错误！
esrally --advanced-config  --target-hosts=12.19.24.92:9200  --pipeline=benchmark-only --client-options="basic_auth_user:'elastic',basic_auth_password:'123456',use_ssl:true,verify_certs:true,ca_certs:'/root/config/client-ca.cer',client_cert:'/root/config/client.cer',client_key:'/root/config/client.key',timeout:120"  --test-mode

**Comment by dliappis** [comment]
@rljie This appears to be a user question **and** this is a closed issue.

If you have a question, could you please go to the [Rally forum](https://discuss.elastic.co/c/elasticsearch/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

**Comment by rljie** [comment]
> @rljie这似乎是一个用户问题**，**这是一个封闭的问题。
> 
> 如果您有疑问，请转到[拉力赛论坛](https://discuss.elastic.co/c/elasticsearch/rally)。如果你能在那里停留，我们会很感激。这允许我们使用GitHub来验证错误报告，功能请求和拉取请求。

用户问题吗？我感觉像是证书问题耶
