### ISSUE TITLE
Don't log the completely rendered track directly in the log file

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#554]
Rally is currently logging the rendered track for debugging purposes in its log file. However, this inconvenient for several reasons:

* It increases the size of the log significantly
* The output is intermingled with other log statements
* For very large tracks it might cause issues with the actor framework as logs are sent to a central process first.

Therefore we should write the rendered track rather to a (temporary?) file and only reference the path to the file in Rally's log.

**Comment by cdahlqvist** [comment]
It would be great if we could output the configuration file after it has been processed by Jinja2, but before Rally has tried to parse the JSON as this would make it a lot easier to find issues in the configuration.
