### ISSUE TITLE
add fio benchmark for the SSD used by es

### ISSUE THREAD

**Issue by tclh123** [elastic/rally#577]
I run the rally pmc track against my new 3 node es cluster, but the throughput seems too low. I saw the official benchmark use the `SSD: Samsung MZ7LN512HMJP-00000` (
https://elasticsearch-benchmarks.elastic.co/ ). I want to know if this difference is because the SSD performance. So I think it will be good if you can provide a fio benchmark.

```
|   All |                       Min Throughput |                  index-append |      580.62 |  docs/s |
|   All |                    Median Throughput |                  index-append |      625.59 |  docs/s |
|   All |                       Max Throughput |                  index-append |      639.55 |  docs/s |
```

**Comment by dliappis** [comment]
Thanks for the suggestion @tclh123 . Rally is primarily meant to be used as a tool for benchmarking Elasticsearch and not the underlying system itself, but we'll discuss a bit more about whether something like that makes sense.

I'd like to point out that there a few more factors that can influence the performance of the benchmarks, apart from the pure SSD performance.

Most of them, have been covered in @danielmitterdorfer 's [Seven tips for Better Elasticsearch Benchmarks[(https://www.elastic.co/blog/seven-tips-for-better-elasticsearch-benchmarks) blog article so this is a highly recommended read.

In general when throughput seems low it is important to use any of the standard methodologies to evaluate where's the bottleneck. One of the most used ones is Brendan Gregg's [USE method](http://www.brendangregg.com/usemethod.html) and you can find some [useful checklists](http://www.brendangregg.com/blog/2016-05-04/srecon2016-perf-checklists-for-sres.html) he's been presenting to quickly triage CPU / IO / Network bottlenecks.

For example you can see in this [discuss topic](https://discuss.elastic.co/t/elasticsearch-benchmarking-docs-s/149027/7) that you need to be careful about the saturation levels on the network side as well, especially with multi node clusters and 1GbE interfaces.

Also many generations of SSDs get adverse performance if they haven't been trimmed; check the [is your Elasticsearch TRIMmed](https://www.elastic.co/blog/is-your-elasticsearch-trimmed) blog article for more information.

**Comment by danielmitterdorfer** [comment]
Thanks for your idea but at this point this is not something we want to pursue. We aim to state as much as possible about our environment but we will not provide additional hardware stress tests.

**Comment by tclh123** [comment]
@dliappis @danielmitterdorfer Thank you.

I've checked the disk performance about those 2 SSD. It seems the IOPS of the Samsung SSD is much better than the Intel SSD I used. Any suggestions?

- Samsung MZ7LN512HMJP-00000

Ran. Read
97 K IOPS (4KB, QD32)
Ran. Write
88 K IOPS (4KB, QD32)

https://www.cnet.com/products/samsung-pm871a-mz7ln512hmjp-solid-state-drive-512-gb-sata-6gb-s/specs/
https://www.samsung.com/semiconductor/ssd/client-ssd/MZ7LN512HAJQ/
https://www.samsung.com/uk/memory-storage/850-pro-sata-3-2-5-inch-ssd/MZ-7KE512BW/ (can't find MZ7LN512 page)

- Intel SSDSC2BB800G6 DC S3510 800GB 2.5IN

Random Read (100% Span)
67000 IOPS
Random Write (100% Span)
15300 IOPS

https://www.cnet.com/products/intel-ssd-dc-s3510-series-800gb/specs/
https://ark.intel.com/products/86199/Intel-SSD-DC-S3510-Series-800GB-2_5in-SATA-6Gbs-16nm-MLC
