### ISSUE TITLE
Does not run in digital ocean droplet any ideas?

### ISSUE THREAD

**Issue by rifaterdemsahin** [elastic/rally#585]
root@ubuntu-s-4vcpu-8gb-lon1-01:~/Python-3.4.0# esrally --distribution-version=6.0.0

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

[INFO] Preparing for race ...
[ERROR] Cannot race. ('Cannot download Elasticsearch distribution from [https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-6.0.0.tar.gz]. Please check that the specified version [6.0.0] is correct.', None)
        Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/esrally/mechanic/supplier.py", line 302, in fetch
    net.download(download_url, distribution_path, progress_indicator=progress)
  File "/usr/local/lib/python3.6/dist-packages/esrally/utils/net.py", line 61, in download
    raise urllib.error.HTTPError(url, r.status, "", None, None)
urllib.error.HTTPError: HTTP Error 404:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/esrally/mechanic/mechanic.py", line 546, in receiveMsg_StartNodes
    nodes = self.mechanic.start_engine()
  File "/usr/local/lib/python3.6/dist-packages/esrally/mechanic/mechanic.py", line 678, in start_engine
    binaries = self.supply()
  File "/usr/local/lib/python3.6/dist-packages/esrally/mechanic/supplier.py", line 167, in __call__
    supplier.fetch()
  File "/usr/local/lib/python3.6/dist-packages/esrally/mechanic/supplier.py", line 308, in fetch
    "version [%s] is correct." % (download_url, self.version))
esrally.exceptions.SystemSetupError: ('Cannot download Elasticsearch distribution from [https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-6.0.0.tar.gz]. Please check that the specified version [6.0.0] is correct.', None)

Getting further help:
*********************
* Check the log files in /root/.rally/logs for errors.
* Read the documentation at https://esrally.readthedocs.io/en/1.0.1/
* Ask a question on the forum at https://discuss.elastic.co/c/elasticsearch/rally
* Raise an issue at https://github.com/elastic/rally/issues and include the log files in /root/.rally/logs.

-------------------------------
[INFO] FAILURE (took 3 seconds)
-------------------------------
root@ubuntu-s-4vcpu-8gb-lon1-01:~/Python-3.4.0#

**Comment by danielmitterdorfer** [comment]
Thanks for your interest in Rally. This was a configuration issue and it should work now if you retry again. For future reference, we'd like to direct questions to the [Rally forum](https://discuss.elastic.co/c/elasticsearch/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

**Comment by KaranTrivedi** [comment]
I just pip installed esrally and got this error with 

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)
