### ISSUE TITLE
Improve error message when no index has been specified in search operation with multiple indices

### ISSUE THREAD

**Issue by dliappis** [elastic/rally#597]
As discussed in [this discuss topic](https://discuss.elastic.co/t/error-cannot-race-error-in-track-preparator-index-is-mandatory-none/156013), when having multiple indices in the track, if user omits `index` in the `search` operation, the following error message gets produced:

`[ERROR] Cannot race. Error in track preparator (("'index' is mandatory", None))`

This doesn't help identify which operation required the index property and needs to be improved.

**Comment by emilmirzayev** [comment]
I guess, this was the [discussion topic](https://discuss.elastic.co/t/error-cannot-race-error-in-track-preparator-index-is-mandatory-none/156013) you meant. It was my question.

**Comment by dliappis** [comment]
Ugh thanks @emilmirzayev, I updated the link.
