### ISSUE TITLE
index-append's "error rate" counts failed shard bulk operations instead of record

### ISSUE THREAD

**Issue by imotov** [elastic/rally#618]
After executing a track with 60mln documents I got the report from rally with error rate of 14.68% after examination of the index, it looks like only 8701 records failed, that would roughly correspond to the number of the failed shard requests - 60,000,000 * 0.1468 / 1000 = 8,808  (I have 5 shards and the bulk size is 5000, which means from each shard bulk size is approximately 1000).

To reproduce:
- take any track with test set of 1k documents  
- modify one documents to fail during indexing
- execute rally with ---test-mode flag
Expected result
- since only 1 record out of 1000 failed, error rate should be 0.1%
Actual result:
- the error rate is 12.5%

**Comment by imotov** [comment]
That makes sense. Sorry, I think I just got confused because I really couldn't match the numbers that I was getting back with either the number of missing records nor with the number of bulk requests that I expected it to do.

**Comment by danielmitterdorfer** [comment]
Ok, then I think we keep this metric as is for now.
