### ISSUE TITLE
Esrallyd Benchmark Candidates should not be restricted to Elasticsearch targethosts

### ISSUE THREAD

**Issue by andyjnaylor** [elastic/rally#628]
Currently attempting to run rally cluster through `esrallyd` in a docker-compose cluster. I would like to run rally against a pre-existing Elasticsearch cluster that is not currently living on the same host as `esrallyd`. The usage of `--targethost` on the benchmark coordinator is preventing me from distributing workloads to the benchmark candidates.

**Comment by dliappis** [comment]
Hello @andyjnaylor ,

GitHub issues are reserved for _confirmed_ bugs and feature requests.
Could you please open a topic in https://discuss.elastic.co/c/elasticsearch/rally first; if we identify a bug we can reopen this one.

When you open the topic there you could clarify what you mean precisely by saying benchmark candidates; do you intend that Rally compiles Elasticsearch for you or do you intend to just use Rally in a distributed way against a present ES cluster? If latter, please take a look at the `benchmark-only` pipeline: https://esrally.readthedocs.io/en/stable/pipelines.html?highlight=pipeline#pipelines
