### ISSUE TITLE
Expose settings for SSL verification mode and provide additional CA for metrics store

### ISSUE THREAD

**Issue by jguay** [elastic/rally#629]
**Rally version** (get with `esrally --version`):
esrally 1.0.2
**Invoked command**:
esrally configure --advanced-config
**Configuration file (located in `~/.rally/rally.ini`))**:
```
[meta]
config.version = 17

[system]
env.name = metrics

[node]
root.dir = /root/.rally/benchmarks
src.root.dir = /root/.rally/benchmarks/src

[source]
remote.repo.url = https://github.com/elastic/elasticsearch.git
elasticsearch.src.subdir = elasticsearch

[benchmarks]
local.dataset.cache = /root/.rally/benchmarks/data

[reporting]
datastore.type = elasticsearch
datastore.host = es10
datastore.port = 9200
datastore.secure = True
datastore.user = elastic
datastore.password = changeme

[tracks]
default.url = https://github.com/elastic/rally-tracks

[teams]
default.url = https://github.com/elastic/rally-teams

[defaults]
preserve_benchmark_candidate = False

[distributions]
release.cache = true
```
**JVM version**:
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-2~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
**OS version**:
Debian
Dockerfile:
```
FROM python:3.7.2
RUN pip3 install esrally
RUN apt update && apt install -y default-jdk
env JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
```
**Description of the problem including expected versus actual behavior**:
Using metric store as elasticsearch cluster backed by self-signed certificate does not work - there is no option to specify verification_mode or ca so getting an error
```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate 
```

**Describe the feature**:
Ability to add CA and verification_mode for reporting elasticsearch cluster similar to client-options json : 
```
"verify_certs": false,
"ca_certs": "/home/es-rally/ca.crt"
```

**Comment by danielmitterdorfer** [comment]
@jguay thank you for raising this issue. In fact, what you're asking for is already possible and documented, see our [docs about metric store configuration options](https://esrally.readthedocs.io/en/stable/configuration.html#configuration-options) (check the "Metrics store settings"). However, I think we could do a better job making this more explicit in our docs. We'll tackle this in a separate issue.
