### ISSUE TITLE
Drop support for metrics store versions before Elasticsearch 7.0.0

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#653]
With #654 we introduce version-specific code in Rally to support metrics store versions before and after 7.0.0. We should drop support for older versions at some point to avoid version-specific code but we should wait at least a few months after 7.0.0 is out, maybe even until 8.0.0.

**Comment by dliappis** [comment]
@danielmitterdorfer One thing that we should be careful about, before releasing a new Rally version, is that the changes brought in https://github.com/elastic/rally/pull/648/files, e.g. the removal of `"template":`  break backwards compatibility with Elasticsearch metric stores older than 6 e.g. 5.6.x (see https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking_60_indices_changes.html#_index_templates_use_literal_index_patterns_literal_instead_of_literal_template_literal). Also the use of `_doc` as a type name isn't acceptable in ES 5.x.

Not sure how many users still use ES 5.x as a metric store but there was at least one in https://discuss.elastic.co/t/esrally-is-now-report-support-es7/177412/8?u=dliappis

**Comment by danielmitterdorfer** [comment]
We should also ensure we mention this in the migration guide and also change the minimum required version in the [configuration docs](https://github.com/elastic/rally/blame/master/docs/configuration.rst) accordingly.

**Comment by danielmitterdorfer** [comment]
We can also think about adding an ILM policy for the metrics store once this is done.
