### ISSUE TITLE
Rally docs do not appear in search results for "rally" on ReadTheDocs

### ISSUE THREAD

**Issue by jasontedor** [elastic/rally#672]
Visit [Read the Docs](https://readthedocs.org) and [search](https://readthedocs.org/search/?q=rally) for "rally". Note that *this* Rally project does not appear in the results. I think there are a few ways that this can be fixed:
1. `esrally` [does not have a description](https://readthedocs.org/search/?q=esrally) in the search results; perhaps expand the description that includes the term `rally` as it appears the description is used in the search
2. I hesitate to propose this because of the breakage: `esrally` is actual name of the project; maybe we could change to `es-rally` for tokenization that would include the `rally` term

**Comment by danielmitterdorfer** [comment]
Good catch. The project had a description on readthedocs; I don't know why it did not show up. I have updated the description now to include "Rally" and verified that it also shows up now if I search for "rally". As this less invasive approach already solved the issue I think we don't need to change the name to `es-rally`.

**Comment by jasontedor** [comment]
Thanks @danielmitterdorfer.
