### ISSUE TITLE
the esrally 1.0.4 with offline can't install in Centos 7

### ISSUE THREAD

**Issue by zqc0512** [elastic/rally#685]
the esrally 1.0.4 with offline can't install in Centos 7
i find it.
slove 
please add the MarkupSafe file with linux.
like MarkupSafe-1.1.0-cp37-cp37m-manylinux1_x86_64.whl  with python 3.7 
like  MarkupSafe-1.1.0-cp36-cp36m-manylinux1_x86_64.whl with python 3.6 
it now only support macos.

**Rally version** (get with `esrally --version`):

**Invoked command**:

**Configuration file (located in `~/.rally/rally.ini`))**:

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by danielmitterdorfer** [comment]
Thanks for your interest in Rally! This is already a known issue and fixed by https://github.com/elastic/rally/pull/682 which will be included in the next release of Rally.
