### ISSUE TITLE
download.sh didn't work 

### ISSUE THREAD

**Issue by copybash** [elastic/rally#724]
**Rally version** (get with `esrally --version`): esrally 1.1.0

**Invoked command**: sh ~/.rally/benchmarks/tracks/default/download.sh geopoint

**Configuration file (located in `~/.rally/rally.ini`))**:

**JVM version**:

java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**OS version**: CentOS Linux release 7.1.1503 (Core)

**Description of the problem including expected versus actual behavior**:  documents.json.bz2 and documents-1k.json.bz2 are unavailable. They are HTML pages.
.
**Steps to reproduce**:
 1.  curl http://benchmarks.elasticsearch.org.s3.amazonaws.com/corpora/geopoint/documents.json.bz2
 2. curl http://benchmarks.elasticsearch.org.s3.amazonaws.com/corpora/geopoint/documents-1k.json.bz2
 3.

**Describe the feature**:

Curl can not download files from AWS S3 now, also in download.sh.

**Comment by dliappis** [comment]
Thanks very much for your interest in Rally.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/c/elasticsearch/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/c/elasticsearch/rally) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
