### ISSUE TITLE
Missing attach_to_node call for telemetry devices in DockerLauncher

### ISSUE THREAD

**Issue by ebadyano** [elastic/rally#733]
We are missing a call to `attach_to_node` in DockerLauncher. It causes DiskIo telemetry device not to work correctly and missing data in metric store for bytes read and written.

**Comment by ebadyano** [comment]
Discovered during https://github.com/elastic/rally/pull/731

**Comment by danielmitterdorfer** [comment]
Addressed by #784 but see also #785.
