### ISSUE TITLE
Move unit-test JSON text into resources

### ISSUE THREAD

**Issue by drawlerr** [elastic/rally#734]
Currently, JSON responses expected by unit tests are inline literals, which is making our python tests rather large.  We could reduce some unnecessary bulk by moving these responses into separate files.

**Comment by bartier** [comment]
This looks like a old issue, is this open to help? If yes, would it be possible to have an migration example? I could replicate to the others test cases it applies to.

**Comment by danielmitterdorfer** [comment]
> If yes, would it be possible to have an migration example?

I've created a draft PR in https://github.com/elastic/rally/pull/1033 with a possible approach. Once that discussion is finished and the PR is merged I think we can use that example as the basis for the rest of the tests.

**Comment by danielmitterdorfer** [comment]
We've discussed this in our sync and we decided to keep the inline literal dicts so code and test data are closely linked. Hence I'm closing this issue.
