### ISSUE TITLE
Support socks proxies

### ISSUE THREAD

**Issue by ThorbenJ** [elastic/rally#738]
**Rally version** (get with `esrally --version`):
esrally 1.2.1

**Invoked command**:
/Library/Frameworks/Python.framework/Versions/3.7/bin/esrally --track http_logs --target-hosts=10.96.63.140:9200 --pipeline=benchmark-only

**Configuration file (located in `~/.rally/rally.ini`))**:
n/a

**JVM version**:
That with ECK 0.9 using the 7.3.0 ES docker image

**OS version**:
OS X 10.14.6
Docker for OS X 2.1.0.0
Kubernetes 1.14.3
ECK 0.9
Elastic Stack images for 7.3.0

**Description of the problem including expected versus actual behavior**:
In the `init()` function of `/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/esrally/utils/net.py` there is no detection of a socks proxy. If http_proxy, https_proxy and/or all_proxy has one of the following schemas: socks, socks5 or socks4: urllib3's SOCKSProxyManager should be used instead of ProxyManager. 
see: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#proxies

(The must have enabled socks support: pip3 install urllib3[socks])
(I also note that only http_proxy envvar is checked)

This feature is really useful with Docker for OS X, as it has a builtin socks proxy.

**Steps to reproduce**:
 1. Install Docker for OS X on OS X
 2. Add `"socksProxyPort" : 8888,` to `Library/Group\ Containers/group.com.docker/settings.json` (Docker Desktop restart required!)
 3. Configure proxy use: `export http_proxy=socks5://localhost:8888` (consider also https_proxy and/or all_proxy)
 4. Run the esrally command given above (note your ES services IP will be different)

**Provide logs (if relevant)**:
```

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/esrally", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/esrally/rally.py", line 677, in main
    net.init()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/esrally/utils/net.py", line 41, in init
    proxy_headers=urllib3.make_headers(proxy_basic_auth=parsed_url.auth))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/poolmanager.py", line 391, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme socks5
```

**Describe the feature**:
Please implement support for accessing ES via a socks proxy, as detailed above.

Using the built in socks proxy is much easier than messing around with port forwards, and is seamless in web browsers. It only become an issue for applications (such as esrally) that have not yet implemented socks support.

**Comment by danielmitterdorfer** [comment]
Thanks for the analysis. I'm putting this on the backlog for now but I think this might also be a nice little project to get started / involved with Rally development.

**Comment by danielmitterdorfer** [comment]
The proxy connection here is used when Rally itself connects to the Internet in order to download tracks or corpora (data sets) but Socks proxy support should probably also be considered in #382 when Rally connects to the Elasticsearch cluster that is being benchmarked.

**Comment by danielmitterdorfer** [comment]
We currently have no intention to support this in Rally. Benchmarking with intermediate proxies is also tricky because users need to pay extra attention not to introduce accidental bottlenecks. When we reconsider to support this in the future we can reopen the issue but I'm closing it for now to indicate that will not work on this for the foreseeable future.
