### ISSUE TITLE
Internet connection test failure

### ISSUE THREAD

**Issue by pitshou** [elastic/rally#742]
**Rally version** (get with `esrally --version`): 1.2.1

**Invoked command**: esrally list tracks

**Configuration file (located in `~/.rally/rally.ini`))**:

**JVM version**:

**OS version**: RHEL 7.6

**Description of the problem including expected versus actual behavior**:

The internet connection test is failing when I have connection and I can manually clone the tracks and teams repo from github

**Steps to reproduce**:
 1. install esrally
 2. run esrally  to configure it 
 3. run the esrally list tracks.

So the question is how are you testing the connection so I know to see if there is a way I can work around it.

**Provide logs (if relevant)**:
Don't think it's relevant as I am trying to understand the test process here to see if I can suggest anything.

**Describe the feature**:

**Comment by dliappis** [comment]
Thanks very much for your interest in Rally.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/c/elasticsearch/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/\) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
