### ISSUE TITLE
QPS testing

### ISSUE THREAD

**Issue by madonhe** [elastic/rally#753]
I want to know which Metric is QPS
How do you recommend me to do QPS testing?

**Comment by dliappis** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Rally forum](https://discuss.elastic.co/c/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/rally) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
