### ISSUE TITLE
Provide more clues to what's causing the error SSL: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by geekpete** [elastic/rally#757]
**Rally version** (get with `esrally --version`): 1.2.1

**Invoked command**: 

`esrally --offline --target-hosts=https://<my_ip>:9200 --pipeline=benchmark-only --client-options="timeout:120,use_ssl:true,verify_certs --report-file=test-1.csv --track-path /mnt/rally/benchmarks/tracks/default/http_logs/`

**OS version**:

```
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.04
DISTRIB_CODENAME=disco
DISTRIB_DESCRIPTION="Ubuntu 19.04"
```

**Description of the problem including expected versus actual behavior**:

When using SSL options against a non-ssl endpoint, the error message is a bit cryptic as to what has failed.

```
[ERROR] Cannot race. Error in race control (ConnectionError([SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1056)) caused by: SSLError([SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1056)))
```

**Steps to reproduce**:

I saw this issue using `--client-options="timeout:120,use_ssl:true,verify_certs:false` against an endpoint with  `--target-hosts=https://whateverhost` 

Setting `use_ssl` to false and leaving verify_certs:false still saw the error occurring.
I had to remove the https and use http instead to have it correctly connect to the endpoint.

**Provide logs (if relevant)**:

**Describe the feature**:

A list of errors with possible causes/resolutions in a troubleshooting guide within the Rally docs is probably enough to steer users to the fix as I don't think this would be all that common.

Additionally, a more informative error message might give users the right hint faster (`"is this a https endpoint?"`)

**Comment by danielmitterdorfer** [comment]
I could not reproduce this exactly in the way you describe it because Rally first failed when checking the distribution-version so I had to specify it manually:

```
esrally --test-mode --pipeline=benchmark-only --target-host=https://127.0.0.1:9200 --distribution-version=7.3.0 --client-options="timeout:120,use_ssl:true,verify_certs:false"  --on-error=abort
```

After that it manifested as an error message on the command line that the REST API is not available:

```
[ERROR] Cannot race. Could not launch cluster
	Elasticsearch REST API layer is not available. Forcefully terminated cluster.
```

But in the logs I could see the error message you're refering to.

I'll soon have a fix ready that instead will show this:

```
[ERROR] Cannot race. Could not launch cluster
	Could not connect to cluster via https. Is this a https endpoint?
		ConnectionError([SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:719)) caused by: SSLError([SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:719))
```

So it provides actionable advice but also the root cause in the error message.
