### ISSUE TITLE
Support running sequence of queries as part of the search operation

### ISSUE THREAD

**Issue by talevy** [elastic/rally#780]
Similar to #486 and the request to replay queries from the slow log (https://github.com/elastic/rally/issues/262#issuecomment-359829313), I think it would be awesome to pass a line-delimited file with all the queries that should be run and have Rally execute them.

**Comment by danielmitterdorfer** [comment]
Thanks for the idea! I am not sure whether you want to:

* Run the same query but with different parameters (this is already tracked in https://github.com/elastic/rally/issues/365) or
* Run completely different queries

If it is the latter then I wonder whether you'd want Rally treat them as completely different queries and run (and report) each of them separately? I'd also think that we need to run each of them for a certain number of iterations and be able to define a target throughput. I describe some of the challenges in https://github.com/elastic/rally/issues/262#issuecomment-363759337.

Happy to hear your thoughts on this.

**Comment by talevy** [comment]
thanks Daniel,

I suppose my desire challenges the purpose of the iterations and noise reduction techniques used by Rally. The goal is to use a large collection of queries to help find which types of queries are slower than others and investigate why

**Comment by danielmitterdorfer** [comment]
Sorry that it took a while to get back to you. I think we can treat this as a special case of #365. I'll add a note there so we won't forget this. Thanks for bringing this up!

**Comment by talevy** [comment]
thanks Daniel
