### ISSUE TITLE
The URL require username and password to login!

### ISSUE THREAD

**Issue by Reza-Abdinezhad** [elastic/rally#827]
The URL of installation of Python for RHEL / CentOS 6 and 7 require username and password to login!

RHEL / CentOS 6 and 7

Please refer to the [installation instructions for Python 3.5 in the Red Hat Software Collections.](https://www.softwarecollections.org/en/scls/rhscl/rh-python35/)

**Comment by dliappis** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Rally forum](https://discuss.elastic.co/c/elasticsearch/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch/rally) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
