### ISSUE TITLE
Update force-merge operation to only force-merge track specific indices

### ISSUE THREAD

**Issue by rohitnair** [elastic/rally#835]
It looks like the existing force-merge operation by default performs a force-merge on all indices by passing "_all" as the index parameter. It might be better to scope this to only the indices created by the current rally track, or allow the user to specify a specific index to force-merge, similar to how other operations like delete-index currently work. 

It seems like it should be a fairly minor change, and I can submit a pull request for this if this sounds good.

**Comment by danielmitterdorfer** [comment]
Agreed, the behavior you're describing makes sense. Thanks for offering to work on a PR. Just some hints for the PR: To make this work, you'd need to add a new "parameter source" for force merge that derives the indices by itself. You can look at `SearchParamSource` for an example:

https://github.com/elastic/rally/blob/47e3d025a4c2ddffdfd52c3c8e039eab0c073621/esrally/track/params.py#L345-L350

The corresponding parameter source needs to be registered so it can be used for the force-merge operations, see here:

https://github.com/elastic/rally/blob/47e3d025a4c2ddffdfd52c3c8e039eab0c073621/esrally/track/params.py#L918-L924

Finally, the force merge runner needs to use the `index` parameter from the provided `params` dictionary:

https://github.com/elastic/rally/blob/47e3d025a4c2ddffdfd52c3c8e039eab0c073621/esrally/driver/runner.py#L570-L581

**Comment by rohitnair** [comment]
Thanks for the hints. I've created a pull request for this - https://github.com/elastic/rally/pull/865
