### ISSUE TITLE
custom tracks

### ISSUE THREAD

**Issue by sadeek** [elastic/rally#837]
**Rally version** (get with `esrally --version`):

**Invoked command**:

**Configuration file (located in `~/.rally/rally.ini`))**:

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:
I.m running esrally 1.3.0 OS Rhel7, and I'm trying to create custom repo using below URL : https://esrally.readthedocs.io/en/stable/adding_tracks.html

but after certain stage it giving below error 

 esrally --distribution-version=6.0.0  --track-path=/root/.rally/tracks/tutorial

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

[WARNING] No Internet connection detected. Automatic download of track data sets etc. is disabled.
[ERROR] Cannot race. Error in mechanic (('Expected a git repository at [/root/.rally/tracks/tutorial/teams/default] but the directory does not exist.', None))

Getting further help:

**Comment by dliappis** [comment]
Thanks very much for your interest in Rally.

This appears to be a user question, and we'd like to direct these kinds of things to the [Rally forum](https://discuss.elastic.co/c/elasticsearch/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch/rally) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
