### ISSUE TITLE
Fix linting issues reported by `make precommit`

### ISSUE THREAD

**Issue by dliappis** [elastic/rally#838]
Now that we got infrastructure to enforce coding conventions in #794 we need to start coming up with PRs to fix issues. This issue tracks the effort and should be only closed when `make precommit` succeeds with no errors reported.

 - [ ] W0707 (raise-missing-from) - 439
 - [ ] C4001 - 283
 - [ ] W0613 - 158
 - [x] C0330 - 98 @ebadyano #1164
 - [ ] W0621 - 95
 - [x] C0415 - 56 @danielmitterdorfer #1131
 - [x] W0612 - 36 @hub-cap #1076
 - [x] W0221 - 30 @hub-cap #1081 
 - [x] C0301 - 30 @hub-cap #855
 - [x] E1120 - 27 @hub-cap #1084 
 - [x] W0212 - 25 @hub-cap #1083 
 - [x] C0303 - 21 @hub-cap #854
 - [ ] C0302 - 12
 - [x] W0404 - 10 @hub-cap #1080
 - [x] W0106 - 9 @hub-cap #1082 
 - [x] C4002 - 9 @hub-cap #1079
 - [x] R1722 - 5 @hub-cap #1077
 - [x] R0904 - 5 @danielmitterdorfer #1127
 - [x] W0311 - 4 @ebadyano #1021
 - [x] W0107 - 4 @hub-cap #1073 
 - [x] W0105 - 4 @danielmitterdorfer #1039
 - [x] W0235 - 3 @hub-cap #1072
 - [x] W0104 - 3 @danielmitterdorfer #1039
 - [x] R1707 - 3 @danielmitterdorfer #1038
 - [x] R1704 - 3 @danielmitterdorfer #1010
 - [x] C0121 - 3 @ebadyano #1021
 - [x] E1128 (assignment-from-none) - 2 @danielmitterdorfer #1113
 - [x] W1201 - 2 @drawlerr #869
 - [x] W0631 - 2 @drawlerr #868 
 - [x] W0143 - 2 @drawlerr #867
 - [x] W0108 - 2 @hub-cap #849 
 - [x] W0102 - 2 @hub-cap #848 
 - [x] C0305 - 2 @hub-cap #847
 - [x] W1202 - 1  through e0601: @drawlerr #845 
 - [x] W0706 - 1
 - [x] W0702 - 1
 - [x] W0201 - 1
 - [x] W0127 - 1
 - [x] R1723 - 1
 - [x] R1714 - 1
 - [x] R1706 - 1
 - [x] R1702 - 1
 - [x] R0916 - 1
 - [x] R0911 - 1
 - [x] E0601 - 1
 - [x] C0122 - 1 @hub-cap #843

**Comment by dliappis** [comment]
@drawlerr some top level guidelines to make the corresponding PRs more manageable to review and focus on important topics:

1. This is frequency chart of warnings/errors/etc. (used `make precommit | grep -e '[CRWE][0-9]\{4\}' | awk -F ':' '{print $4}' | sort | uniq -c | sort -n -k 1,1 -r`):

```
 283  C4001
 158  W0613
  98  C0330
  95  W0621
  60  C0326
  56  C0415
  36  W0612
  30  W0221
  30  C0301
  27  E1120
  25  W0212
  21  C0303
  12  C0302
  11  C4002
  10  W0404
   9  W0106
   5  R1722
   5  R0904
   4  W0311
   4  W0107
   4  W0105
   3  W0235
   3  W0104
   3  R1707
   3  R1704
   3  C0121
   2  W1201
   2  W0631
   2  W0143
   2  W0108
   2  W0102
   2  C0305
   1  W1202
   1  W0706
   1  W0702
   1  W0201
   1  W0127
   1  R1723
   1  R1714
   1  R1706
   1  R1702
   1  R0916
   1  R0911
   1  E0601
   1  C0122
```

2. `C4001` i.e. `Invalid string quote ', should be " (invalid-string-quote)` is very common in unit tests; the intention is **not** so satisfy `pylint` and sacrifice readability, so, as an example this would be a valid way to bypass the error in a unit test while retaining readability:

    ```
    # pylint: disable=invalid-string-quote
    assert foobar.to_dict('{"k":2, "l":3.4, "m":true, "n":"str"}') == {"k": 2, "l": 3.4, "m": True, "n": "str"}
    ```

3. One suggestion is to split PRs that address one or more of those categories, e.g. one PR to deal with `C4001`. If the top two offenders result in huge PRs that are difficult to review, it's ok to additionally split them up e.g. one for core Rally files and another for the unittests.

**Comment by drawlerr** [comment]
Bumping out to 1.5.0 as:
 - This issue has more work to do
 - 1.4.1 is otherwise ready to go
 - it's not worth delaying the release for what appear to be primarily a code-cosmetic issue

**Comment by michaelbaamonde** [comment]
I think we can close this one. `make precommit` returns no errors on `master` these days.
