### ISSUE TITLE
Clarify the impact on refreshes for node-stats telemetry

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#846]
In the [docs of the node stats telemetry device](https://esrally.readthedocs.io/en/stable/telemetry.html#node-stats) we state:

> Using this telemetry device will skew your results because the node-stats API triggers additional refreshes. Additionally a lot of metrics get recorded impacting the measurement results even further.

Furthermore, when this telemetry device is used, we issue the following warning:

> [WARNING] You have enabled the node-stats telemetry device, but requests to the _nodes/stats Elasticsearch endpoint trigger additional refreshes and WILL SKEW results.

This is only the case before Elasticsearch 7.2 and has been fixed with https://github.com/elastic/elasticsearch/pull/40458. Therefore we should clarify that this only applies to Elasticsearch before 7.2 and maybe issue the warning also only for versions before 7.2.

**Comment by bartier** [comment]
I'd like to work on this if possible. =)

Can you provide more information how can I get information about Elasticsearch that is going to be used? 

Looking at the classes, I found `BareProvisioner` that I think just provision the distribution that is set in the command line, is there any idea how can I get this information in the `NodeStats` class? I'm actually newbie at rally yet haha.

**Comment by danielmitterdorfer** [comment]
> I'd like to work on this if possible. =)

Sure, please go ahead. :)

> Can you provide more information how can I get information about Elasticsearch that is going to be used?

You can have a look how it is done in `ClusterEnvironmentInfo#on_benchmark_start()` by calling the node info API. Note that the `NodeStats` telemetry device can work with multiple clusters (e.g. necessary for cross-cluster-replication) and you need to extract the proper client first, i.e. something along the lines of:

```python
default_client = self.clients["default"]
info = default_client.info()
```

We have a utility function in `esrally.utils.versions` that is called `components` which will split that version string into major, minor, patch etc. which you can use for the version check.

Summarizing the goals of this PR: 

* The warning should only be emitted for clusters < version 7.2.0
* The docs should contain a hint that this is only a problem for clusters < version 7.2.0

I hope that helps.
