### ISSUE TITLE
Private custom track repository and corpora URLs

### ISSUE THREAD

**Issue by vincentarnaud90** [elastic/rally#866]
**Describe the feature**:
It's impossible, with offline mode, tu use custom repository for tracks without cloning manually or download custom corpora on private repo though these repositories are accessibles. It would be great if custom repository are cloned even in offline mode.  
It would also be a nice addition to allow custom probing URLfor internet connection, thus in an environment where things like elasticsearch sources, corpora, ...etc are mirrored and provided that one configure properly the rally.ini file, it is possible to run rally in online mode.

**Comment by danielmitterdorfer** [comment]
Sorry for getting back to you so late but it seems this issue has fallen through the cracks. 

IMHO you raise a valid point and we should solve this by making the probing URL configurable via rally.ini` instead of always using `https://github.com/`as probing URL.

**Comment by bartier** [comment]
@danielmitterdorfer @vincentarnaud90 Can you guys provide an example to reproduce this?

A single command example with flags to use with `esrally` is enough I guess? I'm new to rally and I'd like to help if possible.

**Comment by danielmitterdorfer** [comment]
The scenario is that the machine is connected to a network  but that network cannot reach https://github.com/. Also the user has configured Rally (via `~/.rally/rally.ini`) so that it does not need to connect outside of the corporate network. The simplest approach I can think of to simulate this is to add the following line to `/etc/hosts`:

```
0.0.0.0 github.com
```

Please be aware of the side effects of this change: this means that you will not be able to connect to Github from your machine (even via your browser) as long as this entry exists in `/etc/hosts`. So please make sure to remove this entry again after you have finished testing.

The way I'd approach this is to add bump the config format version in https://github.com/elastic/rally/blob/master/esrally/config.py. We also need to add a config file migration that sets the default to `https://github.com` (so existing users are not affected).

Then I'd read this value on startup and pass it in https://github.com/elastic/rally/blob/47ffe654ce8a177835679d9dc8b42de9791f28c3/esrally/utils/net.py#L172-L186

**Comment by bartier** [comment]
@danielmitterdorfer Thanks for your explanation!

> We also need to add a config file migration that sets the default to https://github.com (so existing users are not affected).
Is this necessary? If yes, can you provide more information about config file migration?

I thought about a implementation that considers "https://github.com" a default value if in `rally.ini`does not has a specific value, so migration could be avoid:
```
    if not args.offline:
        probing_url = cfg.opts("system", "probing.url", default_value="https://github.com", mandatory=False)
        if not net.has_internet_connection(probing_url):
            console.warn("No Internet connection detected. Automatic download of track data sets etc. is disabled.",
                         logger=logger)
            cfg.add(config.Scope.applicationOverride, "system", "offline.mode", True)
        else:
            logger.info("Detected a working Internet connection.")
```
Is this valid or this config should be mandatory to exists in rally.ini? If yes, could you provide more information about config file migrations?

The current version of rally.ini is 17. Is a new "url.probing" going to make this to be 18?
```
[meta]
config.version = 17
```

In [migration](https://github.com/elastic/rally/blob/047b0ffb40f9a50d9fa99486a5518c5e044b2337/esrally/config.py#L521), I guess I would have to make something like that to create a valid migration to 17 -> 18:

```
    if current_version == 17 and target_version > current_version:
        # Do stuff about probing url
        ...
```

I'd like to work on this issue =)

**Comment by danielmitterdorfer** [comment]
@bartier your suggestion makes sense to me. Let's avoid the migration and use a default value.

In order for users to be able to change the behavior, can you please add something along the lines of the following to https://github.com/elastic/rally/blob/master/docs/offline.rst?

```diff
diff --git a/docs/offline.rst b/docs/offline.rst
index 3f126dc..751ceff 100644
--- a/docs/offline.rst
+++ b/docs/offline.rst
@@ -15,7 +15,7 @@ Rally will automatically detect upon startup that no Internet connection is avai

     [WARNING] No Internet connection detected. Automatic download of track data sets etc. is disabled.

-It detects this by trying to connect to ``github.com``. If you want to disable this probing you can explicitly specify ``--offline``.
+It detects this by trying to connect to ``https://github.com``. If you want it to probe against a different HTTP endpoint (e.g. a company-internal git server) you need to add a configuration property named ``probing.url`` in the ``system`` section of Rally's configuration file at ``~/.rally/rally.ini``. Specify ``--offline`` if you want to disable probing entirely.
```

**Comment by bartier** [comment]
@danielmitterdorfer Sure! I sent a PR #909 that closes this issue.

**Comment by vincentarnaud90** [comment]
Great, thank you !
