### ISSUE TITLE
How to modify the setting parameters of the index

### ISSUE THREAD

**Issue by k3v8ns** [elastic/rally#889]
i want to modify all index settings config  in index_settings.

rally version: 1.3.0 
cmd:
esrally race  --track=geonames --track-params=index_settings:
["index.number_of_shards:1","index.number_of_replicas:1"]
or 
esrally race --track=geonames --track-params=index_settings:{"index":{"number_of_shards":1,"number_of_replicas":1}}

 but return as :

index_settings:[index.number_of_shards:1,index.number_of_replicas:1]
Traceback (most recent call last):
  File "/root/miniconda3/bin/esrally", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.7/site-packages/esrally/rally.py", line 633, in main
    cfg.add(config.Scope.applicationOverride, "track", "params", opts.to_dict(args.track_params))
  File "/root/miniconda3/lib/python3.7/site-packages/esrally/utils/opts.py", line 84, in to_dict
    return default_parser(csv_to_list(arg))
  File "/root/miniconda3/lib/python3.7/site-packages/esrally/utils/opts.py", line 71, in kv_to_map
    k, v = kv.split(":")
ValueError: too many values to unpack (expected 2)

as follows :

from rally-tracks/geonames/challenges/default.json
```json
        {
          "operation": {
            "operation-type": "create-index",
            "settings": {{index_settings | default({}) | tojson}}
          }
        }
```
and  README.MD
index_settings: A list of index settings. Index settings defined elsewhere (e.g. number_of_replicas) need to be overridden explicitly.

but i cannot find the way to modify the index_settings???

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Rally.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch/Rally forum](https://discuss.elastic.co/c/elasticsearch/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for **verified** bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch/rally) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
