### ISSUE TITLE
Rally does not support windows

### ISSUE THREAD

**Issue by monk-ee** [elastic/rally#89]
**Describe the feature**: 

Rally does not support windows at all - it calls *nix/mac commands to discover binary locations eg. the function def guess_install_location. There are other unix only subprocess commands as well. You probably shouldn't say that it might in the README,  because it sure as heck doesn't.

That said, I have no problem with this, but it's misleading.

**Comment by danielmitterdorfer** [comment]
You're right. I've written this already in the very early stages of Rally and it would probably require a bit of effort to get it going on Windows. I'll correct the wording.
