### ISSUE TITLE
Rally silently ignores errors when creating an index

### ISSUE THREAD

**Issue by jpountz** [elastic/rally#897]
If a challenge includes an invalid body for the index creation call, Rally seems to silently ignore the error, and the index then gets created implicitly via the first bulk request.

**Comment by danielmitterdorfer** [comment]
This is intended (default) behavior. Rally is agnostic to the calls that it executes and by default we continue on errors. Did you try with `--on-error=abort`?

**Comment by jpountz** [comment]
Thanks for the explanation, this makes sense to me. I did not run with `on-error=abort`. I'm closing now but wonder that it might be worth flagging in the Rally output?

**Comment by danielmitterdorfer** [comment]
Thanks for the feedback. I've raised https://github.com/elastic/rally/issues/910 to emit warnings when this happens.
