### ISSUE TITLE
Release Rally 1.4.1

### ISSUE THREAD

**Issue by dliappis** [elastic/rally#898]
We should release Rally `1.4.1`.

The process is defined in https://github.com/elastic/rally/blob/master/RELEASE.md and [preconditions](https://github.com/elastic/rally/blob/master/RELEASE.md#preconditions) and [initial setup](https://github.com/elastic/rally/blob/master/RELEASE.md#initial-setup) need to be met/done before initiating the release.

Target date: 20200218 (Wed Feb 19 2020 15:00 UTC)

**Comment by danielmitterdorfer** [comment]
@drawlerr I think this can be closed?

**Comment by danielmitterdorfer** [comment]
The [release announcement](https://discuss.elastic.co/t/rally-1-4-1-released/220231) is out for quite a bit now so I'm finally closing this.
