### ISSUE TITLE
Warn on request errors

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#910]
By default Rally continues on request errors (`--on-error=continue`) but this might be easy to miss by users. In addition, some operations are treated as "administrative" (e.g. `create-index`) and are thus not included in the command line report by default. We should:

1. Include any operations with an error rate greater than zero in the command line report regardless whether they should be included (see https://github.com/elastic/rally/blob/97d0e85ab0cffd1f1506af96aee1e4a69310fc2a/esrally/metrics.py#L1631)
2. Emit a warning when the error rate of an operation is greater than zero (in https://github.com/elastic/rally/blob/97d0e85ab0cffd1f1506af96aee1e4a69310fc2a/esrally/reporter.py#L134)

**Comment by bartier** [comment]
@danielmitterdorfer Hi! Can I work on this?

1) I'd purpose something in the lines:
`if task.operation.include_in_reporting or error_rate > 0 `
"Administrative" operations would be in the report if error happens (error_rate > 0)

2) Add warnings at the end of the  command line report:
```
def add_warnings(self, warnings, values, op):
    if values["error_rate"] > 0:
        warnings.append(f"Error rate is {values['error_rate']} for operation '{op}'. Please check the logs.")
   ...
   ...
```

**Comment by danielmitterdorfer** [comment]
@bartier sure, thanks for working on it. :) 

I thought about your idea to force-include failed tasks in the report as follows:

```python
 if task.operation.include_in_reporting or error_rate > 0 
```

and I think that makes sense. Looking forward to your PR.
