### ISSUE TITLE
Custom plugin version

### ISSUE THREAD

**Issue by vincentarnaud90** [elastic/rally#920]
**Describe the feature**:
Hello, I have a custom plugin and I'd like to know if it's possible to make the version dynamique directly in rally.ini's `[distributions]` section ? The plugin does not follow elasticsearch's version numbers as there are multiple plugin versions for a single elastic version, so placeholder `{{VERSION}}` doesn't work in this case.    
I'm aware that I can build it from sources with specific git revision using `--revision` flag but I'd like to avoid that as it's already build and published somewhere.

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Rally.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch/Rally forum](https://discuss.elastic.co/c/elasticsearch/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for **verified** bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch/rally) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by vincentarnaud90** [comment]
Thanks, I'll do that, sorry for the mistake.
