### ISSUE TITLE
Externalize number of tries until es rest api is availiable parameter

### ISSUE THREAD

**Issue by hub-cap** [elastic/rally#924]
as pointed out [here](https://discuss.elastic.co/t/unable-to-increase-rest-api-startup-timeout/221719) there is no way to alter the number of tries we attempt to contact ES to make sure the cluster is online, nor the sleep time between each wait. It would make sense to externalize one of these, I think.

**Comment by hub-cap** [comment]
I am not taking this issue over just yet, I am only assigning myself to raise awareness in my mind. If a community member would like to take this over, feel free and I can help shepherd it along.

**Comment by spayne-undo** [comment]
Nice one @hub-cap many thanks.

**Comment by danielmitterdorfer** [comment]
IMHO the current timeout of 2 minutes is sufficient. If there are clusters that take longer than that to start this needs to be investigated separately. 

Furthermore, we have recently added a new mode that allows users to [manage Elasticsearch clusters independently of benchmark execution](https://esrally.readthedocs.io/en/stable/cluster_management.html). Here is the intended execution flow:

1. Install all Elasticsearch nodes with the `install` subcommand, then start them using the `start` subcommand
2. Run the benchmark with the pipeline `benchmark-only`
3. Stop all nodes using the `stop` subcommand

As each step is a separate invocation of Rally, there is nothing that prohibits additional steps in between, e.g. a dedicated check or a `sleep` in between 1 and 2.

Therefore, I propose we don't change this and close this issue instead. Any thoughts on this @elastic/es-perf?

**Comment by dliappis** [comment]
As @danielmitterdorfer mentioned above, I think adding additional configurability for the pipelines that do the installation/launching is not a great use of time, as we'll be steering towards the [separate steps for cluster management](https://esrally.readthedocs.io/en/stable/cluster_management.html) and the `benchmark-only` pipeline.

**Comment by spayne-undo** [comment]
Thanks @danielmitterdorfer and @dliappis . Since there is a way of managing startup independently of benchmarking, that goes some way towards removing the problem. Some people ask for benchmark measurements to include full cluster start-up time so in that case it wouldn't help. But for the purpose I originally asked about, and given we can hack the source code to change the timeout if needed, it isn't a problem.

**Comment by danielmitterdorfer** [comment]
Thanks for the feedback @spayne-undo. Let's close this in that case then.
