### ISSUE TITLE
update chart-generator so it sets Axis min to 0

### ISSUE THREAD

**Issue by ebadyano** [elastic/rally#989]
![image](https://user-images.githubusercontent.com/26631211/81316454-971d7280-9059-11ea-9009-e9aa9c582d1e.png)
Kibana sets Axis to something else by default based on the data and not to 0.

**Comment by danielmitterdorfer** [comment]
According to the configuration in our nightlies we see `axis_min` set to zero, in the UI as well as in exported objects so maybe this was just an issue with Kibana but in any case it's working properly now so I'm closing this issue.
